### ISSUE TITLE
[8]UI and API for crowdsourcing of software component intent

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#1002]
#### Description:
As an OSIO analytics user, I would like to add a valid intent for a component to the existing list of intents in the stack report so that the component gets categorized properly.

#### Acceptance Criteria
*  The stack reports UI provides the means to enter a new intent to the user.

#### Tasks
- [x] Create a API end point that accepts the component and intent list and pushes the same to S3
- [x] Update the Stack Report UI to allow the user to enter some intent for each component
- [ ] Finalising UI with the appropriate look and feel
- [x] Create a PR for the API
- [x] Create a PR for the UI changes

#### Steps followed to achieve this story
- Created a bucket in S3 which is `jgotta-bayesian-user-intent`. This names changes as per the environment the application is running on. Here is the link for the bucket https://s3.console.aws.amazon.com/s3/buckets/jgotta-bayesian-user-intent/?region=us-east-1&tab=overview
- The json structure i am following to store the intent data in like this below 
```
  {
  "component": "argcomplete",
  "intent": [
    "test",
    "test2"
    ]
  }
```
- If a object exists with the component name for which we are trying to store the intent, we update the object. If not we create a new object in the bucket with the component name and intent list.
- Add a popover component in the categories column for each component. 
- User can enter intents as free form text separated with commas
- Once the intent gets successfully added to S3, we show a notification to the user

**Comment by jyasveer** [comment]
PR's for this US -
https://github.com/fabric8-ui/fabric8-recommender/pull/331
https://github.com/fabric8-analytics/fabric8-analytics-server/pull/167

**Comment by sunilk747** [comment]
@samuzzal-choudhury What is the progress for this user story. If it's completed can we close it now?

**Comment by sunilk747** [comment]
@samuzzal-choudhury Can we close this issue?
