### ISSUE TITLE
[3]Bug Fixing in Devstudio.

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#1007]
5 crucial bugs need to be fixed.

- [x] Remove 'server' directory from git repo .https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/34

- [x] Use Eclipse's jobs instead of own treads https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/29

- [x] Remove fabric8-analytics-lsp-server-test-devstudio from git repo  hhttps://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/35

- [x] Exception when running stack analyses https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/24

- [x] Stack analyses goes into infinite loop if recommender api is not set. https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/40

link to outstanding issue list https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues
