### ISSUE TITLE
[8] Green field deployment of fabric8-analytics

### ISSUE THREAD

**Issue by humaton** [openshiftio/openshift.io#1062]
# Description

As a fabric8-analytics developer, I want to be able to deploy all fabric8-analytics (f8a) services easily on the dev cluster. This will enable me to test my changes in close-to-prod environment before commiting them to master branch.

# Acceptance criteria

- the process of deploying f8a services on the dev cluster is straightforward and documented
- the process of deploying custom images containing changes not yet merged to master branch is documented
- initially allocated AWS resources are reused between redeployments, if possible

# Tasks

- [x] update existing deployment scripts
- [x] update templates for services, if necessary
- [x] update templates for secrets and config maps, if necessary
- [x] documentation is updated

**Comment by humaton** [comment]
Hi, there we are currently facing issue with accessing AWS RDS from the dev cluster.
Problem is that we either have to create VPC configuration for the dev cluster or make RDS publicly accessible.
Development of the script is happening on my fork.
https://github.com/humaton/fabric8-analytics-common

**Comment by msrb** [comment]
I tested the script. It works, but it's a bit clunky.

- keycloak URL could be predefined
- deployment prefix could be just `$(oc whoami)`, `msrb-greenfield-test` is too long
- the old analytics spark training job is failing; AFAIK this jobs is not needed any more, we can skip it
- running the script twice fails with `FATAL:  password authentication failed for user "coreapi"`
