### ISSUE TITLE
[13][Spike] Tagging packages using LDA/NMF and TextRank to increase coverage and accuracy of tags

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#1095]
### Description

As discussed in the [proposal on the mailing list](https://docs.google.com/document/d/1fdA4zKotLY_7vnimAp5cW80yFqaoHMCowRK4pRCQeeQ/edit#), the plan here is to use TextRank and LDA/NMF for tagging packages in an attempt to increase the coverage and quality of tags. [Previous work results](https://docs.google.com/spreadsheets/d/1X6ClIqc3sJZXR7mrl0RvJ9FxM9q2tJfJkdjRatybyFo/edit#gid=0).

### Acceptance criteria

Validate the proposed approach for the Maven and NPM ecosystems, tweak the same otherwise. Come up with plan/task list to get the final approach ready for production.

### Task List
- [x] Write code for evaluation metric based on ROUGE-1 recall and precision.
- [x] Validate the LDA based approach for packages in the Maven ecosystem
- [x] Validate the TextRank based approach for the NPM ecosystem
- [x] Tweak the approach/try alternatives methods if required

#### Task list for NPM

- [x] Gather data from Github
- [x] Data cleaning
- [x] Tag packages using TextRank on the Github readme for these projects (analytics worker)
- [x] Calculate the ROUGE-1 recall of the generated tags against the repository descriptions
- [x] Aggregate the generated tags into a master list
- [x] Run the sparsity measures to check the accuracy of the tags

#### Task list for Maven

- [x] Gather stackoverflow data for packages using Google Bigquery
- [x] Data cleaning
- [x] Tag packages using LDA on Stack Overflow data/ Google search data.
- [x] Measure the ROUGE-1 recall and precision against descriptions collected by core
- [ ] (Experimental) Validate the generated tags using the alternative source - stack overflow through Google search data and Google search data through stack overflow tag descriptions.

### Dependencies

None for now, will discuss this.

**Comment by rootAvish** [comment]
Blocked due to lack of AWS console access.

**Comment by rootAvish** [comment]
Will be blocked once we get around to maven.

**Comment by krishnapaparaju** [comment]
@rootAvish are you still blocked with AWS console access ???

**Comment by rootAvish** [comment]
@krishnapaparaju Yes, need it for working with Maven, and to avoid collecting more NPM data. Was working with a set of ~90 packages collected for NPM on the TextRank based approach. Stackoverflow data will be fetched from big query but need the maven package data collected by core that is present in AWS.

**Comment by rootAvish** [comment]
### Results for NPM

Implementation in code: https://github.com/fabric8-analytics/devnull/pull/10
using standard textrank approach:

```` {'ROUGE-1': 0.25047, 'ROUGE-2': 0.09449, 'ROUGE-L': 0.24696, 'ROUGE-SU4': 0.12192} ````

this is with thresholding done.

Using a levenshtein distance based implementation of textrank:

```` {'ROUGE-1': 0.32795, 'ROUGE-2': 0.06353, 'ROUGE-L': 0.32327, 'ROUGE-SU4': 0.11858} ````

This implementation however requires thresholding, the standard implementation once improved on would be the best approach to productionise. I believe we can collect tags for all of NPM using that apporach(wherever we have a readme).

If any coverage remains, we can fallback to the LDA based approach we are using for maven (WIP).

**Comment by miteshvp** [comment]
Previously collected Vertx/Springboot packages can be found [here](https://gist.github.com/miteshvp/608307e0f5029079790f2ded1db3ed5c)
It also contains tags that came out accurate using automated tagging effort.
*Accuracy was arrived at after comparing top 4 automated tags vs. manual tag collected previously for a subset of Vertx/Springboot packages*

**Comment by rootAvish** [comment]
For NPM see: #1268
