### ISSUE TITLE
[5] Improve Vertx/Springboot coverage to 100% of top Github Stacks by Manual tagging effort

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#1118]
### Description
Automated tags can not be captured due to multiple reasons such as dependent component being a private repo, Github url being stale, No information on mvncentral, etc. Also, not all the components automatically tagged may result in accurate tags.

This task is about manual tagging of each of the Vertx and Springboot components that are part of top popular `Github Stacks [1]` and for which automated tagging could not collect meaningful tags.

#### Acceptance Criteria
All the components of Vertx and Springboot components are tagged and results available in S3 for analytical models to be trained.

```
[1] - Github query to identify top popular Stacks
*Vertx* - filename:pom.xml vertx language:java stars:>1
*Springboot* - filename:pom.xml springboot language:java stars:>1
```

##### Task List
- [x] Gather master tag list collected as part of automated tagging and store in S3
- [x] Gather all the required components that needs to be tagged manually
- [x] Create component list to distribute amongst each team member
- [x] Create UI / API necessary to help team members input manual tags and store in S3 directly
- [x] Manually tag components assigned to individuals
- [x] Reduce number of training tags to 4
- [x] Test PGM with new tags.

**Comment by invincibleJai** [comment]
@miteshvp have added task list for UI with my understanding on it as of now. Please add if anything i missed.
CC @samuzzal-choudhury

**Comment by miteshvp** [comment]
@invincibleJai - can you remove UI related items from this task. It seems, they should be part of crowd sourcing work as it is more relevant there

**Comment by samuzzal-choudhury** [comment]
@miteshvp the UI task has been removed.

**Comment by sara-02** [comment]
Concerned PR for PGM scoring: https://github.com/openshiftio/saas-analytics/pull/142
