### ISSUE TITLE
[8] [Spike] GraphDB - migrate from TitanDB to JanusGraph

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#1119]
#### Description
Currently f8-analytics graph uses AWS DynamoDB with TitanDB. With TitanDB upstream community no longer active and already migrated to JanusGraph, AWS has also added support for the same. This spike is about to see any challenges we might face and list it if we migrate from existing TitanDB to JanusGraph.

##### Task List
- [ ] Initiate Gremlin-Docker with Titan layer pointing to AWS dynamodb tables
- [ ] Add some indexes and create some dummy graph nodes and edges
- [ ] Initiate Gremlin-Docker with JanusGraph pointing to same AWS dynamodb tables
- [ ] Validate all the normal graph operations still possible without any challenges
