### ISSUE TITLE
[13] [Spike] -  Graph based PGM for detecting outliers

### ISSUE THREAD

**Issue by abs51295** [openshiftio/openshift.io#1123]
### Description
Currently, PGM is not able to suggest accurate outliers. This spike is about to see if Graph DB can be used to overcome this limitation of PGM.

### Acceptance Criteria
To come up with Graph DB Design and algorithm to detect outliers.

### Task List
- [x] Design the Graph Schema for the Graph DB.

- [x] Ingest the data into Graph DB.

- [x] Query the Graph DB to verify outlier detection.

**Comment by abs51295** [comment]
Spike results are accurate as expected. Can move the approach to production in a future sprint.
