### ISSUE TITLE
POC - Machine Generated Tasks - Phase II

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1127]
### Tasks

- [x] Removing the redundant code
- [x] Removing selection from dropdown in case user clicks close.
- [x] Address flickering while on hover of component
- [ ] Bring in validation [When user submits without any data, it has to be handled]
- [ ] Bring in a mechanism to have a display of error messages [Make it generic]
- [x] Fix the added packages overlapping each other when they exceeded 1 row.
- [x] UI cosmetic changes

**Comment by samuzzal-choudhury** [comment]
New user story(ies) shall be opened for this with new requirements. Hence, closing this.
