### ISSUE TITLE
Provide capacity to support 500 concurrent users

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#1146]
## Goal
Provide capacity to support 500 concurrent users.

## Description
We need to be able to support 500 active concurrent users on OpenShift.io initially. An active user is one who has at least one space with:
- Planner with >50 work items
- Che with at least 1 workspace
- Jenkins with at least 1 build executing
- Fabric8 with at least 1 pipeline executing
- Two pods (1 stage, 1 run) active

## Tasks
- [ ] Add Che 6 (multitenant Che) to OSIO so that there is a single Che server for a cluster and there workspaces are deployed to a pod in an active tenant.
- [ ] Jenkins can be idled when users become inactive.
- [ ] OSIO able to operate across multiple OpenShift clusters.

**Comment by joshuawilson** [comment]
cc @kbsingh

**Comment by l0rd** [comment]
The first task is done. Multi tenant che is already deployed on OSIO. Most of the users are still using their dedicated Che but we are currently rolling out multi tenant Che for everybody (c.f. https://github.com/redhat-developer/rh-che/issues/107)

**Comment by bmicklea** [comment]
Thanks Mario - the idea here was to list out all the things needed for us to handle 500 concurrent users (my list may be incomplete) and link to tasks that can be sprint-scheduled for tracking.

**Comment by kbsingh** [comment]
We need multi-cluster deployed as well for this goal.
