### ISSUE TITLE
OpenShift.io Space Templates

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1217]
When a new Space is created in OpenShift.io, the creator is asked to choose from a list of available Space Templates. These templates may configure the Space in numerous ways.

Some examples of ways a template could configure a Space:
- [ ] Populate the Planner with a set of Work Item Types and a Guided Type Navigation such that the development methodology associated with the template may be easily adopted by the development team
- [ ] Populate the initial Space Dashboard with widgets aligned to the development methodology
- [ ] Add methodology-specific reports to the reporting dashboard
etc.

The schemas for the Space Templates are defined here: https://docs.google.com/spreadsheets/d/1iQ3MBitXy5zWAvxWzHQKtXuv5SWs_uUCQvrqngfm5K8/edit?usp=sharing. This needs to be moved to a more friendly location. The schemas define templates for the following methodologies:

- [ ] A simple Issue Tracker
- [ ] Scrum
- [ ] A generic Agile process
- [ ] Scenario Directed Development

## Parent Scenario
#2060 

## See also
#2032

**Comment by joshuawilson** [comment]
I'm not sure who should own it. The space template selection is a part of the Platform UI but the Planner needs to define the templates for the work-items.

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2007
