### ISSUE TITLE
Expand stack report to Node ecosystem

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#1248]
### Description
Currently, fabric8-analytics can generate stack report for Vertx and Springboot ecosystem. Need to expand the recommendations to node ecosystem as well.

#### Acceptance Criteria
- End users should be able to see recommendations for node packages that are part of top popular github stacks [1] with a recommendation accuracy of 70%

*Github query to identify top popular node stacks*
*language:javascript stars:>500 filename:package.json*

#### Items
- [ ] Ingest node data to graph (https://github.com/openshiftio/openshift.io/issues/1072)
- [x] Collect top node stacks from github
- [ ] Automated tagging for node packages (#1268)
- [ ] CI/CD for node analytical models
- [ ] Train and deploy PGM

**Comment by miteshvp** [comment]
Top node github stacks collected

**Comment by miteshvp** [comment]
Done.
