### ISSUE TITLE
Implement API to facilitate crowdsourcing through IDE

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#1271]
### User Story
As an OSIO developer I should be able to get a component to tag and save the tags for the component so that all the users can get better recommendations.

### Description:
As a fabric8-analytics developer I would like to create some API endpoints to facilitate crowdsourcing through IDE so that the tagged intents for a component are propagated to the PGM training module via the analytics verification module.

### Acceptance Criteria:
- API endpoints are to be deployed on production and integration tests for those are to be run during the end-to-end test.
- A http GET end point should exist which would return a list of tags for a given ecosystem
- A http GET end point should exist which would return a component that is not tagged for a given ecosystem
- A http POST end point should exist which would add user intent(s) for a component into Graph DB

### Work items:
- [x] API endpoint to get master tag list for an ecosystem
- [x] Create s3 adapter configuration and methods in worker to fetch master tags
- [x] Add a caching mechanism on the get master tag list, which would prevent frequent hits to s3
- [x] API endpoint to get component to be tagged
- [x] Add a method in the utils file that has the gremlin query to get the next component to be tagged
- [x] API endpoint to store user tagged intents for a component
- [x] Add a method in the utils file that has the call to graphDB with the gremlin query to add the tag nodes to the component nodes
- [x] Integration tests for the API endpoints

**Comment by samuzzal-choudhury** [comment]
@ravsa is this user story complete? If yes, can you set the label status/completed to this?
