### ISSUE TITLE
 Implement UI to facilitate crowdsourcing through IDE

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#1274]
### User Story: 
As a IDE user, I will be able to add intent tags to a given component so that it will improve recommendation system of analytics

### Description:
will be providing a UI to the IDE users to add intent tags to a given component so that the those are propagated to the PGM training module via the analytics verification module.

### Acceptance Criteria: 
- A modal UI prompt to add intent tags to a system provided component is to be provided through VSCode, Dev Studio and Eclipse plugins.
- This UI should prompt the user to tag a component for the user's relevant ecosystem with one or more intents. 

### Task list:
- [x] Create a component of user-intent for auto-suggest of tags , with capability of manual editing as well. 
- [x] User-intent component should be part of modal in stack-report screen
- [x] User-intent component should be part of new view
- [x] Creation of services in angular2 for API calls
- [x] Modifying existing UI route to dynamically load modal/screen based on route param
- [x] Integration of Master-tag list API
- [x] Integration of user-intent GET API, which would provide component name
- [x] Integration of user-intent POST API, which would submit tags to component   
- [x] Have polling in place for stack-report-ui portal for STACK-ANALYSIS GET as we have in client side

**Comment by jyasveer** [comment]
This is the workflow doc for the UI implementation
https://docs.google.com/presentation/d/1qODPBH2Lk0GV02O_Evswzwfo58tKCc3v8l6JMwKmK_s/edit#slide=id.g2a76d8ec0e_0_0

**Comment by samuzzal-choudhury** [comment]
@invincibleJai please add the label status/complete if this user story is complete.

**Comment by invincibleJai** [comment]
Added @samuzzal-choudhury
