### ISSUE TITLE
Implement timeout and counter based crowdsourcing in VSCode plugin

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#1276]
### User Story: 
As a IDE user, I will be able to add intent tags to a given component so that it will improve recommendation system of analytics

### Description:
will be providing a UI to the IDE users to performs stack analyses through VSCode after a timeout duration or after a count of stack analyses runs to add intent tags to a given component so that the those are propagated to the PGM training module via the analytics verification module.

### Acceptance Criteria:
The IDE user should see a modal prompt in the stack report UI to provide intent tag for a component of user's relevant ecosystem when the user performs stack analyses through VSCode after a timeout duration or after a count of stack analyses runs.

### Task List:
- [ ] Implement logic for having timeout and counter based crowdsourcing in VSCode plugin
- [ ] Trigger desired view based on timeout/counter based logic
- [x] Integration of IDE with stack-report portal UI for user-intent
- [x]  Launch user-intent view on we successfully do STACK-ANALYSIS POST call

**Comment by invincibleJai** [comment]
Have not done the tasks about implementing timeout logic for user-intent from VSCode as we have discussed this logic shouldn't be handled in client side. For now am showing user-intent screen once user triggers STACK-ANALYSIS POST call and polling for stack report is handled in web portal

CC @samuzzal-choudhury @krishnapaparaju
