### ISSUE TITLE
Implement the OSIO stack report as per revamped UX

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#1277]
### User Story:
As an OSIO Developer I will be able view more detailed stack report so that I can get lot more clarity so that I can get lot more clarity

### Description:
As a fabric8-analytics developer, I would like to implement the stack report on openshift.io based on the revamped UX (as per ~~https://redhat.invisionapp.com/share/JUEBSI892#/screens/262435891~~
https://redhat.invisionapp.com/share/6TF4C40KF#/screens/270947409) so that the OSIO users get a more intuitive UI to look at the analytics data and recommendations.

### Acceptance Criteria:
An openshift.io user views her/his stack report as per the wireframe provided by ~~https://redhat.invisionapp.com/share/JUEBSI892#/screens/262435891~~
https://redhat.invisionapp.com/share/6TF4C40KF#/screens/270947409.
Now user can not only view details in trivial way but also sees graphical and more attractive way.

### Work items:
- [x] Understanding the Existing code
    - [x] Identifying different components
    - [x] Understanding the services it is having
- [x] Create a new starter branch
- [x] Create new components
	- [x] Create Stack report component
	- [x] Create User components with suggested alternatives
	- [x] Create Additional components suggested by analytics
- [ ] Integrating complete UI.

### UX enhancements
- [ ] This iteration is mostly on the improvement on the information flow. First iteration enhancement based on the comments from PM and the team. Some comments below.
   - [ ] Tabs showing "file1", "file2" etc is not intuitive it looks as if it applies only to Summary section not to entire view.
   - [ ] Licenses Card need to reworked based on what we have in current Stack report in OSIO.
   - [ ] Security Issues Card should represent Critical issues in better way if it has higher CVEs
   - [ ] "Components with suggested alternatives" is confusing for user as we are listing all components here and alternate components needs a click to be shown and then only user can see action associated with it i.e "Add as workitem".
    (Here Alternate components / reasoning / associated action should be prominent to user)
   - [ ] Chart showing "GitHub Statistics" doesn't add much value
   - [ ] we have some label/wording correction.

**Comment by samuzzal-choudhury** [comment]
@sanketpathak how far are we with the implementation?

**Comment by sanketpathak** [comment]
@samuzzal-choudhury  one and half component are done

**Comment by msrb** [comment]
I see this section called "Additional components suggested by analytics" in the new UI. And I have to say it's a bit confusing. Are we really suggesting those companion packages? User is not really missing any packages so suggesting that he/she should add some, without any explanation why, feels kinda weird. 

I wouldn't expect people to just go and add the companion packages to their stacks. Because that simply wouldn't be a reasonable thing to do. Knowing what other packages are people with similar stacks using is an interesting information, but right now it's entirely up to developers to actually translate the names of the suggested packages to some concrete feature that they could implement, if they decide to add them to their stacks. If they don't solve this puzzle themselves, then there is no reason to add those companion packages.

With all that said, I think we don't want to "suggest" those companion packages (at least not at this point when we can't answer the ultimate "why should I add such package?" question. I'd suggest that we actually explicitly say that those are open-source packages that are commonly used in similar projects/stacks. That way developers won't be confused about why we are trying to suggest those packages to them, and they can either stop for a second and think what those other projects are doing when they need those extra packages (try to solve the puzzle), or they can just treat the section as another interesting information about their stack and ignore it (not a bad thing).

And if we want to help them to solve the puzzle, we could try to provide more information, like for example short description for each companion package.

WDYT? Should we try to come up with a different name for the section?

cc @miteshvp @samuzzal-choudhury @krishnapaparaju

**Comment by miteshvp** [comment]
@msrb - Good points. We did discuss this already and we will be re-wording the word suggestions to more like based on our insights. Also, we are currently showing as a tooltip about why this companion package is recommended. We provide the number of stacks that use this package in addition to user stack as a reasoning. Hope it helps.

**Comment by msrb** [comment]
@miteshvp yeah, I am just watching the BJN recording from yesterday. I am glad more people see this similarly :)

👍

**Comment by samuzzal-choudhury** [comment]
Some Feedbacks here: https://github.com/openshiftio/openshift.io/issues/1552.

**Comment by arunkumars08** [comment]
Closing this as it is being tracked here - https://github.com/openshiftio/openshift.io/issues/1773
