### ISSUE TITLE
Crowd Sourcing: Create a job to read tags from graph.

### ISSUE THREAD

**Issue by SaketJNU** [openshiftio/openshift.io#1283]
### Description: 
As the package-tagging task is crowd-sourced, end-user (developer) will suggest few tags for an unknown package, which will be saved in a graph. In next, we need to read those tags so that we can perform further tags cleaning, verification and make them available to PGM. For this, we can create a new job which will be execute all these tasks periodically. 
### Acceptance Criteria:
Tags shown by gremlin-query in web-browser and from reading through developed system should be same.
### Task:
- [x] Identify the graph-structure and it's constraints.
- [x] Create a dummy data and store it into the graph.
- [x] Create a job to read tags from graph
- [x] Write Unit test
~~- [ ] Write Integration test~~

**Comment by miteshvp** [comment]
@SaketJNU - I have already published one package with multiple tags and given the URL which will help you with what data is returned in the json. cc @sivaavkd

**Comment by GeorgeActon** [comment]
@SaketJNU please put an email stints in this today.

It looks to me like 5points total and you have alr day completed 3of 5 tasks.

**Comment by SaketJNU** [comment]
Opened the PR for unit-test:: https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/216

**Comment by jpopelka** [comment]
The job along with unit tests is https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/211

**Comment by jpopelka** [comment]
The last bullet point on Saket's list for this task is to write an integration/E2E test.

However the job as it is (see previous comment) modifies properties of **all** packages of specified ecosystem, which is definitely not what we want to do in tests.
I don't see a way how to test the job on just one package, so for now I'd leave implementing a e2e test for this out. We can do it later if we change the job to be able to accept only specific EPV, but I don't think it's a priority.

**Comment by miteshvp** [comment]
@jpopelka - ack. Thanks.
