### ISSUE TITLE
Dev Studio integration with 3scale registration portal

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#1284]
## User Story:
As a Devstudio IDE user, I will be able to call API's as per limits so that I can get better security.

## Description:
Currently, no API management is being done on the endpoints used in the Devstudio IDE to make fabric8-analytics available. This renders . limited scalability and unmanaged traffic control.
This implementation will help in traffic management by inspecting incoming calls for valid credentials and access rights hence providing rate limiting.

## Acceptance Criteria:

- User will be able to call API's only as per the rate limits.

- Beyond the rate limit, user will not be able to make API call and will get an error message in return.

## Task List:

- [x]  Make 3scale available on staging.

- [x] Create a job to register the user to 3scale in the backend.

- [x] Replace the current endpoints with 3scale endpoints.

PR - https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/99

**Comment by GeetikaBatra** [comment]
This is completed, we can close this one as well.

**Comment by qodfathr** [comment]
Who owns closing this? @samuzzal-choudhury, is it you?

**Comment by GeetikaBatra** [comment]
Closing this user story.
