### ISSUE TITLE
VSCode integration with 3scale registration portal

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#1285]
### User Story: 
As a VSCode IDE user I will be able to consume APIs with rate limits so that i can achieve better security and control around APIs

### Description:
Once extension user authenticates through openshift.io implicitly registers her/him to 3scale gateway. In process of registration we need to consume services of 3Scale portal.
The user should be able to invoke stack analyses on VSCode and check the stack report through the UI (APIs would be protected via 3Scale).

### Acceptance Criteria:
Authenticating a user through openshift.io implicitly registers her/him to 3scale gateway. The user should be able to invoke stack analyses on VSCode and check the stack report through the UI.

### Task List:
- [x] Make service call to intermediate 3scale gateway api with access token.
- [x] Persist received routes, user key in IDEs context
- [x] Utilize routes to make call to stack-analysis via 3scale
- [x] Utilize routes to make call to component-analysis via 3scale (as component-analysis is consumed via LSP which is common for RH-CHE, VSCode, DevStudio)

**Comment by invincibleJai** [comment]
Associated PRs
- https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/46

**Comment by invincibleJai** [comment]
Integration with VSCode is done pointing to self hosted gateway at Dev cluster.
Yet to handle the Changes needed to LSP level as it will be common piece which needs to be called via 3scale layer as well as direct API calls

**Comment by qodfathr** [comment]
cc: @bob-davis
