### ISSUE TITLE
[8] Updated Crowsourcing engine with Packages that PGM needs tag for.

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#1286]
## User Story:
Upon training, PGM will be able to update the crowd-sourcing engine with un-tagged packages.

## Description:
Every time PGM is trained, it recognizes the packages with missing tags. These packages need to be listed for crowd-sourcing. Once the tags are verified, they are stored in s3, and can be consumed by PGM for retraining.

## Acceptance Criteria
Un-tagged packages are reflected onto the crowd-sourcing engine.

## Task List:
- [x] Add Packages with no tags to the Crow sourcing DB.
- [x] Pick Top 4 most relevant tags for each package.
- [x] PGM training with the new tags.
- [x] Push the new model to production

**Comment by miteshvp** [comment]
I guess PR's are created. Closing this issue now.
