### ISSUE TITLE
Identification of sub-ecosystems for Maven Ecosystem

### ISSUE THREAD

**Issue by abs51295** [openshiftio/openshift.io#1291]
#### User Story

As an OSIO developer, I will be able to get better outlier recommendations for Maven ecosystem so that I can refine my chosen Maven stack.

#### Description

Since maven ecosystem is huge, we need to group the eco-system into sub-ecosystems so that we can easily identify the anchor packages for each sub-ecosystem.

#### Acceptance Criteria

* Given a sub-ecosystem, the system should be able to list all the packages belonging to that sub-ecosystem.

#### Task list

- [x] Setting up dev cluster.
- [x] Gathering package data from s3 bucket.
- [x] Grouping packages according to sub-ecosystem and writing data to s3 bucket.
- [x] Define metrics to identify significant sub-ecosystems which can help in determining anchor packages.

**Comment by abs51295** [comment]
Group ids with &ge; 200 artifacts were identified as significant sub-ecosystems for Maven.
