### ISSUE TITLE
Identification of statistical metric(s) to determine anchor packages for Maven ecosystem

### ISSUE THREAD

**Issue by abs51295** [openshiftio/openshift.io#1292]
#### User Story

As an OSIO developer, I will be able to get better outlier recommendations for Maven ecosystem so that I can refine my chosen Maven stack.

#### Description

After the identification of sub-ecosystems ( #1291 ) we need to determine the set of metrics with which to identify anchor packages.

#### Acceptance Criteria

* System should be able to provide a list of all anchor packages for Maven ecosystem.

#### Task list

- [x] Identify a set of statistical metric(s).
- [x] Test if the identified statistical metric(s) are generalized enough to work for every identified subgroup.
- [x] If the above task fails, then go back to task 1 and repeat the process.

**Comment by miteshvp** [comment]
@abs51295  - you can assign yourself when you actually start working on it. Till then no assignment

**Comment by abs51295** [comment]
@miteshvp I think the problem was trivially solved since we decided to move with mvn repository's download statistics. Assigning it to me and taking this is in current sprint goals.

**Comment by abs51295** [comment]
Top 30% packages for identified sub-ecosystems [ #1291 ] were chosen as anchor packages. Artifact usages from [mvnrepository](http://www.mvnrepository.com/) were taken as the primary metric to identify top 30% packages for the sub-ecosystems.
