### ISSUE TITLE
Data collection for node ecosystem from different data sources for anchor package determination

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#1293]
#### User Story
As an OSIO developer, I will be able to get better outlier package recommendation for node ecosystem so that I can improve my stack selection.

#### Description
In order to determine anchor package for node ecosystem we need statistical data (i.e download count, fork count, stars count, watchers count) for each node package. This user story aims to first identify the vectors, then identify data sources for collecting the vectors then collect data from the identified data sources.
#### Acceptance Criteria

- The application should be able to prevent the anchor package from being an outlier and suggest alternate package within the ecosystem of anchor package.

#### Task list

- [x] Setting up dev cluster
- [x] Identification of vectors and its corresponding data sources.
- [x] Collection of data from identified sources.
- [x] Cleaning of the collected data.
- [x] Preparing an intermediate data set for further processing.

**Comment by sunilk747** [comment]
The vectors identified are `dependents`, `dependencies`, `star_gazers` count and `subscribers` count  and the corresponding data sources are `npmjs` and `github`.

**Comment by sunilk747** [comment]
The final data set obtained can be found [here](https://drive.google.com/open?id=1dLvhDRInIK7ierHWMx3cUIkOzjOA86-X).
