### ISSUE TITLE
[3] CrowdSourcing Schema

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#1295]
### Description
In order to support crowd sourcing through our analytics platform, we require the necessary back-ends schema to be created.

#### Acceptance Criteria 
In order to enable end-users to contribute towards tagging through IDE or OSIO platform, there has to be a stable and robust back-end schema created.

##### Task List
- [x] Identify database to be used
- [x] Create necessary schema to support tagging
- [x] Get initial data dump
- [x] Create necessary query for online support
- [x] Create necessary query for offline support

**Comment by miteshvp** [comment]
Discussed whether to use Postgres or Graph for this use-case.
Graph was selected as we can use all the existing nodes in graph plus with few additional properties at each node level can also help with our online transactions.

**Comment by miteshvp** [comment]
Schema PR created - https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/58

**Comment by miteshvp** [comment]
**Query Section**
_**Online Query**_
1. Get next untagged component
2. Store the tags 

**_Offline PGM Query_**
1. Store all packages with no tags

**_Offline Verification_** 
1. Pick all the packages which have been tagged more than once
2. Store processed tags for the packages

**Comment by miteshvp** [comment]
Queries completed and can be found as part of [presentation](https://docs.google.com/a/redhat.com/presentation/d/1dA3f8U_5jf2Y0j9g5JUn3_0G1eyyUX1yOHXvre0HlHU/edit?usp=sharing)

**Comment by miteshvp** [comment]
Initial data dump created on Stage Environment
