### ISSUE TITLE
Identification of statistical vector(s) to determine anchor packages for node ecosystem

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#1297]
#### Description

This user story aims to enable the fabric8-analytics developer to identify the correct statistical vectors for identification of anchor packages in order to improve the outlier package recommendation by PGM.

#### Acceptance Criteria

Have a set of statistical metric(s) for determination of anchor packages.

#### Task List

- [x] Identify a set of statistical metric(s).
- [x] Test if the identified statistical metric(s) are correctly determining anchor packages or not.
- [x] Repeat the above two steps for other statistical metric(s).

**Comment by miteshvp** [comment]
@sunilk747 - you can assign yourself when you actually start working on it. Till then no assignment

**Comment by sunilk747** [comment]
refer #1293
