### ISSUE TITLE
PGM Scoring load tests

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#1306]
##### Description
In order to support our SLAs for stack-analyses, PGM scoring takes majority of the time in providing recommendations. This exercise of load test will help us arrive at the numbers that current PGM scoring service can handle.

##### Task List
- [ ] Run PGM load tests against Prod service
- [ ] Identify the response times for one stack analysis service under load
- [ ] Identify how many concurrent requests can be handled in order to meet our SLAs

**Comment by tisnik** [comment]
It is subtask for the https://github.com/openshiftio/openshift.io/issues/1144 EPIC

**Comment by miteshvp** [comment]
Closing
