### ISSUE TITLE
Crowd Sourcing: Implement verification logic

### ISSUE THREAD

**Issue by SaketJNU** [openshiftio/openshift.io#1311]
### User Story: 
As an **OSIO** developer, i will be able to reduce the number of unknown packages in stack-analysis report so that i will get better recommendations for alternate and companion packages.

### Description:
As the tags suggested by end-users of osio, stored in graph may be inaccurate. We need to perform data cleansing and verification for these tags. These verified tags (in the required format  ) will be used for next level of PGM training.

### Acceptance Criteria:
Cleaned Tags in required format should be available in S3 bucket for PGM.

### Task:
- [x] Filter out punctuation from tags
- [ ] Filter out stop-words from tags
- [ ] Perform stemming on tags
- [x] Implement a verification logic on tags
- [x] Create tag list in the proper format as per PGM requirement
- [x] Push the tag list in S3 bucket for PGM

**Comment by SaketJNU** [comment]
Opened PRs
https://github.com/fabric8-analytics/fabric8-analytics-common/pull/371
https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/211
https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/445

**Comment by miteshvp** [comment]
Code is deployed on Staging. Marking it as closed

**Comment by miteshvp** [comment]
Further improvements around stop-words and stemming can be taken up incrementally.
