### ISSUE TITLE
[8] Testing and Evalution of PGM results.

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#1312]
## User Story:
The PGM engine will be able to test the re-trained model so that it can evaluate the accuracy of the new model.

## Description:
Currently, there is no testing and evaluation module for the trained model. Which means that we have no way of automatically determining how good/bad or improved the model is after training. With testing in place, we will be able to measure the accuracy and validate the changes made.

## Acceptance Criteria:
Report/Log the evaluation metric whenever teh PGM model is trained.

## Task List:
- [x] Determine the Test Data set.
- [x] Determine the best possible output/recommendation for the test data.
- [x] Determine the evaluation metric.(https://github.com/openshiftio/openshift.io/issues/639)
- [x] Evaluate the expected recommendation with the PGM generated recommendations.
- [x] Report the evaluation metric.

**Comment by sara-02** [comment]
Covered by https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/134
The `EMR` job for maven test was `j-3TB0ZM29BKA8M`
The result can be found at `S3` `dev-stack-analysis-clean-data/maven/github/data_uranus_test/evaluation_results/01da3de6-dc53-11e7-8409-0242ac110002.json`

**Comment by sara-02** [comment]
@miteshvp I think we are good to close this issue.
