### ISSUE TITLE
Further merge the Launcher and OSIO project creation wizard

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#1317]
## Goal
Further merge fabric8 launcher and OSIO wizard so they share a code base and the user experience is fluid from launcher to OSIO.

## Description
We have two separate codebases between Launcher and project creation wizard in OSIO. This came from historical reasons while Launcher needed to be released while OSIO was not ready. The goal of the epic is mainly to reduce the technical debt between the two components and allow to use a single codebase.

The user experience will remain consistent, but Launcher, would allow to display the specific pages that are used and needed inside of OSIO

Launcher (on redhat.developers.com/launch) will allow to point the user to OSIO, so that it will open OSIO with the create project wizard displayed in OSIO 

## Identified steps and items to reduce the technical debt 
**Moving component to ngx-forge:**
- [x] Add component to ngx-forge #1186 
- [x] Create shareable code for Forge wizard between fabric8-ui and launchpad-frontened #1112
- [ ] Improve summary screen #1136 
- [x] Finish wizard flow with default values #1136 

**Merge Tasks:**
- [x] Merge launchpad-backend with fabric8-backend https://github.com/openshiftio/appdev-planning/issues/69
- [x] Refactor Mission Control for re-use https://github.com/openshiftio/appdev-planning/issues/66
- [x] Refactor the openshift-io Forge add-on to reuse services in the fabric8-launcher backend #1499

**Bugs:**
- [x] s/organisation/organization in quickstart wizard (and elsewhere, if relevant) #1322 
- [ ] Overlapping of text in "Summary" when importing existing projects #1175
- [ ] Cropped information in "Application wizard" on Summary step #1171 
- [ ] After quickstart project creation new codebase is not visible in the dashboard #1252 

**Nice to have improvements:**
- [x] Finish wizard flow with default values #1113

## User Experience
We need to better align the create project wizard from OSIO with the flow in Launcher. UXD will need to work on how we can make the wizard consistent between the two platform. 

- [ ] Wireframe: Add missions to the wizard https://github.com/fabric8-ui/fabric8-ux/issues/697
- [ ] RESEARCH: Write test plan and script for merged wizard https://github.com/fabric8-ui/fabric8-ux/issues/736
- [x] VISUALS: Wizard summary screen & information https://github.com/fabric8-ui/fabric8-ux/issues/710

## Parent Scenario
#2083

**Comment by joshuawilson** [comment]
cc @corinnekrych @edewit @krishnapaparaju @gastaldi

**Comment by gastaldi** [comment]
I created https://github.com/openshiftio/appdev-planning/issues/69 and we (cc @quintesse) are working on https://github.com/openshiftio/appdev-planning/issues/66

**Comment by adisakala** [comment]
CC @arunkumars08

**Comment by gastaldi** [comment]
@slemeur can you add https://github.com/openshiftio/openshift.io/issues/1499 as a new merge task checkbox? That is the only missing task extracted from https://github.com/openshiftio/appdev-planning/issues/66

**Comment by slemeur** [comment]
Done. Thanks @gastaldi

**Comment by qodfathr** [comment]
It looks like the checkboxes are out-of-date relative to the child issues. Can someone update, please?

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2059
