### ISSUE TITLE
[EPIC] Leverage Chefile in fabric8 boosters

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#1318]
## Goal
Anyone who is using Launcher (from standalone or from its integration within OSIO) will be able to get a developer workspace in Che fully ready and configured to work on the generated project (boosters).

## Description
When a user is using Launcher, he is selecting a booster which is then uploaded on a git repository. We want to provide the associated Chefile with the booster so that it provides a ready-to-use definition of a developer workspace in Che.

The Chefile will provide the information about the workspace’s runtime that is needed, as well as all the information that are needed to build, run and debug on the project.

Note: This Chefile will work only with Che installed on kubernetes/openshift. 

## Subtasks
Along with the work we are doing on upstream Che : https://github.com/eclipse/che/issues/4362

- [ ] Handle Chefile for different infrastructure implementation
- [ ] Provide Chefile for all boosters provided with fabric-8 Launcher
- [ ] Add instructions to start developer workspace in Che, in the readme.md of the booster
- [ ] Add instructions to start developer workspace in Che, in the readme.md of the generated source code from fabric8 launcher.
- [ ] Rely on Chefile for creating the developer workspaces on OSIO
- [ ] Che is able to import a workspace from a Chefile

**Comment by gastaldi** [comment]
I created https://github.com/fabric8-launcher/launcher-planning/issues/94 in the launcher backlog
