### ISSUE TITLE
Ability to provide an analytic driven project dependency editor into Launcher

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#1319]
## Goal
Provide complete specification and design to add the ability to include an analytics-driven project dependency editor into Launcher. 

## Description
Launcher allows to generate source code for applications which are deploy-able onto OSO. Those are called the boosters. We would like to allow the developer to configure the dependencies which are included inside of the boosters. This means, that the boosters will became extensible. 

Our goal is to generate a complete application which runs out of the box. We will allow the developer to: 
- Scaffold a project template,
- Define the dependencies to be integrated,
- Generate the POM.XML,
- Generate the definition of the developer workspace stack (for Che)
- Generate a `readme.adoc` with instruction to get started (import in Che, JDBS, IntelliJ)

To generate this complete application, we will guide the developer into a flow, where at the end - he will get the project source code generated for him which used directly to start a project on OpenShift, OSIO and Che.

We will leverage analytics in order to better guide the developer in the choice of the project dependencies. 

We will build a form based editor which will allow that. This editor would be designed in a way which will allow the integration into Launcher and in Che.

There are two main use cases:
1- For bootstrapping projects: Launcher will add the ability to customize the booster templates using analytics-based dependency recommendations. 
2- For existing projects: a dependency editor will make suggestions based on developer’s need and existing project dependencies. (mainly in Che)

## The flow requirements
The UI of the flow allows an integration inside of Launcher and inside of Che 

The flow provides a set of steps:
- Choose Application services (dependencies)
- List of categories
- List of packages (or add-ons)

It is possible to get details about the packages and show information, such as github stars, CVEs, versions.

At any point of time, the developer will be able to hit the button “generate” and get jump to the next step of the flow

Depending on the various dependencies selected, analytic will provide recommendations. User will have the ability to accept / decline the recommendation.

At any point in time, the user will have the ability to see a “summary” of the application and the dependencies selected.

## Sub-Tasks

- [ ]  Identifiy the list of categories which would allow a first classification of the dependencies
- [ ]  List all the different dependencies that we want to have listed in the wizard 
- [ ]  Define the UI Flow in a way that it can be added in Launcher and as a dedicated editor in Che

**Comment by joshuawilson** [comment]
cc @krishnapaparaju @arunkumars08

**Comment by miteshvp** [comment]
Already covered by Getting Started and Dependency Editor workflow. Closing
