### ISSUE TITLE
Analytics flow to create his/her own application stack

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1323]
#### User Story:

As an OSIO user, I will be able to drag and drop boxes (containers) and connect them in case they are required. I will also be able to enter details about ecosystem, intention and framework ... in each of the boxes so that I can get custom dependencies related to the details.

#### Description:

User drags and drops various boxes (containers) and adds some information on each of the boxes which takes details like ecosystem, framework ... which is then used by the analytics to generate necessary dependencies for the combination.
User can then link each of the boxes by arrows if required that shows the link between each containers.

#### Acceptance Criteria:

User should be able to drag and drop various boxes (containers) and add some information on each of the boxes which takes details like inputs regarding ecosystem and other application level information and should see relevant dependencies which he can later on use for his application.

#### Tasks:

- [x] User express the intent to indicate the kind of application 
- [x] User has option to add / delete to the generated project dependencies
- [x] Drag and drop shapes functionality for the application
- [x] Link various shapes
- [x] Open modal on click of every shape
- [x] Get input details from user

**Comment by arunkumars08** [comment]
This user story is mainly a POC around how this can be achieved.

**Comment by slemeur** [comment]
cross - linking to #1319

**Comment by arunkumars08** [comment]
Closing this as the tasks in this user story is complete for the POC
