### ISSUE TITLE
[8] Linting the UI

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1351]
### Description
As a developer of the system, I want the code to be linted when I compile and build it.

### Acceptance
 - [x] Update the linter rules for TS and Angular #1352
 - [x] Fix linting issues TS and Angular #1353
 - [x] Activate the linter on build, stopping the build if it fails #1354

**Comment by mindreeper2420** [comment]
@joshuawilson I played around with TSLint a bit here: https://github.com/mindreeper2420/fabric8-ui/tree/enviro-linting. It required updates to the packages to fix known bugs, as well as issues with the config file.

**Comment by joshuawilson** [comment]
We now have TS lint rule on and running.
