### ISSUE TITLE
[8] Expose workers bookkeeping data via API

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1404]
# User Story

We want to build a bookkeeping API for analyses of ecosystems and their packages so that we can know the current state of packages ingestion into the system.

# Description

We schedule analyses of components in any ecosystem using Jobs API at the moment. Once a job has been scheduled, we have to check logs, S3, Kibana etc. to know what is happening behind the scenes. Was there any failure? How many packages got ingested so far? How many were scheduled and how many failed? As a fabric8-analytics developer, I want to be able easily determine which tasks succeeded and which failed. Knowing which tasks failed, without need to query Kibana, will allow me to more easily spot/identify issues and bugs in the system.

Note: We already store this data in RDS, but currently there is no API that one could use to get the data.

We also want to retrieve an audit log against a component and its versions, so we know what all has happened in the system so far for a particular package.

# Acceptance criteria

- [x] API exposing summary of packages ingested by ecosystem -- total scheduled, success count, failure count summary
- [x] API exposing audit log of a package version -- workers which were executed, when, and outcome ( SUCCESS / FAILURE )
- [ ] basic filtering is implemented, e.g. it is possible to only show succeed / failed task for particular ecosystem, since <timestamp>, and allow for topN results
- [ ]  the code runs in production

# Tasks

- [x] Create API Design summary document
- [x] Create API exposing summary of packages ingested by ecosystem -- total scheduled, success count, failure count summary
- [x] Create API exposing audit log of a package version -- workers which were executed, when, and outcome ( SUCCESS / FAILURE )
- [ ] Create filters for succeed, failed, topN results
- [x] API Documentation via Swagger ?

**Comment by fridex** [comment]
[Sentry support](http://selinon.readthedocs.io/en/latest/trace.html#sentry-integration) can be helpful here (for debugging). There are two options how to implement this:

 * use selinon's tracing mechanism and waiting for [events](http://selinon.readthedocs.io/en/latest/selinon/doc/selinon.trace.html#module-selinon.trace) TASK_START, TASK_END, TASK_FAILURE, FLOW_START, etc.
 * use `store_error()` and `store()` on storage adapters to track failures and store them in RDS

**Comment by tuxdna** [comment]
## API description

```
BASE PATH api/v1/

GET bookkeeping/
GET bookkeeping/<ecosystem>/
GET bookkeeping/<ecosystem>/<package>/
GET bookkeeping/<ecosystem>/<package>/<version>/
```

All above paths will have filter query parameters:

`?worker=w1&worker=w2...status=success&status=failure...`


For example, following request shall return NPM package details for just the privided version, and worker name

```
GET bookkeeping/npm/event-lite/0.1.1/?workers=InitPackageFlow
```

**Comment by msrb** [comment]
@tuxdna please push the latest changes to git so we can move this forward while you're on PTO. Thanks

**Comment by tuxdna** [comment]
This PR https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/218 was updated and reviewed, and is good to merge.

**Comment by GeorgeActon** [comment]
@tuxdna if this is complete please close it.
