### ISSUE TITLE
test for planning - ignore until complete

### ISSUE THREAD

**Issue by GeorgeActon** [openshiftio/openshift.io#1410]
Sprint Goal
Publish IDE extensions for OSIO analytics platform (VSCode, DevStudio)
RHOAR - Plan/design for Machine generated stacks covering user experience
Continue the Research of NPM tags to cover the entire ecosystem

Engineering work:
Continue the progress on developers using Dev. cluster and wrap up remaining TODOs.
Wrap up service related open items for getting a handle on various operational scenarios, service.
Technical Debt.

Publish IDE extensions for OSIO analytics platform (VSCode, DevStudio)

- [ ]     Test and increase analytics coverage for Vertx, SpringBoot (#1287)
- [ ]     UX related enhancements for the stack report  (#1277) 
- [ ]     Identify,fix bottlenecks,publish out matrix involving resources been used with OSIO users that can be supported (#1144)

Wrap up Crowdsourcing (inside, outside stack report) for VSCode and DevStudio extensions
 - [ ] List and close all the marketplace related TODOs (icons, READMEs) for publishing IDE extensions

- [ ] End to end testing with 3Scale gateway deployed at OSIO 

Continue the research of NPM tags to cover the entire ecosystem (#1095)

- [ ]      (PRIORITY -1) Calculate the % of packages that could not tagged across NPM (#1095) 

Continue the progress on developers using Dev. cluster and wrap up remaining TODOs 

- [ ] Greenfield deployment of Fabric8 Analytics (#1062)

Wrap up service related open items for getting a handle on various operational scenarios, service (#1087)
- [ ] #1142 
- [ ]  #1330 
- [ ] #1085
- [ ] #1329 

RHOAR/Analytics Integration
- [ ]   Plan/design for Machine generated stacks covering user experience (https://github.com/openshiftio/openshift.io/issues/1323)

CVEs
- [ ] Figure out next steps for operationalising CVE mapping work to individual packages  (#1264)

Technical Debt
- [ ]         #688
- [ ]         #1196

---------------- Stretch ------------------------
- [ ] Wrap up significant % of ingestion for the GO ecosystem (#939)
- [ ] Setup end to end flow for users, NPM Recommendations would not be accurate by sprint 141
