### ISSUE TITLE
Deploy self hosted 3scale gateway 

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#1451]
#### User Story:

As a fabric8-analytics developer I would like to deploy self hosted 3scale gateway so that the IDE extensions can consume OSIO services via 3scale 

#### Description:
Self hosted 3scale gateway needs to be deployed on dev cluster( to start with) which would be using the 3Scale api management service (enterprise). fabric8-3scale-registration would be consuming it's services to register a user for 3scale and further will consume OSIO services via this gateway

#### Acceptance Criteria:
User should be able to register for 3scale via self hosted gateway.

#### Tasks:

- [x] Create `template.yaml` for openshift-apicast
- [x] Create a new repo in f8-analytics
- [x] Create CICO files needed
- [x] CI/CD with centos CI
- [x] Identify monitoring points needed for (dev/stage/prod)

---
> Dev Cluster
- [x] Deploy self hosted gateway on DevCluster
- [x] Integrate self hosted gateway with 3Scale api management service 
- [x] consume 3Scale api management service via fabric8-3scale-registration

---
> Staging
- [x] Deploy self hosted gateway on stage env
- [x] Integrate self hosted gateway with 3Scale api management service 
- [x] consume 3Scale api management service via fabric8-3scale-registration
- [x] Have FQDN for routes exposed

---
> Prod
- [x] Deploy self hosted gateway on prod env
- [x] Integrate self hosted gateway with 3Scale api management service 
- [x] consume 3Scale api management service via fabric8-3scale-registration
- [x] Have FQDN for routes exposed

**Comment by kbsingh** [comment]
lets also make sure we identify all the monitoring points needed, for dev/stage/prod for : our code, the 3scale gateway itself we host, and for the upstream 3scale end points. Once identified, we need to then work with the SD team to get it setup and the right reporting paths established.

**Comment by invincibleJai** [comment]
sure @kbsingh will worked towards it, thanks for inputs

**Comment by invincibleJai** [comment]
Associated PR's
1. https://github.com/fabric8-analytics/f8a-3scale-apicast-gateway/pull/2
2. https://github.com/fabric8-analytics/f8a-3scale-apicast-gateway/pull/1
3. https://github.com/fabric8-analytics/fabric8-analytics-common/pull/395
4. https://github.com/openshiftio/saas-analytics/pull/180
5. https://github.com/almighty/almighty-jobs/pull/423

**Comment by invincibleJai** [comment]
Have completed the flow with Dev Cluster , Testing flow with Stage is in progress. Not started with Prod.

**Comment by sunilk747** [comment]
@invincibleJai As I can see most of the task items in this user story are completed, can we close it now?

**Comment by invincibleJai** [comment]
@sunilk747 not sure if we can close it as i can see it under review from PM , @sivaavkd any views?
