### ISSUE TITLE
Items related to publishing VSCode extension to marketplace

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#1455]
#### User Story:

As a IDE(VSCode) user I would like to have OSIO-Auth/f8-analytics extension in marketplace so that the can use this extension to authorise IDEs to consume OSIO services for f8-analytics

#### Description:
OSIO-Auth extension needs to be in market place of VSCode, which would help any user to install and try out the extension. This story talks about the items needs to be achieved in order to publish extension in marketplace 

#### Acceptance Criteria:
All tasks needed to publish OSIO-Auth/f8-analytics extension in marketplace needs to be handled

#### Tasks:

- [x] Need to have readme's verified as this will be shown in marketplace for OSIO-AUTH extension
- [x] Need to have readme's verified as this will be shown in marketplace for f8-analytics extension 
- [x] Need to have the icon for OSIO-AUTH extension
- [x] Need to have the icon for f8-analytics extension
- [x] Need to finalise on Extension names for both (OSIO-AUTH extension and f8-analytics extension)
- [x] Need to automate the flow to publish the OSIO-AUTH extension to marketplace as redhat official
- [x] Need to automate the flow to publish the f8-analytics extension to marketplace as redhat official
- [x] Sharing extensions installable file (.vsix) with internal team
- [x] Integration test should check if `generate Stack-analysis` command is being triggered as expected 
- [x] Integration test should check if `generate Stack-analysis on workspace` command is being triggered as expected

**Comment by invincibleJai** [comment]
Associated PR's
1. https://github.com/fabric8-analytics/f8a-3scale-apicast-gateway/pull/2
2. https://github.com/fabric8-analytics/f8a-3scale-apicast-gateway/pull/1
3. https://github.com/fabric8-analytics/fabric8-analytics-common/pull/395
4. https://github.com/openshiftio/saas-analytics/pull/180
5. https://github.com/almighty/almighty-jobs/pull/423

**Comment by invincibleJai** [comment]
Tasks are completed here , one PR is yet to be reviewed and merged to have CI/CD(intranet) in place as we have for auth-ext

**Comment by invincibleJai** [comment]
it's completed @sivaavkd hence closing
