### ISSUE TITLE
API Implementation of analytics flow to create his/her own application stack

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#1462]
#### User Story:

As an OSIO user, I will be able to get relevant get relevant packages given English text or a tag as input and able to check if the dependencies are valid or not.

#### Description:

As a fabric8-analytics developer, I would like to create API endpoints to get relevant packages information given English text or tags as input and able to check if the dependencies are compatible to each other and valid if all the dependencies are valid then generate application stack.

#### Acceptance Criteria:

- A HTTP GET endpoint should exist which should return relevant packages information as the response.
- A HTTP POST endpoint should exist which should return relevant packages information as the response when an English sentence is given as input.
- A HTTP POST endpoint should exist which takes packages information as JSON input and should generate application stack or return invalid packages with information.

#### Tasks:

- [x] API endpoint to return packages information on the basis of user's intent to indicate the kind of application 
- [x] API endpoint to get relevant packages given a tag as input
- [x] API end-point for dependency check
