### ISSUE TITLE
Improve Analytics recommendations for quick starter applications

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#1471]
### Description
Current fabric8-analytics support for Vertx and Springboot takes into account [top github stacks](https://github.com/search?utf8=%E2%9C%93&q=filename%3Apom.xml+vertx+language%3Ajava+stars%3A%3E1&ref=simplesearch). We would also like to account for OSIO quick starter applications as part of training.

#### Acceptance Criteria
User sees improved recommendations for OSIO quick starter apps

##### Task List 
- [x] Retrain PGM with OSIO quick starts
- [x] Polish the tags for Packages in quick starts
- [x] Generate one real world example of Springboot
- [x] Performance Enhancements to the PGM (#1474 )
- [x] Test and increase analytics coverage for Vertx, SpringBoot (#1287)
- [x] Extend the effort to cover all OSIO quick-starts

**Comment by krishnapaparaju** [comment]
Please extend this effort to cover all the OSIO quick starts

**Comment by rootAvish** [comment]
This is resolved in the PGM retrain of https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/164.
