### ISSUE TITLE
PGM - Technical Debt / Housekeeping and improvement of end-user experience

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#1475]
### Description

This task involves adding Python3 support to the PGM and improving the end user experience in terms of recommendations that are shown for the quickstart applications in OSIO.

### Task List

- [x] Python 3 compatability
- [x] Upgrade to the most recent version of pomegranate
- [x] Integrate unit tests in the CI pipeline
- [x] Confirm whether INFO logging level is required at all places

**Comment by rootAvish** [comment]
PR for pomegranate upgrade: https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis-base/pull/3

PR for unit test integration: https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/137

PR for Python3 compatibility: https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/45

**Comment by rootAvish** [comment]
@sivaavkd Spills to 142.
