### ISSUE TITLE
Sprint 142 Planning: Fabric8 Analytics

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1524]
### Sprint Goals 
**Work towards publishing IDE extensions for OSIO analytics platform (VSCode, DevStudio)**
- [ ] UX related enhancements for the stack report  (#1277) 
- [ ] Identify performance bottlenecks and publish matrix for OSIO resource requirements based on load testing results (#1144)
- [ ] Deploy 3scale APICast gateway, Update IDE workflow to include 3scale user registration and test IDE workflow end-to-end with 3Scale gateway deployed. (https://github.com/openshiftio/openshift.io/issues/1451, https://github.com/openshiftio/openshift.io/issues/1285)
- [ ] List and close all the marketplace related TODOs (icons, READMEs) for publishing IDE extensions ( https://github.com/openshiftio/openshift.io/issues/1455 )

**Analytics recommendations for quick-starter app** 
- [ ] https://github.com/openshiftio/openshift.io/issues/1471

**Testing / Quality related** 
- [ ] https://github.com/openshiftio/openshift.io/issues/1521
- [ ] https://github.com/openshiftio/openshift.io/issues/1522
- [ ] https://github.com/openshiftio/openshift.io/issues/1523
- [ ] Run E2E tests against fabric8-analytics prod deployment: #1460 
  - this is about a subset of our existing E2E tests, UI is not covered by them

**Getting started experience** 
- [ ] Continue implementation of the UI code merge work., #1186
- [ ] Integrate the Che files, https://github.com/redhat-developer/rh-che/issues/402
- [ ] Based on feedback #1323, develop 2nd leg for POC for Analytics driven flow

**Figure out next steps for operationalising CVE mapping work to individual packages  (#1264)**
- [ ] #1613

### Bugs
- [ ] #1500 
- [ ] #1429
- [ ] #1450
- [ ] #1298
- [ ] #1147 
- [ ] #1490
- [ ] #1463

### Engineering work

**Work on high priority Technical Debt**
- [ ] Expose workers bookkeeping data: #1404
- [ ] Able to figure out and sync the delta between OLAP and OLTP stores: #1085

**Wrap up service related open items for getting a handle on various operational scenarios, service (#1087)**

##### AWS resources/infra improvements:
- [ ] Map AWS resources to staging/dev #1081

##### Tests:
- [ ] enable/improve E2E tests for ingestion components: #1329

##### Gradle:
- [ ] Implement Gradle support in Mercator: #689

**Comment by bmicklea** [comment]
CVEs continue to be a high priority.  Is #1471 actually complete?  It looks like all subtasks are done...

In fact it seems several of these are already closed. Perhaps a quick clean-up is needed?

@slemeur is the getting started experience items here part of the work you've been doing with the team?  From my perspective the OSIO stack reports, CVEs and a similar experience to start.spring.io (with added analytics) are high priorities. Please discuss the natural language experiment for package building with @slemeur before continuing work there.

**Comment by miteshvp** [comment]
@bmicklea - We actually increased the scope of #1471 to cover all OSIO quick-starts. Thanks for pointing out, I have added explicitly a line item for the same and we are working towards the same in this sprint (142).

**Comment by krishnapaparaju** [comment]
@bmicklea CVE work is going good, with Maven related CVEs will be in good condition by end of the train. Along with this, will working with SourceClear for improving CVEs for Maven.

**Comment by krishnapaparaju** [comment]
@bmicklea experiment related to natural language processing is only an experiment. I am working with @slemeur to define the user experience for analytics driven dependencies..

**Comment by bmicklea** [comment]
Thanks for the responses - is the list in this issue ordered by priority?

**Comment by krishnapaparaju** [comment]
@bmicklea Except items related to 'Engineering Work', all other work items carry same/high priority. While working towards these high priority items, comfortable to close on these by end of the current train.

**Comment by bmicklea** [comment]
@sivaavkd going forward perhaps each item referenced in the sprint plan should be proceeded by a checkbox. That way at the end of the sprint when we close the issue the team can "check" each of the items that was completed. This would provide a quick way for PM to understand what was completed and would be a good input into the sprint retrospective.

**Comment by sivaavkd** [comment]
@bmicklea - ack.  I think we have check boxes already in the sprint plan. But I think, we are not checking.  Will look into this and talk to team.
