### ISSUE TITLE
UI: Show environment resource usage

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1654]
The mock [1] has a resource usage section showing utilization of CPU, Memory and Network for each environment. This should be added as a component for the Deployments page.

[1] https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260764292

## Parent:
- #287

## Tasks:
- [x] Show resource usage
  - [x] Add utilization bars
    - [x] https://github.com/fabric8-ui/fabric8-ui/pull/2232
  - [x] Show warnings
    - [x] #1535
  - [x] Use real data
    - [x] #1370 

- Others
  - [x] #1412
  - [x] #1385 
  - [x] #1714
  - [x] #1779

**Comment by jiekang** [comment]
The initial merge included the base components for this.

https://github.com/fabric8-ui/fabric8-ui/pull/2232

**Comment by jiekang** [comment]
Closing as the work targeted for this tracking issue is now complete and functioning. Any subsequent issues are external to this tracking issue.
