### ISSUE TITLE
API: Provide API to support Deployments Page

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1655]
The mock [1] shows deployment details. This data needs to come from the backend API.

[1] https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260764292

## Parent:
- #287

## Tasks:
- [x] Provide per deployment status and resource utilization
  - [x] #1660
- [x] Provide pod scaling
  - [x] #1622
- [x] Provide per environment resource utilization
  - [x] #1661
- [x] Provide URLs for logs, openshift console and application
  - [x] #1662
- [x] Provide deployment deletion
  - [x] #1663

**Comment by jiekang** [comment]
The base work is in https://github.com/fabric8-services/fabric8-wit/pull/1798

**Comment by jiekang** [comment]
It would be much preferred if the pod status was in the format:
```
{
  "pods" : [
    ["Running", 1],
    ...
  ]
  "total" : 1
}
```

**Comment by stooke** [comment]
Can we make this an array of objects, instead of an array of heterogeneous arrays?

  "pods" : [
     { "running" : 1 },
    ...
  ]

Also, can we use lowercase here; the state strings should be localized by the UI.

**Comment by jiekang** [comment]
@stooke I'm going to see if I can accept that format without conversion in c3js but if not, we would end up converting this into an array of arrays on the UI side, though it's not a huge deal. It's really just a matter of which side loops over the object; since it will need to be done to calculate the total.

I would much prefer this kind of work done on the backend though; I already have concerns about the page's load time & resource utilization with 3 (4?) line charts and 2 donut charts per deployment and the static 2 (3?) utilization bars per environment.

**Comment by jiekang** [comment]
@stooke for lowercase, sure it can be done on the UI side. If we do all the work on the UI side, and the API is just a proxy for the Openshift/Kubernetes API. If we do all the work on the API side where the API is a converter for the Openshift/Kubernetes API so that the data can be used as is. A halfway conversion feels strange to me, why can't it do the rest?

For extra context:

The pod work is built off of the original in Openshift's web console:

https://github.com/openshift/origin-web-console/blob/b9034e8109e833d961d771a4ecbedbfeb4422919/app/scripts/directives/podDonut.js

If you do a quick read of the code, it recieves the pods data "raw" and does all the calculation on the UI side for the total (see `updatePodCount`) and the pod states (see `getPhase(pods)`). When I talked to Elliot at the beginning, I wanted to especially move the calculation of pod states onto the API end. If the API would be doing all this work, it made sense to me to also do the work for calculating the total and formatting the data as the UI wants.

**Comment by jiekang** [comment]
After further discussion with Simon, the pods data format will be a multi-dimensional string array as arrays with items of different type aren't so easy to do outside of javascript.

**Comment by jiekang** [comment]
Reopening as there are portions that this issue tracks that are still not complete, for example API to provide URLs  for logs, openshift console and application.

**Comment by jiekang** [comment]
A list of endpoints from the first iteration of API:

    /apps/environments/{envName}
    /apps/environments/{envName}/applications/{appName}/pods
    /apps/spaces/{spaceID}
    /apps/spaces/{spaceID}/environments
    /apps/spaces/{spaceID}/applications/{appName}
    /apps/spaces/{spaceID}/applications/{appName}/deployments/{deployName}
    /apps/spaces/{spaceID}/applications/{appName}/deployments/{deployName}/control
    /apps/spaces/{spaceID}/applications/{appName}/deployments/{deployName}/stats
    /apps/spaces/{spaceID}/applications/{appName}/deployments/{deployName}/statseries

**Comment by jiekang** [comment]
Reopening as there are portions that this issue tracks that are still not complete, for example API to provide URLs for logs, openshift console and application.

**Comment by ebaron** [comment]
With the deletion API merged, all of the specified API is now present.
