### ISSUE TITLE
UI: Show deployment details

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1658]
https://guides.github.com/features/mastering-markdown/The mock [1] has a deployment details section showing status of each deployment in the form of cards. More detailed information can be found by expanding the card [2].

[1] https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260764292
[2] https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260764295

## Parent:
- #287

## Tasks:
- [x] Show deployments as cards
  - [x] Show deployment status
    - [x] #1452
    - [x] #1659
    - [x] #2545 
  - [x] Show deployment version
  - [x] Show pod lifecycle donut chart
    - [x] #1369
    - [x] #1534
    - [x] #1622 
    - [x] #1653
    - [x] #1679
    - [x] #1713
    - [x] #1788
  - [x] Show resource usage charts
    - [x] #1366
    - [x] #1709
    - [x] #1711
    - [x] #1712
    - [x] #1750
    - [x] #1787
    - [x] #1878
    - [x] #1859
    - [x] #1893
    - [x] #2520
    - [x] #2521
    - [x] #2541
  - [x] Show alerts for pod quota issues
    - [x] #1659
  - [x] Allow user actions per deployment
    - [x] #1578 
    - [x] #2474
  - [x] Allow filtering and sorting deployments
    - [x] #1633 
  - [x] Use real data
    - [x] #1370 
- Others:
  - [x] #1372
  - [x] #1373
  - [x] #1374
  - [x] #1382
  - [x] #1395
  - [x] #1397 
  - [x] #1515
  - [x] #1516
  - [x] #1645
  - [x] #1710  
  - [x] #1749
  - [x] #1888
  - [x] #1907
  - [x] #1865 
  - [x] #2543

**Comment by jiekang** [comment]
The initial merge included the base components for this.

fabric8-ui/fabric8-ui#2232

**Comment by jiekang** [comment]
Status update:

Everything is complete except:

Status alerts for pod deployment failures
Links for logs, openshift console and application
Action for deleting application

**Comment by qodfathr** [comment]
#1865 was once referenced from here, but now is not. Is #1865 a task that needs to be completed for this? Thanks.

**Comment by jiekang** [comment]
@qodfathr I initially intended this issue to track tasks for the previous train. #1865 is a task that wasn't in the initial UX designs and was discussed in the last 2 weeks of the previous train; it was decided to be done in train/heather. I was inclined to recreate user stories to track tasks specifically for train/heather but wasn't sure if it would be worth it, versus continuing to use these ones.

In the meantime I've re-referenced #1865 here.

**Comment by qodfathr** [comment]
Thanks, @jiekang

**Comment by jiekang** [comment]
#1909 is now tracked under #1443. Removing from this issue.


Update on remaining work:

Provide ability to delete deployments : Waiting on API

Show alerts for deployment failures: Requires API, or internal calculation logic. Would be preferable to have websocket API as polling API isn't as great of a user experience.

Loading indicators

**Comment by jiekang** [comment]
This task was created to track the work for meeting the original UX design. Closing as completed. New issues will be opened to track work for meeting the additional changes in UX design.
