### ISSUE TITLE
Improve Companion Recommendation Reasoning

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#1674]
## User Story:
As an OSIO user I should see the confidence score along with the co-occurrence count for each companion recommendation so that I am aware of the reasoning behind the recommendation

## Description:
Currently, OSIO user sees by hovering over the companion recommendation the co-occurrence count(i.e number of times this companion has occurred along with the input stack). This value is calculated by searching the Github manifest list as a source of truth. The problem with current approach is that a raw number of frequency in a large set of GitHub manifest, does not convey the message clearly. The aim is to include a confidence score as a percentage of co-occurrence of input set + companion against only the input set which gives a better picture of how confident we are with the recommendation.

## Acceptance Criteria
Display the confidence score as a visible column along with every companion recommendation. The co-occurrence count can be shown by hovering.

## Task List
- [ ] Change in the Kronos post-recommendation filters to calculate and store both the confidence % and the co-occurrence count for companion recommendations.  
- [ ] Update at Worker-Recommendation API  level to parse the new keys sent by Kronos
- [ ] Update at Server level to reconstruct the message to be displayed for the companion reasoning.
- [ ] Changes in the UI to display the confidence score and the co-occurrence count

**Comment by sara-02** [comment]
@miteshvp  PTAL to add if I have missed any component that might get affected by this work.

**Comment by miteshvp** [comment]
@sara-02 PTAL at the MM comment

**Comment by sara-02** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/154

**Comment by sara-02** [comment]
@arunkumars08 What is the status on this? The work from the API side is complete now.

**Comment by arunkumars08** [comment]
@sara-02 It is already in prod. You can verify and close.

**Comment by arunkumars08** [comment]
@sara-02 The design will again change as a part of the revamp. Just a heads up.

**Comment by sara-02** [comment]
@arunkumars08 as long as the work flow is taken into account, we are good.
