### ISSUE TITLE
POC for Analytics driven flow

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#1688]
#### User Story:

As an OSIO user, I will be able to generate my own stack and also be able to select my custom dependencies related to the details.

#### Description:
Allowing the user to edit (add/remove) the project dependencies once he selected one of the boosters in the project creation wizard and providing stack report of the project he is building.
Showing recommendations on the dependencies user has selected.
Adding intent based dependency selector.

### Tasks:

- [x]  Add edit option in the Application wizard
- [x] Create Application component in the Modal
    - [x] Add a selection component
    - [x] Add a dependencies used component
    - [x] Add a recommendation component
    - [x] Add a security component
    - [x] Add a license component
    - [x] Add a metadatas component

- [x] Create Package component in the Modal
    - [x] Add search for packages with filters
    - [x] Displaying list of filtered dependencies
    - [x] Displaying categories grouping the dependencies

- [x] Generate manifest file with selected dependencies

### Follow up tasks
- [x]  Integrate an intent based dependency selector
