### ISSUE TITLE
Getting Started Experience: Launcher + OSIO Wizard

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1689]
### User Story: 
As a OSIO user I will be able to see the new flows of wizard (Launcher + OSIO). [Quick Start flow]

### Description:
Currently, in OSIO we don't have mission flow. With this addition, it helps us to merge the flow from Launcher (i.e the mission, tech stack flow and others).

### Acceptance Criteria:
OSIO user should be able to select mission, technology stacks and proceed with selecting pipelines and creating a starter application.

### Task List:
- [ ] - Link OSIO Forge front end with respective backend (Local setup) to test customisations.
- [ ] - Document the whole flow of Request, response mapping and steps for setting up end to end flow locally (It helps for future reference)
- [ ] - Create module for new wizard flow

---
> #### Select a Mission and Technology flow - https://github.com/openshiftio/openshift.io/issues/1720

---
> #### Select a Project' Environment flow - https://github.com/openshiftio/openshift.io/issues/1721

---
> #### Select a Pipeline flow
- [ ] - UI flow development as per UX.
- [ ] - API development
- [ ] - Integration of API and UI in case of customisation.

---
> #### Git Provider flow
- [ ] - UI flow development as per UX.
- [ ] - API development
- [ ] - Integration of API and UI in case of customisation.

---
> #### Summary flow
- [ ] - UI flow development as per UX.
- [ ] - API development
- [ ] - Integration of API and UI in case of customisation.

**Comment by arunkumars08** [comment]
Closing this as it is no longer relevant.
