### ISSUE TITLE
Enabling authentication via OSIO icon on menu bar in Devstudio.

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#1691]
## User Story:
As a Devstudio IDE user, I will be able to authorize using OSIO icon.

## Description:
Currently, the login page pops up if manifest file is clicked upon or stack analyses is called. This implementation will add a provision to connect to openshift.io using the icon on menu bar. This will create a better user experience.

## Acceptance Criteria:

- User will be able to log in using OSIO icon on menu bar.

## Task List:

- [x] - Find a way to access preferences, which will enable the lsp server when user authorizes OSIO.
- [x]  Integrates the plugin with 3scale

- [x] Removes the dependency from node js server

- [x] Makes server.js executable

- [x] Adds a command on toolbar to enable OSIO authentication.

- [x] Changes the control flow of token mechanism.

- [x]  Validate if both stack analyses and component analyses are running fine.

PR - https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/99

**Comment by GeetikaBatra** [comment]
This is completed. We can close this one.
