### ISSUE TITLE
Add a tab for Stack Analyses along with manifest files on Devstudio.

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#1692]
## User Story:
As a Devstudio IDE user, I will be to see stack analyses on a tab in manifest editor window.

## Description:
Currently, the stack analyses is called only by right clicking on a project. This implementation will add a tab named as ```Stack Analyses``` along with the manifest files. This will create a better user experience.

## Acceptance Criteria:

- User will be able to click on Stack Analyses  tab to see the report.

## Task List:

- [x] Get handy with eclipse core m2e plugin in order to add a tab.

- [x] Add a tab named stack analyses along with manifest files.

- [x] Connect browser to the tab.

- [x] Initiate Stack Analyses on this tab.

PR - https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/101

**Comment by GeetikaBatra** [comment]
This is covered by https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/110

**Comment by GeorgeActon** [comment]
@GeetikaBatra Is this completed?

**Comment by GeetikaBatra** [comment]
@GeorgeActon ,Yes.
