### ISSUE TITLE
Account for User Input stacks as part of recommendation training

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#1694]
## Description
Currently, when we train our recommendation engine, we only consider top Github stacks + OSIO quick starts as part of the training data set. We should also consider user input stacks as part of our training data set.

## Acceptance Criteria
As a user, I should get improved recommendations over time based on mine and other users input.

## Task List
- [x] Create the pipeline
- [x] Create new storage handler
- [x] Create new jobs endpoint to trigger this ingestion.
- [x] Append packages with no tags for crowd sourcing(should happen automatically while re-training)
- [x] Append user input stack as part of recommendation training

## Additional TODO:
 - [x] Use proper SQLalchemy instead of raw query
 - [ ] Add test cases for the Job
