### ISSUE TITLE
Add all the licenses that are unknown to license analysis platform

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#1695]
#### User Story
As an OSIO developer, I should get correct license recommendation for my selected stack which will help in my final stack selection.

#### Description
Currently all the licenses are not covered as part of the license analysis. This results in failure of license analysis for some of the selected stacks, because of which OSIO user doesn't get a final representative license for the selected stack. This user story aims to add all the unknown licenses to license tree which will improve the license recommendation.

#### Acceptance Criteria

- The OSIO user will be able to get a final representative license for the stack selected by the user at component level and stack level.

#### Task list

- [x] Find all the licenses that are unknown to platform.
- [x] Check compatibility of unknown licence with the existing licenses. 
- [x] Add unknown licenses to existing license tree.
- [x] Check whether it's giving correct license recommendation for stack selected by user.

**Comment by sunilk747** [comment]
These are the unknown licenses for vertx and springboot:
`BSD 2-clause`, 
`CDDL 1.0`, 
`CDDL 1.1`, 
`CC-BY 3.0`, 
`CDDL`, 
`POSTGRESQL`, 
`Commercial`, 
`CPAL 1.0`, 
`JSON`, 
`Atlassian 3.0`, 
`CC0 1.0`, 
`Apache 1.1`, 
`BOUNCYCASTLE`, 
`MPL 2.0`, 
`EDL 1.0`,  
`CPL 1.0`,   
`EDL`, 
`W3C`, 
`CDDL 2`

**Comment by sunilk747** [comment]
CDDL 1.0, CDDL 1.1 and CDDL 2 added.

**Comment by sunilk747** [comment]
MPL 2.0 added.

**Comment by sunilk747** [comment]
MPL 2.0 added.

**Comment by sunilk747** [comment]
BSD - Simplified added.

**Comment by krishnapaparaju** [comment]
Can we close this issue ?

**Comment by sunilk747** [comment]
@krishnapaparaju Yes. Closing this as all the unknown licenses are now added to the platform.
