### ISSUE TITLE
Write api test for production.

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#1697]
## User Story:
API test for production.

## Description:
Currently,there are no api test cases to test production. This implementation will add some tests for the same.

## Acceptance Criteria:

- CI/CD is able to run a set of tests for production.

## Task List:

- [ ] Figure out what tests should go in file for production.

- [ ] Test if they are working for all prod urls

- [ ] Coordinate with SD team to include the tests.

**Comment by msrb** [comment]
I think we already have some API tests in our test suite (?) cc @tisnik

**Comment by GeetikaBatra** [comment]
@msrb, This is taken care by @tisnik,  I guess. Closing this one.
