### ISSUE TITLE
Getting Started Experience - Select a Mission and Technology flow

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1720]
### Epic:
https://github.com/openshiftio/openshift.io/issues/1689

### User Story: 
As a OSIO user I will be able to select mission and technology in the quickstart flow so that I can see specific results.

### Description:
Currently, in OSIO we don't have mission and technology flow. With this addition, it helps us to merge the flow from Launcher (i.e the mission, tech stack flow and others) and have options to select mission, technology.

### Acceptance Criteria:
OSIO user should be able to select mission, technology stacks.
Depending on the selection of mission, technology should be updated for selection.

### Task List:
- [ ] - Understanding the flows, getting comfortable with customizations.
- [ ] - UI flow development as per UX.
- [ ] - API development
- [ ] - Integration of API and UI in case of customisation.

**Comment by arunkumars08** [comment]
Closing this as it is no longer relevant
