### ISSUE TITLE
Improve companion recommendations for entire Vert.x and SpringBoot ecosystem to support release of IDE extenstions

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#1727]
## User Story

As an OSIO or IDE extensions user, I should be able to get companion recommendations for any stack that contains packages from the SpringBoot or Vert.x ecosystem.

## Acceptance Criteria

IDE users should be able to get reasonable companion recommendations for the Vert.x(partial support) and SpringBoot ecosystems.

For a recommendation to be acceptable:

* The testing and evaluation results of the PGM should show a reasonable accuracy (>50%)
* The recommendations should make sense to the user, this covers:
    - The generated companion recommendation is from the same ecosystem
    - The recommendation, in certain cases should match the expectation of the user in accordance with the discussion we had around this with a user of the technology.
* We are aiming for a high accuracy for SpringBoot, Vert.x recommendations may not make sense in cases.

## Description

Previously, efforts had been made in the direction however the PGM had always been trained using a four tag limit. The objective here is to clean the data in a way that we're able to lift the limitation of each tag being mapped to just four intents and go up to a respectable number (in the 15-20 range). The reason why we think this'll work is because previously the limit was in place keeping in mind a much larger ecosystem where the size of the PGM tree would be way too large for it to be practical.
However, in case of a sub-ecosystem like Vert.x and SpringBoot (parts of the maven ecosystem) we would be able to go past this limit.

The other reason why this limit is in place is beacause the size of the CPD increases exponentially as the number of tags in each intent increases. However based on our experimental results the PGM code is able to handle tables about 2^17 rows in size.

## Task List

- [x] Check the gnosis intents for the most popular tags that are a part of the same
- [x] Clean the most popular tags as these are not a value add in case of vert.x and springboot
- [x] Tune the threshold parameter for intent co-occurence
- [x] Run the testing and evaluation script
- [x] Verify the result for the quickstarts manually
- [ ] Validate all the Vertx and Springboot Reference Stacks with experts
- [ ] Based on the validations/feedback modify the PGM training data set to get good recommendations
- [ ] ~~(Stretch) Extend the PGM to k-itemset tree if required~~
- [ ] ~~(Stretch) Explore alternate methods for approximation of marginals rather than exact inference(thereby reducing the size of the CPD).~~

**Comment by rootAvish** [comment]
@sivaavkd Please see this. I couldn't find the epic for the IDE extensions with the search for type/epic & stream/analytics, if there is one elsewhere can you please link it here?

**Comment by miteshvp** [comment]
@rootAvish - I've added two more task list items to this issue. I will be talking to experts to validate all our reference stacks for Vertx and Springboot

**Comment by miteshvp** [comment]
Sent an email to Hrishikesh, Burr and Kamesh to help us validate the stacks.

**Comment by miteshvp** [comment]
https://docs.google.com/document/d/1OG3PH6gyUeLRWG1FbAqhDu72tulTwR8kYJV_NsSFxgA/edit is where we are maintaining the comments from experts.

**Comment by sivaavkd** [comment]
Closing this since we are tracking the comments separately.  If there are any changes needed based on the comments, we will open separate issue(s).
