### ISSUE TITLE
Sprint 143 Planning: Fabric8 Analytics

### ISSUE THREAD

**Issue by sivaavkd** [openshiftio/openshift.io#1738]
### Sprint Goals 
**Publishing IDE extensions for OSIO analytics platform (VSCode, DevStudio)**
- [x]  <img width="31" alt="screen shot 2018-01-09 at 7 59 14 pm" src="https://user-images.githubusercontent.com/15967765/34725740-dcd64010-f577-11e7-9288-d2e6b61a18dc.png"> UX related enhancements for the stack report  (https://github.com/openshiftio/openshift.io/issues/1773) 

- [x] <img width="31" alt="screen shot 2018-01-09 at 7 59 14 pm" src="https://user-images.githubusercontent.com/15967765/34725740-dcd64010-f577-11e7-9288-d2e6b61a18dc.png"> Identify performance bottlenecks and publish matrix for OSIO resource requirements based on load testing results (#1144)
- [x] Deploy 3scale APICast gateway, Update IDE workflow to include 3scale user registration and test IDE workflow end-to-end with 3Scale gateway deployed - to PROD. (https://github.com/openshiftio/openshift.io/issues/1451, https://github.com/openshiftio/openshift.io/issues/1285)
- [ ] List and close all the marketplace related TODOs (icons, READMEs) for publishing IDE extensions ( https://github.com/openshiftio/openshift.io/issues/1455 )

**Analytics recommendations for Vert.x and SpringBoot and quick-starters** 
- [x] Recommendations for Vert.x and SpringBoot  (https://github.com/openshiftio/openshift.io/issues/1727)
- [x] Spikes to try out supporting Node ecosystem (#1736 and #1802 )

**Testing / Quality related** 
- [x] <img width="31" alt="screen shot 2018-01-09 at 7 59 14 pm" src="https://user-images.githubusercontent.com/15967765/34725740-dcd64010-f577-11e7-9288-d2e6b61a18dc.png"> UI Integration tests https://github.com/openshiftio/openshift.io/issues/1693
- [x] <img width="31" alt="screen shot 2018-01-09 at 7 59 14 pm" src="https://user-images.githubusercontent.com/15967765/34725740-dcd64010-f577-11e7-9288-d2e6b61a18dc.png"> enable/improve E2E tests for ingestion components: #1329

**Getting started experience** 
- [x] Based on feedback, develop 2nd leg for POC for Analytics driven flow(https://github.com/openshiftio/openshift.io/issues/1764)

**CVEs**

- [x]  <img width="31" alt="screen shot 2018-01-09 at 7 59 14 pm" src="https://user-images.githubusercontent.com/15967765/34725740-dcd64010-f577-11e7-9288-d2e6b61a18dc.png">  (#1264)

- [x] <img width="31" alt="screen shot 2018-01-09 at 7 59 14 pm" src="https://user-images.githubusercontent.com/15967765/34725740-dcd64010-f577-11e7-9288-d2e6b61a18dc.png"> #1767

**Improve license recommendation for end user**
- [ ] <img width="31" alt="screen shot 2018-01-09 at 7 59 14 pm" src="https://user-images.githubusercontent.com/15967765/34725740-dcd64010-f577-11e7-9288-d2e6b61a18dc.png"> #1761 
- [x] <img width="31" alt="screen shot 2018-01-09 at 7 59 14 pm" src="https://user-images.githubusercontent.com/15967765/34725740-dcd64010-f577-11e7-9288-d2e6b61a18dc.png"> #1695

### Bugs
- [x] #1429
- [x] #1147 
- [x] #1490
- [x] #1463

**Feedback Loop**
- [x] Add user input stack to PGM training. #1694 
- [x] Save user's feedback for the stack analysis report #1740 

### Stretch goals (POCs, pulled in from H train priorities)
- [x] Display Insights from Fabric8 analytics at Che IDEs UI as POC (https://github.com/openshiftio/openshift.io/issues/1768)
- [x] POC for CVE alerts on Pipeline view  (#1770) 

### Engineering work

**Work on high priority Technical Debt**
- [x] Expose workers bookkeeping data: #1404
- [x] Able to figure out and sync the delta between OLAP and OLTP stores: #1085 
- [x] Remove logging from PGM once it is tested on production: #1785

**Comment by krishnapaparaju** [comment]
@sunilk747 Please include the License related EPIC (next steps) as part of the sprint plan

**Comment by krishnapaparaju** [comment]
@miteshvp Please include PGM caching related work item

**Comment by krishnapaparaju** [comment]
@invincibleJai Please include work items related to quick POCs around (a) Insights at Che (b) Flagging CVEs, Stack level Licenses at build, pipelines screens. Goal is to iterate a quick POC and get it reviewed with PM team.

**Comment by krishnapaparaju** [comment]
@rootAvish @abs51295  Please include spikes around research around analytics: (a) based on Bayesian networks with Edward to have Bayesian networks run on deep neural networks (b) Plain deep neural networks

**Comment by krishnapaparaju** [comment]
@samuzzal-choudhury we wanna wrap up fixing performance bottlenecks by end of sprint # 143. Please change #1144 / create  a new issue and include as part of the sprint plan.

**Comment by krishnapaparaju** [comment]
@miteshvp Please include the issue covering remaining work items related to insights for VertX and SpringBoot ecosystems.

**Comment by krishnapaparaju** [comment]
@sivaavkd please remove #1521

**Comment by krishnapaparaju** [comment]
Please remove code merge related work until UX work is done for this activity

**Comment by krishnapaparaju** [comment]
@sivaavkd  From this sprint, please remove integrating into Che files as currently OSIO support Che version 5x and this Che files format is being planned for Che version 6x.

**Comment by bmicklea** [comment]
This is a very aggressive sprint - perhaps we should start listing priorities in the description here?  From my perspective the most important things are:
#1773 
#1144
#1264 
#1767 
#1761
#1695
#1693
#1329

**Comment by krishnapaparaju** [comment]
@bmicklea Ack. Doing well with these work items marked as priority. I have included an new icon to indicate priority and maybe would be good to review during spring demos..
