### ISSUE TITLE
Capture user feedback for the stack-analysis report.

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#1740]
## User Story:
As an OSIO user, the feedback I submit should be stored against each recommendation. 

## Description:
Once the user submits the feedback, we need to have a mechanism to save the feedback in RDS to be consumed by analytic.
The end-to-end flow depends on the new UX being implemented. This task focuses on having the back end flow ready to be integrated.
 
## Acceptance Criteria:
Have an endpoint that is called, when the feedback is submitted from the UI. The endpoint should store the feedback against each recommendation.

## Task List:
- [x] Determine the attributes that need to be captured.
- [x] Set up an RDS table for the feedback.
- [x] Set up API endpoint to collect and store feedback.
  
## Additional TODO:
 - [x] Use proper SQLalchemy relations
 - [x] Add test cases for the server
