### ISSUE TITLE
Determine a representative license for a github repository given by user

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#1761]
## Description
The task here is to determine a representative license for a github repository given by the user. The user will give repository url as an input and our license analysis platform should be able to determine a license the user can use by taking into consideration all the transitive and immediate dependencies for that repository.  The final representative license shouldn't be in conflict with licenses of transitive and immediate dependencies.
For more details on transitive dependency and immediate dependency refer this [blog.](https://medium.com/@vovabilonenko/licenses-of-npm-dependencies-bacaa00c8c65)

## Acceptance criteria
The user will get a final representative license with no conflicts for the input github repository.

## Task List
- [x] Adding support for unknown licenses #1695 .
- [x] Fetch dependencies and transitive dependencies for go project by parsing glide.lock or Gopkg.lock.
- [x] Fetch license information for dependencies from graph.
- [x] Perform License analysis for the repo using above information.
  
## Parent
#1766

**Comment by krishnapaparaju** [comment]
pushing this work to sprint 144.

**Comment by sivaavkd** [comment]
@sunilk747 - Can you help me understand the current status of this ?  are we targeting this for the current sprint ?

**Comment by sunilk747** [comment]
@sivaavkd I am currently not working on this user story and we are not targeting this in this sprint. I think it's better to put it backlogs.

**Comment by vasulakkaraju** [comment]
Currently to identify the dependencies and unknown dependencies for given go project we are parsing the glide.lock/gopkg.lock file.

**Comment by vasulakkaraju** [comment]
Here is the PR for the same https://github.com/fabric8-analytics/fabric8-analytics-server/pull/286

**Comment by vasulakkaraju** [comment]
closing this issue as the implementation is done in the PR https://github.com/fabric8-analytics/fabric8-analytics-server/pull/286
