### ISSUE TITLE
Fix identified stack analyses bottlenecks and publish resource requirements

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#1763]
## User Story
As a Fabric8-Analytics developer I would like to fix `/stack-analyses` performance bottlenecks so that subsequent load and performance testing can be done on the revised API endpoints and resource requirements can be published.

## Description
We have already identified the various performance bottlenecks in the existing `/stack-analyses` by running performance and load tests. In this sprint, we will have to take architectural decisions and code fixes to get rid of the bottlenecks

## Acceptance Criteria
Resource requirements are published to support XX requests per minute.

## Task List
- [x] Decouple SQS, celery and Selinon from the codebase and introduce new API backbone services.
- [x] Load testing without Kronos Caching.
- [x] Productize new analytics endpoint and related services.
- [x] Implement caching for Kronos scoring.
- [x] Load testing with Kronos Caching.
- [x] Load testing with 3-scale API rate limiting.
- [ ] Stretch: Introduce Mercator service to generate effective-poms.
- [ ] Stretch: Add new services for dev cluster deployments.

## Integration TODO
- Deploy fabric8 API Backbone service on Production.
- Deploy coreapi service endpoint `/analyse'.
- VSCode extension to generate of effective POM.
- Developer Studio: figure out the way to locate and send auto-generated effective POM.
- Integrate IDE extension/plugin with `analyse` endpoint.
- Integrate `analyze` with openshift.io Bayesian Jenkins plugin.
- Future: Phase out `/stack-analyses` endpoint.
- Future: Phase out bayesian-worker-api service.

**Comment by samuzzal-choudhury** [comment]
This work has been completed. The high performer /stack-analyses has been already made available on prod and the all the integration points now currently working.
