### ISSUE TITLE
POC for Dependency Editor flow

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#1764]
#### User Story:

As an OSIO user, I will be able to generate my own stack and also be able to select my custom dependencies related to the details.

#### Description:
Allowing the user to edit (add/remove) the project dependencies once he selected one of the boosters in the project creation wizard and providing stack report of the project he is building.
Showing recommendations on the dependencies user has selected.
Adding intent based dependency selector.

### Tasks:

- [x] The list of dependencies should not be empty when the user arrives in the dependency editor.
- [x] Remove added dependencies / current dependencies section from the summary.
- [x] Recommendation functionality comes in the Insights part.
- [x] Replace tags with categories.
- [x] List of packages should be relevant to application stack user selected.
- [x] Insights package width should be the same as application summary.
- [x] Change running/test packages indicators to gray color and few alignment issues.
- [x] Insight packages add button should be replaced by the accept/decline button.
- [x] Correct wordings and capitalizations.
- [x] Replace chatbot with detailed interaction inside the insights

**Comment by slemeur** [comment]
@ravsa Adding few feedbacks from comments in the current layout.
<img width="1580" alt="screen_shot_2018-01-11_at_10_39_59" src="https://user-images.githubusercontent.com/1636769/34823061-5d4fd376-f6c9-11e7-9e40-20ba1cbeb8e3.png">

There is another one which is quite important: we should try to use less space for each dependency. On the screen I attached, we are able to show only 4 dependencies, which will require the user to scroll a lot. I think we can refine a little bit our use of the space (and maybe the font sizes) in order to display one dependency in a more efficient way.

**Comment by ravsa** [comment]
Thanks, @slemeur It is very helpful.
