### ISSUE TITLE
Remove Anitya service

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1765]
# User story

As a fabric8-analytics developer, I want to remove Anitya bits from the codebase and stage/prod deployments so this no longer used component is not consuming resources and flows are simpler.

# Description

We started using Anitya service for upstream release monitoring long time ago. Requirements changed since then quite significantly - we started relying on libio to provide information about latest releases (and on maven-index-checker for Maven). Therefore there is no need to keep Anitya service around anymore. We want to preserve GitHub repository with our patches, but we want to exclude Anitya from the main flow and we want to delete it from all current prod/stage deployments (+from dev cluster deployment scripts). CI/CD will probably also need to be modified.

# Tasks
TBD
 

# Acceptance criteria

- [x] Anitya bits are no longer present in the codebase
- [x] CI/CD configuration is modified so merges to master branch don't trigger deployment
- [x] Anitya containers are not running in staging/prod

**Comment by pkajaba** [comment]
- [ ] CI Change: https://github.com/almighty/almighty-jobs/pull/458
- [ ] worker changes https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/491
- [ ] CD changes
- [ ] local deployment changes
- [ ] devcluster changes

**Comment by pkajaba** [comment]
@msrb I have discovered that there are some database changes required (we are currently storing latest version in RDS and graph DB, same applies to some downstream data).

My current status is that I did the groundwork for removing and I have to focus on testing of the system because I don't want to broke it.

**Comment by pkajaba** [comment]
I am already done with removing codebase and CI/CD part. I am waiting until services are scaled down in stage and production. We decided to scale down services instead of removing them. In some rare circumstances we might need it, so it will stay there.

**Comment by msrb** [comment]
@pkajaba I think we can delete the deployments. If we don't depend on them in the code, then there is no reason keeping them around (IMO).

**Comment by msrb** [comment]
Of course we can just scale them down for now and delete them once it's clear we won't need to rollback  from some reason.
