### ISSUE TITLE
POC - Display Insights from Fabric8-Analytics at Che UI

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#1768]
#### User Story:

As an OSIO user, I will be able to see insights from Fabric8-Analytics platform inside Che UI as the user adding in new packages at IDE.

#### Description:
Insights are shown inside Che UI as the user adding in new packages at IDE which include insights for the combination of packages, licenses used, additional and alternate packages.

### Tasks:

- [x] License insights into the combination of packages.
- [x] License being used for the packages.
- [x] Insights into additional packages that can be added
- [x] Insights into replacing any current package(s) being used with an alternative package(s) typically used for the kind of application user is building.
