### ISSUE TITLE
Stack Report design revamp

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1773]
### User Story:
As an OSIO Developer I will be able view more detailed stack report so that I can get lot more clarity. I should be able to view the information on demand rather than all at once.

### Description:
As a fabric8-analytics developer, I would like to implement the stack report on openshift.io based on the revamped UX (as per 
https://redhat.invisionapp.com/share/6TF4C40KF#/screens/270947409) so that the OSIO users get a more intuitive UI to look at the analytics data and recommendations.

### Acceptance Criteria:
An openshift.io user views her/his stack report as per the wireframe provided by 
https://redhat.invisionapp.com/share/6TF4C40KF#/screens/270947409.
Now user can not only view details in trivial way but also sees graphical and more attractive way.

### Work items:
- [x] Designing of the data model to properly store and represent the data for better flow.
- [x] Developing the UI for the modal
- [x] Developing the Summary UI for the dashboard screen
- [x] Developing snippet view for the pipelines screen

#### Designing of the data model to properly store and represent the data for better flow.

- [x] Split data representation as atomic and reusable as possible
- [x] Use classes

#### Developing the UI for the modal
- [x] Developing the summary widget
- [x] Integrating it with services
- [x] Writing unit test cases

- [x] Developing the information screen
- [x] Integrating it with services
- [x] Writing unit test cases

- [x] Writing necessary end to end test cases

#### Developing the Summary UI for the dashboard screen
- [x] Developing the summary widget
- [x] Integrating it with services
- [x] Writing unit test cases
- [x] Writing necessary end to end test cases

#### Developing snippet view for the pipelines screen
- [x] Developing the snippet view as per ux
- [x] Integrating with services
- [x] Test cases

**Comment by sivaavkd** [comment]
Changes are yet to be pushed to prod

**Comment by arunkumars08** [comment]
@sivaavkd Changes for the modal are in prod. The design in the dashboard hasn't been moved yet and will be moved sooner. @jyasveer

**Comment by jyasveer** [comment]
changes for the dashboard are moved to prod now. so i am closing this issue.
