### ISSUE TITLE
Work items for publishing VSCode extensions

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#1793]
## User Story
As a Fabric8-Analytics developer I would like to close on open tasks so that VSCode extension can be published

## Description
We have already identified the various open items/tasks/issues which we need to close in order to publish VSCode extension to marketplace.This serves as master list to track all open items for Same

## Task List
--- Effective Pom ---
- [x] VSCode extension to generate effective POM for a particular POM file. (https://github.com/openshiftio/openshift.io/issues/1763)
- [x] Generated effective pom file should be stored in same level as POM.xml
- [x] VSCode extension to generate effective POM for the Workspace level.
- [x] Accommodating stack-analysis call with effective pom for a particular pom. 
- [x] Accommodating stack-analysis call with effective pom at workspace level. 

--- Taking to prod ---
- [x] 3scale apicast -gateway needs to be taken to prod
- [x] 3scale connect api needs to be taken to prod
- [x] getting dedicated 3scale enterprise account
- [x] Creating a application plan/services/metrics for stage 
- [x] Creating a application plan/services/metrics for Prod

--- Issues ----
- [x] Size of extension is huge like 94MB for f8-analytics (https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/54)
- [x] On unauthorization, multiple markers appear. (https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/53)
- [x] If try to trigger "generate fabric8-analytics stack report on workspace" on VSCode without having any workspace it shows loading screen. (https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/42)
- [x] Error while authorizing OSIO on VSCode 1.19.1 (https://github.com/fabric8-analytics/vscode-osio-auth/issues/22)
- [x] Ctrl + Shift + P triggers the unauthorize OSIO service instead of triggering the VScode build-in command palette on fedora. ( https://github.com/fabric8-analytics/vscode-osio-auth/issues/27 )
- [x] LSP is not getting triggered on VSCode 1.17.0
- [x] Show some meaning full message on browser post authorisation from Openshift.io currently it shows blank screen
- [x] Remove unneeded popups being shown up
- [x] Show notification/indication to user if Effective Pom is getting generated as currently it looks like nothing is happening post user action. 
- [x] Stack report shows path of effective pom's not actual pom, this should be other way
- [x] improve login flow with footer "Openshift.io" , on first click let user authorize if not authorized else prompt with "Already authorized with Openshift.io, would you like to reauthorize/unauthorize"
