### ISSUE TITLE
Publish Devstudio IDE Plugin.

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#1795]
## User Story
As a Fabric8-Analytics developer I would like to close some tasks, so that Devstudio Plugin is ready to be published.

## Description
We have identified the various open items/tasks/issues which we need to close in order to publish Devstudio Plugin. Following is the task list for the same.

## Task List
--- Effective Pom ---
- [x] Create a async job to retrieve effective pom.
- [x] Accommodating stack-analysis call with effective pom for a particular pom. 
- [x] Accommodating stack-analysis call with effective pom at workspace level. 

--- Enable/Disable Button ---
- [x] Change the icon and text of button.
- [x] Open a dialog page to inform user of the various services.
- [x] Integrate the dialog page with authentication mechanism.

--- Make build Windows compatible ---
- [x] create a job that use a pomless maven exec to fetch and unpack a tar.gz from nexus
- [x]  Use the tar instead of zip

--- Find project wide pom files recursively ---

- [x] Change the selection form single file to entire project.
- [x] Find pom files recursively
- [x] Add tests in workspace file finder.

 Change the icon and text of button.
- [x] Open a dialog page to inform user of the various services.
- [x] Integrate the dialog page with authentication mechanism.

--- Taking to prod ---
- [x] 3scale connect api needs to be taken to prod

--- Features ----
- [x] Send Effective Poms for analyses

--- Issues ----
- [x] WIP: Add Unit Tests and Integration Tests (https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/105)
- [x] WIP: Lookup of project wide manifest files to utilize multi maven support in stack analyses. (https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/104)
- [x] Change the 3scale URLS to production one and update the lsp server urls. (https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/102)
- [x] Build is not Windows compatible (https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/98)
- [x] LSP server authentification. (https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/91 )
- [ ] Fix builds on LSP installation(https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/133, https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/125)
- [x] Add timeout for loading the analyses in StackAnalyses view.(https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/86)
- [x] Change ROUTES and SERVICE ID’S to the production 3scale urls.(https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/102)
- [x] Change of maven pom files temporary storage.(https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/127)
- [x] Fix broken tests(https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/129)

**Comment by GeetikaBatra** [comment]
@sivaavkd, can we close this one?
