### ISSUE TITLE
Add support for `released` level of feature

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#1912]
Once released, a feature should be set to the released level (and presumably, all other levels could be removed). This level might be kept for a few weeks after the release, in order to keep a mean to roll it back in case something wrong. Once the delay is expired, we should remove all conditional statements in the code base and remove the feature settings in the toggle server, and keep the feature in the code without any toggle flag around.

Since the UI currently support the `nopreproduction` level, the following stages of deployment are proposed:

1. [x] Update the UI to support both `nopreproduction` and `released` values for the users' consent when they only want to use stable/released features, so that both values can be used to select the radio button on the users' profile page. If users change their consent, the `released` value should be used instead of `nopreproduction` (#1960)
2. [x] update `fabric8-auth` to support `released` as the default value for the users consents (#1937)
3. [x] update the content of the users profile in the `fabric8-auth` database so that all `nopreproduction` values are changed to `released`. At the end of this stage, the `nopreproduction` level value should be used anywhere in the system (#1962)
4. [x] support the new `released` value in `toggles-service` (see https://github.com/fabric8-services/fabric8-toggles-service/pull/28)
5. [x] update the UI to get rid of all older use of `nopreproduction` values in its codebase (#1961)

**Comment by xcoulon** [comment]
@qodfathr I'm not sure I understand the `Projects` / `Needs Parent in team/PM` metadata here. I just submitted a PR to resolve this issue, does it mean I need to hold it until you approve the issue itself ?

**Comment by xcoulon** [comment]
reopening (was closed by the `fixes...` in the commit message of https://github.com/fabric8-services/fabric8-toggles-service/pull/28), but https://github.com/openshiftio/openshift.io/issues/1961 isn't done yet.

**Comment by xcoulon** [comment]
closing now, as all sub-tasks have been resolved.
