### ISSUE TITLE
Codebases and Workspaces UI

### ISSUE THREAD

**Issue by ashumilova** [openshiftio/openshift.io#1936]
### Description
In an OSIO space, a user is able to configure multiple codebases. At this moment, the user is able to manage the different codebases.
The users who are coding on the codebases are creating Che workspace - but the current capabilities of OSIO don't allow the user to manage his workspaces easily. In some cases, it also requires the user to go into the Che's dashboard in order to be able to do certain actions.  

We would like to introduce a new UI, which will allow the user to more easily create and manage his workspaces. For that we are going to introduce a new "Workspace" UI and refine the current "Codebase" UI, in order to handle the following use cases:

- As a user, I want to be able to create a workspace and specify its name + the branch it will use.
- As a user, I want to be able to see all my workspace with their current state (running, stopped,...) so I can easily access my workspaces and manage them (delete/stop) 
- As a user, I should be able to see all the branches of my codebases and access to their corresponding workspaces

### Mockups
https://redhat.invisionapp.com/share/V9EIZNOZX#/screens/263956702_Codebases_And_Workspaces_1.

### Sub-tasks
The tasks needed for this epic are both implementing missing codebases API parts and finalizing the UI that has already get started:
- [ ] Extend API for interaction with Che workspaces https://github.com/openshiftio/openshift.io/issues/1439
- [ ] Improve the list of codebases by including workspaces info https://github.com/openshiftio/openshift.io/issues/1331
- [ ] Add new entry point for workspaces retrieval per space https://github.com/openshiftio/openshift.io/issues/1332
- [ ] Add repositories layouts according to new designs https://github.com/openshiftio/openshift.io/issues/1434
- [ ] Connect the workspace list page with API interactions https://github.com/openshiftio/openshift.io/issues/1432

### Note
For simplification and getting a first iteration of this work in place quickly, we will not handle the branch comparison.

## Associated defects
- [ ] #587 Date based codebase filters treat dates as strings, not as dates

## Parent Scenario
#2058

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2004
