### ISSUE TITLE
Automated Definition of Done

### ISSUE THREAD

**Issue by bartoszmajsak** [openshiftio/openshift.io#1941]
We spent an enormous amount of time focusing on things which are not the core of the PR itself. This includes, but it's not limited to:

- Code quality aspects
  - is a feature shipped with tests and docs
  - proper syntax
  - common bugs
  - docs 
  - code coverage
- Pull Request
  - is the description provided?
  - is it linked to existing issue? 
  - are commits [using proper labels](https://seesparkbox.com/foundry/semantic_commit_messages)?

Having this steps automated will not only let us focus on the important aspect of the code review, but also ensure that we all stick to the standards and ship high-quality software. In addition, this lets us gather data about the way how we work to identify challenges and improve.

- [ ] Define a workflow (to be discussed during F2F)
- [ ] Investigate existing tools which can be incorporated into our developer workflow 
- [ ] Design and develop a service which can be used by all teams (with the goal to be eventually integrated into OSIO)

**Note** The idea behind this work is to first start using it internally and on GH, where the code lives, and if proven useful and important we start defining UX for OSIO components/services.

**Comment by abs51295** [comment]
👍  Looking forward to this. Would be very nice to have this :)
