### ISSUE TITLE
OSIO Stability improvements

### ISSUE THREAD

**Issue by bartoszmajsak** [openshiftio/openshift.io#1942]
### Contract testing

- [ ] introduce contract testing between key OSIO components
- [ ] build a service for sharing contracts and orchestrate builds

### Ensuring cluster update stability

- [ ] develop a mechanism to detect configuration mismatch prior to rolling out the new cluster
