### ISSUE TITLE
[Checklist]: Items to be addressed with VSCode extension and Stack report revamp

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#1974]
Checklist of items to be addressed from VSCode IDE and revamped Stack Report point of view. The following list is formed after the demo.

### In Revamped Stack Report:

- [x] Colors for manifest tabs (indicate colors based on highest severity (CVE))
- [x] Security card notification color has to be based on cve progress colour
- [x] Insights color has to be changed (not red, may be warning color)
- [x] License icon
- [x] License card has to be 2nd moving the insights next.
- [x] Instead of components use the word ‘dependencies’
- [x] Label name ‘Stack License’ -> ‘Compliant/Recommended License’
- [x] License conflicts, unknown, restrictive has to have names that says ‘dependencies’ (e.g.. Dependant license conflicts)
- [x] Revisit description texts in all cards
- [x] Handle card height based on highest content
- [x] Remove OSIO usage count (Statistics until GA)
- [x] Github card alignment
- [x] In detail tabs, show count of entries before hand
- [x] No data scenario - left align
- [x] Pipeline CVE's should be clickable and take it to the same place as click of stack report link

### API Changes:

- [x] Stack level license has to be accompanied by the current license in the stack https://github.com/openshiftio/openshift.io/issues/2043
~Show alternate versions if available for a dependency in case of CVE’s https://github.com/openshiftio/openshift.io/issues/2008~

### Open discussion:

- Once the build is completed, if CVEs are found after ’n’ days -how to notify the user?
- Need more discussion on how to flag components with CVE’s (New pipeline build triggers or something else)

### VScode Changes:

- [x] Quick start Wordings
- [x] the GIFs shown are going way too fast.
- [x] Needs PM review with Readme (https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/blob/master/README.md, https://github.com/fabric8-analytics/vscode-osio-auth/blob/master/README.md)
- [x] Pass Licence info along with manifest file

**Comment by arunkumars08** [comment]
cc: @krishnapaparaju

**Comment by joshuawilson** [comment]
@sivaavkd @RanjithRV what `type` should this be?

**Comment by RanjithRV** [comment]
@joshuawilson As this is listing a bunch of small issues thrown together...I am marking it as type/paper-cut for now

**Comment by krishnapaparaju** [comment]
@miteshvp  @invincibleJai   would  license at repo. level (current license) be optional at required API changes ?

**Comment by invincibleJai** [comment]
@krishnapaparaju i'll be passing licence data as an extra parameter while making POST stack-analysis call

**Comment by miteshvp** [comment]
@krishnapaparaju - Yes, license at API will be an optional parameter. It will be handled accordingly

**Comment by arunkumars08** [comment]
UI items have been closed from this list.

**Comment by arunkumars08** [comment]
@miteshvp Hey Mitesh, you can have a look once and feel free to close this issue if you feel the API changes are taken care.

**Comment by sivaavkd** [comment]
@miteshvp - I think we are done with all the changes.  Can you please review and close it ?
cc @arunkumars08 @invincibleJai

**Comment by sivaavkd** [comment]
@miteshvp - a gentle reminder !!!

**Comment by miteshvp** [comment]
License API - https://github.com/fabric8-analytics/fabric8-analytics-server/pull/276
