### ISSUE TITLE
Centralize cluster configuration across services

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1988]
Provide a central API that holds information about the configured clusters.

- [x] GET /api/clusters to provide OSO cluster info https://github.com/fabric8-services/fabric8-auth/issues/282
- [x] Add automatic backend discovery support based on Cluster API https://github.com/fabric8-services/fabric8-oso-proxy/issues/3
- [x] Implement Cache Warm up and validation of Cluster tokens during startup https://github.com/fabric8-services/fabric8-tenant/issues/515

## Parent Experience
#2172 OpenShift.io is multi-cluster capable

**Comment by alexeykazakov** [comment]
auth.openshift.io/api/clusters is now available in both prod and preview. Removing /team/auth from the issue.
