### ISSUE TITLE
OpenShift.io registration and on-boarding process is Pleasant and Inviting

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2015]
First impressions matter.

When a user first registers to join OpenShift.io, it should be a friction-free experience, getting them into the product as quickly as possible and immediately engaged with their first learning actions.

## Realizing Experiences
- [ ] #286 OSIO Register, Sign up, login flow
- [ ] #2109 OpenShift.io registration queuing
- [ ] #2884 First time user experience of OSIO

ref: https://openshift.io/openshiftio/openshiftio/plan/detail/2169

**Comment by catrobson** [comment]
There is UX activity at the next level down in the hierarchy.

Summary:
* There are UX flows completed here:  https://redhat.invisionapp.com/share/PYG7IRFXZQD
* We're meeting with the various Dev team stakeholders to discuss implementation, back end and front end.  
* Front end: Minimal or no UI changes are required in OSIO, main UI changes will be in the OpenShift.io webpage and we're working on designs and implementation of that this and next week.  
* Back end:  Size of changes TBD after discussion
