### ISSUE TITLE
Finding meaningful and actionable information within a large development project

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2026]
As a development project continues to grow along multiple dimensions -- the size of the team, the amount of work tracked (both past, present and future), the number and variety of artifacts created, etc. -- it runs the risk of becoming an undecipherable ocean of data. Large data sets, in of themselves, are often indistinguishable from noise.

The ability to extract meaningful and actionable information from these large data sets can be crucial for the success of a development project.

## Realizing Experiences
- [ ] #346 Account Dashboard
- [ ] #351 Teams (overview)
- [ ] #478 Space - management
- [ ] #978 Notifications in OSIO
- [ ] #2027 Easily searching across all the development artifacts of OpenShift.io
- [ ] #2032 Space Dashboards
- [ ] #2725 Impact of Teams on the Planner
- [ ] #2726 Team Dashboards

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/1992
