### ISSUE TITLE
[User-Story] Admin UI for the feature toggles service

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#2052]
Belongs to [Epic: feature flags - phase2](https://github.com/openshiftio/openshift.io/issues/2049)

# Description
As a PM I should be able to access a admin UI to:
- toggle off a feature (in case of an issue)
- rollout a feature from beta to released etc...
- easy way to group feature
- provide an export tool to retrieve the list of features (json format) so it can be used for hard-coded features in the UI.  (to be used by menu and/or by the information page for the user to know which feature is in beta, exp...)
No login. the admin could be accessible as the unleash admin is (request htaccess login to SD team)

# List of tasks:
- [ ] spike: investigate if we reuse unleash admin: reactJS, technologies different
- [ ] boostrapper angular UI - build, runtime, create repo
- [ ] endpoints admins: reuse unleash sdk - investigate if reuse sdk or rest endpoint
- [ ] ask UX for mock-up: could display a treeview which would display for each item the level of enablement (a combo?) and an enabled/disabled button.
- [ ] express validation: one parent is beta, all children beta. Cascading action to guide PM user.
- [ ] add feature in feature hierarchy

# Out of scope
- login
- not embedded in OSiO

**Comment by corinnekrych** [comment]
As discussed closing this one. we'll see later if we really need it (we can always re-open)
cc @xcoulon @aslakknutsen @joshuawilson
