### ISSUE TITLE
[6] Feature toggle for component

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#2056]
belongs to [Epic: feature flags](https://github.com/openshiftio/openshift.io/issues/1165)
# Description
As a developer I want to be able to wrap an angular component with a wrapper. the wrapper will contain the name of the feature which is embedded.
# List of tasks:
- [x] wrap feature component to hide them if feature is not enable. No dynamic load. https://github.com/openshiftio/openshift.io/issues/2362
- [x] UX to provide mock-up on how to display exp component (no display at all or banner?)
- [x] Display feature-flagged component as per UX design https://github.com/openshiftio/openshift.io/issues/2400
- [x] spike: dynamic loading of component ie: [angular.io doc](https://angular.io/guide/dynamic-component-loader) https://github.com/openshiftio/openshift.io/issues/2363
- [x] implement dynamic load of component
- [x] document how to a developer should wrap (in code) a feature component
- [x] implement Feature Flag no visible feature as per screen https://redhat.invisionapp.com/share/KAF97RBGB#/screens/276638408, 
- [x] make all module dynamic loaded only if feature level is enable for this user. https://github.com/openshiftio/openshift.io/issues/2554
- [x] [spike] group all components visible in a UI menu page, to make only one call to `fabric8-toggles-service`. Possibly enhance existing endpoint [List features](https://github.com/fabric8-services/fabric8-toggles-service/blob/master/controller/features.go#L83) or create new one. Use naming convention `planner.*` to retrieve all feature associated with planner menu.
cc @xcoulon
