### ISSUE TITLE
User managed fine-grained access control in OpenShift.io

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2068]
A team is looking to adopt OpenShift.io. However, they need to maintain a fine level of control over access to various parts of OpenShift.io -- such as who is allowed to create certain content, who is allowed to view it, who is allowed to edit it, who is allowed to delete it, who is allowed to perform certain kinds of operations, etc. These requirements for control may be a result of legal reasons (e.g. Federal regulations, such as FDA CRF 21 PART 11) or just internal business desires and constraints of the organization.

## Supporting Value Propositions
- [ ] #2070 Access Control
- [ ] #2071 Operational Control

## Realizing Experiences
- [ ] #2069 End-to-end Experience
- [ ] #2072 System-level access control
- [ ] #2073 Entity(User)-level access control
- [ ] #2074 Entity(Organization)-level permissions
- [ ] #2075 Space-level permissions
- [ ] #2076 Team-level assignment
- [ ] #2077 Security Group-level assignment
- [ ] #2078 User-level assignment
- [ ] #2081 Permission states
- [ ] #2080 Permission resolution
- [ ] #2088 Security Groups
- [ ] #2089 Teams

# The Spirit of this Scenario

We consider permissions from at least two different angles -- the first being “what kinds of permissions are possible and what can they do?” and the second being “here are some specific permissions to define.” The goal is to have a highly flexible system, such that Extensions can define their own permissions. For example, the Planner may want to define a set of permissions which are specific to Planner usage -- e.g., who can create new work items, who can view them, who can define new layouts for the task board, etc. None of these permissions need to be ‘predefined’ within the ‘core’ of the OSIO platform itself; rather, OSIO needs to make it possible for an Extension to add these various permissions to the permissioning system of OSIO, such that when the system is run, a user can use the permissions in a natural way. This is also an attempt to unify all permissions under one consistent UX.

## See also
- #1630 
- #1632

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2035
