### ISSUE TITLE
Promoting and Adopting new Frameworks for Developers

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2083]
A software developer or team has created some code to be consumed by other developers -- for example a new framework, library or package. Even if it is the world's greatest framework, if it goes unseen or unused, it will never achieve its potential.

Developers who are likely candidates to consume things such as new frameworks and packages face the [Paradox of Choice](https://en.wikipedia.org/wiki/The_Paradox_of_Choice). Moreover, even the seemingly easiest frameworks and libraries have high learning curves, if only for the need for the consumer to make the appropriate context switches. Using someone's else code has been described as "trying to read their mind."

Increasing the discoverability of packages, frameworks and the like, combined with the lowering the barrier to adoption for new consumers likely benefits both the producer and the consumer. For example, history has shown that even extremely complex frameworks, such as DirectX and JEE, have been able to achieve popularity, in part, due to (1) discoverability within tools such as Visual Studio and Eclipse and (2) "hello world"-style templates and wizards within those tools.

## Realizing Experiences
- [ ] #2084 Getting Started Quickly with a Framework - from Wizard, to IDE, to Deployment
- [ ] #2085 Getting Started Quickly with a Framework - from Import, to IDE, to Deployment
- [ ] #1317 Further merge the Launcher and OSIO project creation wizard

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2050
