### ISSUE TITLE
Getting Started Quickly with a Framework - from Import, to IDE, to Deployment

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2085]
**WIP**

E2E experience -- decompose into peer experiences

Import Wizard
Che
Pipeline

## Implemented Features
- [ ] #282 Public GitHub Repos - Verify the free tier for users on OSIO
- [ ] #1365 Import repo wizard: UX revisited summary page

## Associated Defects
- [ ] #113 Doing an import codebase and selecting the default options seems to kick off master builds continually
- [ ] #518 
- [ ] #534 
- [ ] #541 
- [ ] #1360 
- [ ] #1832 
- [ ] #1880 
- [ ] #1947 
- [ ] #1948 
- [x] #1949
- [ ] #1950 
- [ ] #1951 
- [ ] #1952 
- [ ] #1953 
- [ ] #1954 

## Parent Scenario
#2083

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2056
