### ISSUE TITLE
POC for automating mapping CPEs to individual application dependencies

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2106]
Automation of CPEs would require these following steps and to start with , wanna focus on step (4) which carry most of the uncertainty.

Would suggest we run down this POC for Node, Python ecosystems..

1. Gather all the content from CPE description and associated links mentioned at CPE
2. Pick a CVE a NVDB and gather (manually) all the possible dependencies (master list)
3. Gather tags / intent for all the dependencies gathered in the step (2) (manually)
4. Write multi class regression algorithm to generate possible dependencies matching the CPE description

# Tasks
- [x] [Document how current CVE job works](https://github.com/openshiftio/openshift.io/issues/2121)
- [x] Improve [cvejob](https://github.com/msrb/cvejob) to extract and parse relevant information correctly.
**Update**: This has been done by creating a new library [nvdlib](https://github.com/msrb/nvdlib).
- [x] Analyze cve entries from NVD database and find number of entries with direct GitHub reference.
- [ ] Have a way to trace GitHub (or a relevant scm) from CVEs with indirect GitHub reference.
- [x] If acceptable, for those entries, implement a way to infer package and corresponding ecosystem.
- [ ] Improve existing approach regarding package inference from CVE description.

**Comment by sivaavkd** [comment]
@abs51295 and @CermakM - Please create individual user stories and link them to this epic. If you think that this is a story sized, and not an epic sized, let us discuss more.

**Comment by msrb** [comment]
@sivaavkd it's important to keep in mind that everything around CVEs is basically a research project. We need to try things and see what works and what doesn't. So the possibility of not delivering anything useful at the end of the sprint is always there.

**Comment by msrb** [comment]
I see one potential problem with using tags. CVE description and most of the links don't discuss the package itself. They describe the vulnerability. Therefore trying to connect CVE (description+links) with packages based on tags could be difficult. Of course, if we could identify which of the links points to the project's homepage, that could help us a lot. The same for GitHub/SCM links.

**Comment by krishnapaparaju** [comment]
right. Package names are not typically mentioned in the description. Hence tags describing the master list of packages would be one possible approach (this poc) to interpose onto the content (description + content from the links).

**Comment by CermakM** [comment]
@krishnapaparaju, @msrb, @abs51295 , @sivaavkd 

I've created a flowchart of an approach that I am currently exploring.

PTAL at [CVE research flowchart](https://github.com/CermakM/cvejob/blob/research/research/cve-analysis-flowchart.png)

also, analysis of gh-references cves from NVD json feed is available at

[GitHub reference analysis](https://github.com/CermakM/cvejob/blob/research/research/cve-gh-refs-analysis.png)


In the first stage of the process, I focus on the right side of the graph. I try to figure out the number of results (and the number of false-positives) that is produced, given that the source is traceable. The ecosystem and package estimation using this approach should be very accurate (but we'll see about the results). 
As an additional comment, the benefit of this is that we eventually should be able make use of both, the [cvejob](https://github.com/msrb/cvejob) repository and the [workers](https://github.com/fabric8-analytics/fabric8-analytics-worker/tree/master/f8a_worker/workers) that we already have implemented.

**Comment by CermakM** [comment]
[Here](https://github.com/CermakM/cvejob/blob/research/cve-spike-gh-analysis.ipynb) is the analysis of GH references.
Also, providing [link](https://github.com/CermakM/cvejob/blob/research/cve-spike-package-from-gh.ipynb) for the latest dashboard - atm I have implemented convenient ecosystem based search and visualization through CVEs (local setup needed, however).

**Comment by msrb** [comment]
This is an epic, but we should probably close it and create another one (for automating CVE mapping), as this is a mixture of different ideas and tasks...

**Comment by sivaavkd** [comment]
@msrb - I agree with your comment that we can close this and create another one with specific approach.  @CermakM - Can you please create a new one with details ?
