### ISSUE TITLE
Profile Screen

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2135]
WIP

## Implementing Features
- [ ] #1775 Ability to select Private or Public for the Email address on user profile page

## Associated Defects
- [x] #862 Updating user profile requires browser refresh to see the changes
- [x] #1881 Wrong email validation on profile page
- [x] #2100 Line wrapping doesn't seem to be supported in profile bio

## Parent Scenario
- [ ] #2134 Creating one's professional brand in the software industry

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2061
