### ISSUE TITLE
Planner Backlog Management Experience placeholder

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2162]
WIP

## Implementing Features
- [ ] #1840 Add Ctrl+Enter support to submit comment / confirm text / confirm markdown area
- [ ] #2157 Planner iterations Feature placeholder
- [ ] #2160 Planner backlog Feature placeholder

## Associated Defects
- [ ] #1595 Planner: Work Item descriptions and comments do not have a maximum characters limit
- [ ] #1814 HTML entities not rendered in Planner Item Title
- [ ] #1827 Creating a Scenario in selected Iteration does not assign the Scenario into the Iteration
- [ ] #1831 Planner calendar doesn't allow date usage
- [ ] #1846 WI Type incorrectly set if quick add is committed using Enter key
- [ ] #1983 Filter by Creator|Assignee cause Type error in Console and hang for ever 
- [ ] #2288 Planner: arrow icon next to items that cannot be expanded

## Associated Questions
- [ ] #2044 Question to PM: Exploration of child workitems under a matching workitem entry

## Parent Experience
#2146 Planning Experience placeholder

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2009
