### ISSUE TITLE
Sprint plan for Fabric8 Analytics: #145

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2216]
**IDE Extensions:   Publish  IDE extensions**

- [x] Revisit 3Scale SaaS to fix CORS issue
- [x] Explore AWS API Gateway if CORS issue could not resolved with 3Scale SaaS 

**Adding Insights to the platform**
***WF Swarm***
- [ ] Promote changes to production: insights to cover WildFly Swarm applications  #2090 

***Node***
- [ ] Implement post filter for 'CVAE' and document insights been generated along with accuracy (manual testing to start with) (#2264)
- [x] Figure out deployment of TensorFlow with  RHEL as base image (#2331)

**Getting Started Experience**
    **Integrate Launcher into OSIO** - https://github.com/openshiftio/openshift.io/issues/2178
- [x] Wrap up all the UI side navigation issues
- [ ] Tests are in place for the UI components
- [ ] Integrate with mocked backend API

**Make the boosters work at OSIO user flow**
- [ ] #2217

**Dependency Editor**
- [ ] Create standalone Launcher for demonstration (with backend API, Dependency Editor UX) https://github.com/openshiftio/openshift.io/issues/2260, https://github.com/openshiftio/openshift.io/issues/2275 , https://github.com/openshiftio/openshift.io/issues/2302
- [ ] Integrate Dependency editor into Launcher

**Scale the platform to support 1000 concurrent users from 500 concurrent users (#1144)** 
- [x] Document the test results
- [x] Work with SD team to get necessary resources
- [ ] Promote changes to OSIO

**Enable OSIO Gemini related activities**
- [x] Define the end to end flow around various components involved at Fabric8 Analytics platform
- [ ] Design & Development (https://github.com/openshiftio/openshift.io/issues/2326)
- [x] Work with Bama to start integrating Fabric8 Analytics with a new Scanner
- [ ] Change base image from Cent OS to RHEL https://github.com/openshiftio/openshift.io/issues/2259

**Map CVEs for the Maven, Node ecosystems**
- [x] Continue the current manual mapping from NVDB to individual packages
- [x] POC for automating CPEs to individual dependencies #2106 
- [ ] Determine version ranges from NVD data https://github.com/openshiftio/openshift.io/issues/2006

**Improve service side for better handle on service deployment**
- [ ] #1084 

**Data ingestion, sanity related activities**
- [x] #2048 
- [ ] #2221
- [x] #2161
- [x] #2236 
- [x] #2238 
- [x] #2240 
- [ ] #2220 
- [x] #2012 
- [ ] #2222 

**Quality**

- [x] #1229
- [x] #1232
- [x] #2094
- [x] #1745
- [x] #2248
- [ ] #1635
- [ ] #1636
- [ ] #2257
- [ ] #2256
- [x] #2310
- [x] #2311
- [x] #1228

<img width="27" alt="screen shot 2018-01-19 at 6 04 16 pm" src="https://user-images.githubusercontent.com/15967765/35151147-3731edb6-fd43-11e7-9fdb-da70b2f55db0.png"> **[Stretch goal] POC, UX for application stack editor, supporting multi container applications**

- [ ] Work with Stevan to refine the specification for application stack editor

- [ ] Start with POC for application stack editor

<img width="27" alt="screen shot 2018-01-19 at 6 04 16 pm" src="https://user-images.githubusercontent.com/15967765/35151147-3731edb6-fd43-11e7-9fdb-da70b2f55db0.png"> **[Stretch goal]  Integrate insights into Che editor**

- [ ] Current POC:  Get feedback from PM team

- [ ] Work with UX team to finalize the UX changes

- [ ] Integrate the changes to LSP and deploy changes at OSIO
