### ISSUE TITLE
Make the boosters work with Launcher at OSIO

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2217]
The boosters documented here at 
https://github.com/fabric8-launcher/launcher-documentation/wiki.

These boosters would need to working at OSIO launcher and across the complete user flow for an OSIO user (Che, Build, Analytics)

## Parent Experience
#2084 Getting Started Quickly with a Framework - from Wizard, to IDE, to Deployment

#### Task List
- [ ] Redhat GA Booster ingestion to Analytics #2481
- [ ] E2E Tests to include more Coverage #2399
- [x] Discuss and identify gaps in the current E2E Tests w.r.t boosters

**Comment by bartoszmajsak** [comment]
Thread on detailed steps to validate boosters can be found on the [`#fabric8-launcher` mailing list](https://groups.google.com/d/msg/fabric8-launcher/NypXPuyoCrg/Ic-SWweOCgAJ).

**Comment by ldimaggi** [comment]
Test for running maven install and test commands from Che terminal - https://github.com/fabric8io/fabric8-test/pull/463

**Comment by miteshvp** [comment]
Gaps identified and documented https://docs.google.com/document/d/1bqRPSOyd7PA1FYSPFMlH-BfyDIBaMI8ysHnrZ1TpsoM/

**Comment by miteshvp** [comment]
Closing this issue as all the task list is added as part of https://github.com/openshiftio/openshift.io/issues/2776

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2055
