### ISSUE TITLE
Backend API Service Implementation for Dependency Editor

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#2223]
#### User Story:

As an OSIO user, I will be able to get Stack Analysis and CVE analysis for user stack.

#### Description:
Implementation of logic for storing dependency snapshot column in RDS and creating API end-points for dependency editor and decoupling of services.

#### Tasks:
- [x] A column should be added to the RDS stack analysis table for storing Dependency Snapshot as JSON
- [x] Implement the logic for storing Dependency Snapshot in the Database.
- [x] Implement CVE Endpoint to serve dependency editor which take a list of (ecosystem, package, version) as input.
- [x] Implement Upsert in POST stack-analysis so that it does not create duplicate entries in RDS.
- [x] Implement logic for optional parameter `sid=<request_id>` in POST stack-analysis so that it flags the dependency editor modified.
- [x] Implement Upsert in POST recommender and POST stack-aggregator endpoint in f8a backbone service.
- [x] Create a new Asynchronous independent API endpoint in f8a backbone service.
- [x] Implementation of logic `persist=false|true` in recommender and stack-aggregator endpoint in backbone services.
- [x] Create a new Synchronous POST API endpoint for dependency editor analysis which gives response same as stack-analysis call.
- [x] Implement logic for getting cves for the list of packages from graphdb.
