### ISSUE TITLE
License scoring services for dependency editor

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#2224]
## User story
As an OSIO developer I should get a conflict free representative license for my selected stack.

## Description
Currently there is no separate public facing API endpoint for license services. As of now all the license scoring activity was done internally while calling the stack-analysis endpoint. With the current implementation a user won't be able to get a representative license for it's selected packages. This user story aims to create a separate public facing API endpoint for license scoring services. A user can successfully get a representative license for selected stack by using this API endpoint.

## Acceptance criteria
A separate public facing API endpoint for license scoring services with authentication mechanism in place so that a particular group of user can only use the service.

## Task List
- [x] Create a public facing API endpoint for license scoring services.
- [x] Create necessary API endpoint to serve dependency editor.
- [x] Implement authentication mechanism.
