### ISSUE TITLE
Audit the existing fabric8 pipeline library and create a new OSIO pipeline library if need be.

### ISSUE THREAD

**Issue by pradeepto** [openshiftio/openshift.io#2243]
https://github.com/fabric8io/fabric8-pipeline-library is huge. We need to audit it, figure out the relevant bits. Extract these relevant, required and important bits into perhaps a new OSIO pipeline library.

For the audit, we need to figure out where the libraries and which parts of it are being used across OSIO. Also, check if they are being used in the booster/launcher projects.

- [ ] Audit https://github.com/fabric8io/fabric8-pipeline-library
- [ ] Create a new pipeline library with the relevant bits
- [ ] Test for feature parity and make sure it works for all known customers.

**Comment by bartoszmajsak** [comment]
Few observations from my side while working on the fix for Boosters imported through quickstart (so having Fabric8 pipeline library used)

- only "CI" builds executes integration tests, regular builds on `master` branch (so "CD" part in the `f8-p-l` book) runs regular tests unless specified differently (see [here](https://github.com/fabric8io/fabric8-pipeline-library/blob/4b899c6dd5bef984939658af5b4236ba18e58d1f/vars/mavenCI.groovy#L60)
- `f8-p-l` locks `maven-failsafe-plugin` to an arbitrary version which might be different to what actual project assumes to be - [see here](https://github.com/fabric8io/fabric8-pipeline-library/blob/4b899c6dd5bef984939658af5b4236ba18e58d1f/vars/mavenIntegrationTest.groovy#L32)
- until this [PR](https://github.com/fabric8io/fabric8-pipeline-library/pull/381) is merged integration tests will be failing on PR builds for all the boosters. There is one other thing which needs to be fixed for boosters to make their tests pass, but this is not related to `f8-p-l`
- we tend to throw in project-specific functions to the library which don't belong there. I doubt this has any relevance or appeal for end-user. More on this [here](https://github.com/fabric8io/fabric8-pipeline-library/pull/378#issuecomment-365955435)

**Comment by bartoszmajsak** [comment]
Another interesting bit is that this library assumes that user has certain profile defined in his Maven build [[1](https://github.com/fabric8io/fabric8-pipeline-library/blob/de8d06de6f8019354b8983804e8db6d049ea654c/vars/canaryRelease.groovy#L16-L20)] [[2](https://github.com/fabric8io/fabric8-pipeline-library/blob/e2ad4f66a3185d678c58419bbc31a37af278ea66/vars/mavenCanaryRelease.groovy#L17)] [[3](https://github.com/fabric8io/fabric8-pipeline-library/blob/4127ec0adf20b4088601bbeff1b9a8cf29109520/vars/mavenCI.groovy#L32-L36)]. This is results in Maven WARNING, so not a big deal, but shows that the flow was done ad-hoc without thinking about implications.

**Comment by sthaha** [comment]
Closing this as this EPIC would be covered by the work on https://github.com/fabric8io/osio-pipeline
