### ISSUE TITLE
Scope out moving fabric8cd (http://jenkins.cd.test.fabric8.io/) out of GKE

### ISSUE THREAD

**Issue by pradeepto** [openshiftio/openshift.io#2246]
Moving fabric8cd from GKE to Badger will help a lot with costs. But more importantly, it will help the cause because of better hardware, more control for debugging etc.

The current system is setup using gofabric8 previously by James Rawlings. The team isn't aware of any manual configurations, if any. We need to evaluate how we deploy the new system.

- [ ] Figure what all will be needed to move the fabric8cd out of GKE and make sure there is functional parity
- [ ] We need to make sure it works for our current (Planner and UI teams) and future "tenants" a.k.a feature parity.
- [ ] We should make sure that we automate this process, so it can be repeated. Ansible, perhaps?

NOTE: @rupalibehera and @chmouel have access to GKE but they got that only recently when the previous maintainers were about to leave.

NOTE: There needs to be a window when both systems will have to run to test the new system thoroughly before we retire GKE

**Comment by pradeepto** [comment]
Related to https://github.com/openshiftio/openshift.io/issues/1902

**Comment by jaseemabid** [comment]
> The current system is setup using gofabric8 previously by James Rawlings. The team isn't aware of any manual configurations, if any. We need to evaluate how we deploy the new system.

@pradeepto Not sure about that. Its a Jenkins installed somehow and then maintained with folder backups. I'm sure we modified a ton of things through the UI, CLI and any other ways we could. So there is _only_ manual configurations and no scripts or automation here.

**Comment by pradeepto** [comment]
Closing this as duplicate in favour of https://github.com/openshiftio/openshift.io/issues/1902 as discussed with @maxandersen and @stevengutz .
