### ISSUE TITLE
[User-Story] Change Image base from Cent OS to RHEL

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#2259]
## User Story:
As Devtools developer, I will be to see stack analyses on a tab in manifest editor window.

## Description:
Currently the base image for most of the services provided by various teams in Devtools is Cent OS based. Completion of this user story would replace Cent OS images by RHEL for all the services.

## Acceptance Criteria:

- User will be able to build RHEL based images with full functionality as provided by Cent OS images.

## Task List:

- [ ] Identify the services which require this change.

- [ ] Get RHEL based VM.

- [ ] Change the base image and test it on VM

- [ ] Collaborate with respective teams to verify it's functionality

**Comment by joshuawilson** [comment]
please give it a `team` and `area` too

**Comment by GeetikaBatra** [comment]
Done
