### ISSUE TITLE
Backend API service Implementation for Dependency Editor 

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#2260]
#### User Story:

As an OSIO user, I will be able to make License Analysis optional in fabric8-backbone service for dependency editor, improved component search service, and create category search service.

#### Description:
Decoupling license service from stack_aggregator and recommender and make it optional because we already have separate license service. Creating API end-points for category search service and necessary modifications in component search service

#### Tasks:
- [x] Implement the logic for component search service so that we can get different packages based on keywords provided as input.
    - [x] Modification in graph database query.
- [x] Decoupling of license service and making license service optional for the POST dependency editor API call on the bases of the parameter passed to it. 
- [x]  Implementation of the logic for category search service and create a GET API endpoint.
