### ISSUE TITLE
Gathering categories data for spring, vertx, wildfly-swarm

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#2302]
#### User Story:

As an OSIO user, I will be able to get dependencies with categories based on mission and technology selected.

#### Description:
Collecting categories data from spring, vetx, wildfly-swarm and store it in graph database so that it can be used for categories search service in dependency editor.

#### Tasks:
- [x] Implement the logic for data collecting for spring and dumped it into JSON format.
- [x] Implement the logic for data collecting for vertx and dumped it into JSON format.
- [x] Implement the logic for data collecting for wildfly-swarm and dumped it into JSON format.
- [x] Insert the json dump into graph database.
