### ISSUE TITLE
Change kronos dockerfile and fix unit tests to complete the move of Kronos to Python3

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#2306]
## Description

In the Kronos service, we made sure that our codebase is compatible with Python3 with https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/45. However the `Dockerfile` has not been changed yet as the unit tests do not pass when using Python3. This is not due to some error in the code, rather a consequence of comparing two deep dicts using the Python `==` operator which relied on an implementation detail of `dict` in Python2.

## Acceptance Criteria

Kronos service should be running in production in a Python3 container.

## Task List

- [ ] Fix dictionary comparison in unit tests so they pass on Python3
- [ ] Modify the `Dockerfile` to install Python3 inside the container instead of Python2.
- [ ] Test that the service is working fine and there are no stability issues
- [ ] Retrain the model for `kronos-maven`
- [ ] Push to production

**Comment by abs51295** [comment]
@sivaavkd this can be again put in backlog for now. Revoking my assignment as of now. Thanks.
