### ISSUE TITLE
Pipeline Performances checklist

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#2314]
This is the epic task to improve the build pipeline : 

- [x] Remove any unwanted jenkins plugins #2347
- [ ] Get more insights inside the Jenkins builds #2245 
- [x] Jenkins moves plugins on every startup #2612
- [x] Jenkins slave should use a known good/local maven mirror #2457
- [x] ~~~Disable jenkins update of plugins on startup #2350~~~ 
- [x] Improve FMP performance loop https://github.com/fabric8io/fabric8-maven-plugin/issues/1208
- [X] ~~~Jenkins is configured to start builds only after a minute #2495~~~
- [x] Drop jenkins-mvn-local-repo PV from jenkins-slave #2368
- [x] ~~~Jenkins building app twice? #2340~~~
- [x] ~~~Precache maven dependencies in a tarball #2349~~~

see as well here for a my general task on OSIO #1570

**Comment by joshuawilson** [comment]
please set the type and team labels at a minimum

**Comment by jfchevrette** [comment]
Added: Drop jenkins-mvn-local-repo PV from jenkins-slave #2368

SD team believe this will result in the best gains for the least amount of work needed at the moment.

**Comment by kbsingh** [comment]
https://github.com/openshiftio/openshift.io/issues/2230 has impact from the work done here

**Comment by chmouel** [comment]
@hrishin I believe all the maven content caching performances improvement can be striked thought, since this could be achieved with a  global proxy.

**Comment by hrishin** [comment]
>   believe all the maven content caching performances improvement can be striked thought, since this could be achieved with a global proxy.

Second that :+1:

By the way, https://github.com/openshiftio/openshift.io/issues/2457 is showing significant improvement in build experience.

**Comment by jaseemabid** [comment]
Closed off (Jenkins starting after 1 min)

https://github.com/fabric8io/fabric8-build-team/issues/46 
https://github.com/openshiftio/openshift.io/issues/2495

**Comment by hrishin** [comment]
### Update

Closing: Jenkins slave should use a known good/local maven mirror
Issue #2457  is showing a significant reduction in build time.

**Comment by kbsingh** [comment]
does #2612 belong here ?
