### ISSUE TITLE
Exploring launcher backend APIs and it's workflow

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#2319]
## Description
The task here is to get familiar with launcher backend APIs and it's workflow. It will help in the code merge work in case if some APIs need to be modified or some new API need to be added to fit our use case. In this task our main aim is to find out the invocation point and condition for each API endpoint of out interest. Also we are getting familiar with the CI/CD process of launcher backend in production.

## Task List
- [x] Load the code of launcher backend and successfully run it without any error in the flow.  
- [x] List out all the API end points of our interest.
- [x] Find out the invocation points for each API end point.
- [x] Get familiar with the CI/CD process for launcher backend in production.
- [x] Prepare a [document](https://docs.google.com/presentation/d/1qByaeidXpZ6mgcMkZi0r436CjbpF8UOlR-jhUohW_gc) listing out all the findings for launcher backend.
