### ISSUE TITLE
OSIO Gemini server workflow implementation

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#2326]
## Description
This user story scopes the development work required for OSIO Gemini. The staging or production deployed Gemini API server shall provide an endpoint `/register` to register a new repository to the system that in turn will initiate an analytics scan on that and email a report with the security vulnerability status of all direct and transitive dependencies.

**Ecosystems To Be Supported:** Maven, Python, Node and Go.

## Task List
- [x] Finalize the API workflow
- [x] Develop Gemini API Server with `/register` endpoint. (Geetika, https://github.com/openshiftio/openshift.io/issues/2493). 
- [x] Define required worker flows to process a scan in the backend. (Aagam/Sam)
- [x] Develop a task to parse a registered Maven GitHub repository and identify all dependencies. (Aagam)
- [x] osioAnalysisFlow: Generalize dependency_tree task to support different ecosystems. (Aagam)
- [x] osioAnalysisFlow: Generalize unknown_deps_fetcher task to support different ecosystems. (Vasu,
https://github.com/openshiftio/openshift.io/issues/2494)
- [x] osioAnalysisFlow: Implement dependency parser for node ecosystem. (Aagam)
- [x] osioAnalysisFlow: Implement dependency parser for python ecosystem. (Aagam)
- [x] osioAnalysisFlow: Ingest unknown dependencies. (Vasu, https://github.com/openshiftio/openshift.io/issues/2494)
- [x] osioAnalysisFlow: report generation task to collate CVE for all dependencies. (Aagam)
- [x] osioAnalysisFlow: Implement dependency parser for go ecosystem (gopkg.lock support). (Aagam)
- [x] osioAnalysisFlow: Implement dependency parser for go ecosystem (glide-lock support). (Aagam)
- [ ] ~~osioAnalysisFlow: Support multiple manifest files of the same ecosystem (Aagam)~~
- [x] osioAnalysisFlow: Create a GitHub issue with scan report post report generation (Sam).
- [ ] ~~Create UX for report e-mail~~
- [x] Gemini Server: Develop `/report` endpoint to return report generation task output (Vasu,https://github.com/openshiftio/openshift.io/issues/2494)
- [ ] ~~Deploy Gemini API Server with `/register` endpoint on production. (Geetika, https://github.com/openshiftio/openshift.io/issues/2493)~~
- [ ] ~~osioAnalysisFlow: report generation task to call license service to retrieve stack license. (Geetika, https://github.com/openshiftio/openshift.io/issues/2493)~~
- [ ] ~~Deploy worker-api with osioAnalysisFlow on production. (Aagam)~~
- [ ] ~~osioAnalysisFlow: Identify and Configure an e-mail server.~~

Productize (Stretch for 147):
- [ ] Gemini Server: Develop `/scan` endpoint to initiate osioAnalysisFlow. (Aagam)
- [ ] Create a scheduled job to periodically run a scan on registered repositories.
- [ ] Gemini Server: Develop `/scanner-error` endpoint to report scanner level errors via e-mail.
- [ ] Gemini Server: Develop integration tests for Gemini server.
- [ ] osioAnalysisFlow: e-mail intended recipients via the configured mail server.
- [ ] Deploy Gemini service on the production cluster.
- [ ] Deploy worker API on the production cluster.

**Comment by GeetikaBatra** [comment]
Associated user story https://github.com/openshiftio/openshift.io/issues/2493

**Comment by maxandersen** [comment]
We have email notifications setup and api in platform this should use. Not sure if notifications api fits to this yet but we’ve gone through all the mail setup thus should be best to use that.

**Comment by samuzzal-choudhury** [comment]
Sprint 147 user story for Epic https://github.com/openshiftio/openshift.io/issues/2774

**Comment by sivaavkd** [comment]
@abs51295 Can you close this and create a new story for 148 ? I believe the stretch items mentioned in this story will become the items for 148. cc @samuzzal-choudhury

**Comment by miteshvp** [comment]
Closing in favor of https://github.com/openshiftio/openshift.io/issues/3167
