### ISSUE TITLE
Analytics Documentation updates

### ISSUE THREAD

**Issue by sivaavkd** [openshiftio/openshift.io#2327]
We want to update the documentation for Fabric8 Analytics repos so that contributors can onboard quickly.  We identified some updates needed in the documentation while new team members are being onboard and there is some work done in this area.

This epic is to list down, track and fix all the documentation updates.

**Comment by Preeticp** [comment]
Tasks identified for the Analytics Repo work:
- [ ] List all the repos under Analytics with links.
- [ ] Create a workflow (Marek).
- [ ] Analyze them, filter, modify, or deprecate as required.
- [ ] Use Marek's dashboard for creating a better on-boarding experience.

Tasks for Getting Started guide and User guide:
- [x] Update Getting Started as per latest UX, content and screenshots. (Done by Misha)
- [ ] Update User Guide as per latest UX, content and screenshots.
