### ISSUE TITLE
Service to detect under what license a project is distributed

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#2376]
#### User Story:

As an OSIO user, I will be able to get my license from license file.

#### Description:
License extractor scans the LICENSE files and compare the contents with known license synonyms and detects the license for the project

#### Tasks:
- [x] Implement the logic for license extractor service.
- [x] Make the necessary changes in core API server for license service.
- [x] Make the necessary changes in backbone server for license extract service.
