### ISSUE TITLE
Task list for Getting started [ngx-launcher]

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#2377]
> Quickstart Flow

##### API (Runtimes) `/booster-catalog/runtimes`
- [x] - Description is not coming as part of API response
- [x] - Missing/invalid Auth bearer token should respond with status code 401 (https://github.com/fabric8-launcher/launcher-backend/issues/122)
- [x] - API changes to handle UX changes (https://github.com/fabric8-launcher/launcher-planning/issues/121)
- [x] - Filter Node, Fuse from Runtimes

##### API (Missions) `/booster-catalog/missions`
- [x] - Description is not coming as part of API response
- [x] - Missing/invalid Auth bearer token should respond with status code 401
- [x] - API changes to handle UX changes (https://github.com/fabric8-launcher/launcher-planning/issues/120)
- [x] - Filter secured, crud, circuit-breaker

##### API (Pipelines) `/services/jenkins/pipelines`
- [x] - Missing/invalid Auth bearer token should respond with status code 401
- [x] - API changes required to handle UX changes (https://github.com/fabric8-launcher/launcher-planning/issues/122)
- [x] - All pipelines has suggested flag.

##### API (Git) 
- [x] - Missing/invalid Auth bearer token should respond with status code 401
- [x] - Get user info : `/services/git/user`
    - [x] - needed endpoint to get user avatar url, gitHub id other meta info. (https://github.com/fabric8-launcher/launcher-planning/issues/112)
    - [x] - Auth bearer token should be able to get response instead of depending on (x-git-token)
- [x] - Get user organisation info :  `/services/git/organizations `
    - [x] - Auth bearer token should be able to get response instead of depending on (x-git-token)
    - [x] - Improper response for /organizations.In case of no Organisation for user , default organisation should be there (https://github.com/fabric8-launcher/launcher-planning/issues/127)
- [x] - Get user organisation repo info :  `/services/git/repositories `
    - [x] - Auth bearer token should be able to get the response instead of depending on (x-git-token)
- [x] - Passing Authorization bearer token here but not X-git-token it gives 401 (https://github.com/fabric8-launcher/launcher-planning/issues/117)
- [x] - Changing Organisation label to Location
- [x] - GitHub login shouldn't be there for the logged in user

##### API (Launch) `/osio/launch`
 - [x] - Validation/default value of project name, groupId, artifactId at client side
 - [x] - Space name should be non editable in Summary screen
 - [x] - Space Id needs to sent from UI instead of space path as per recent API changes [Priority1]
 - [x] - Missing/invalid Auth bearer token should respond with status code 401
 - [x] - Description overflow in Summary screen **[Priority1]**
 - [x] - Codebases not getting created **[Priority 1]**
 - [x] - Do not see pipelines getting triggered from the /osio/launch end point call
           https://github.com/fabric8-launcher/launcher-planning/issues/139
 - [x] - Description for runtimes should be updated for summary screen
           https://github.com/fabric8-launcher/launcher-planning/issues/147 

##### API (Status/Web socket)
- [x] - **UXD**
          Don't have placeholders in html page to show the error messages from the web socket call in the 
          progress page
          https://github.com/fabric8-launcher/launcher-planning/issues/125
- [x] - Error handling as per UXD for Progress Screen
- [x] - Getting the error response as `Unauthorized` from the web socket call response.
           https://github.com/fabric8-launcher/launcher-planning/issues/123
- [x] - Events are not sent to the UI
          https://github.com/fabric8-launcher/launcher-backend/issues/139
- [x] - Messages are long. It should be shorter and relevant to the user.
- [x] - https://github.com/fabric8-launcher/launcher-planning/issues/130
- [x] - https://github.com/fabric8-launcher/launcher-planning/issues/131
- [x] - https://github.com/fabric8-launcher/launcher-planning/issues/132
- [ ] - https://github.com/fabric8-launcher/launcher-planning/issues/150

> Import Flow
##### Step 1 : Import GIT Repo
- [x] - UXD is in progress
- [x] - Layout Changes for GitHub  provider screen **[Priority 1]**
- [x] - Changing Organisation label to Location **[Priority 1]**
- [x] - gitHub login shouldn't be there for the logged in user

##### Step 2: Release strategy
- [x] - Release strategy shouldn't be optional as per new UXD **[Priority 1]**

##### Step 3: Import Application
- [x] - https://github.com/fabric8-launcher/launcher-planning/issues/135
- [ ] - https://github.com/fabric8-launcher/launcher-planning/issues/138
- [x] - Do not see pipelines getting triggered from the /osio/import end point call
           https://github.com/fabric8-launcher/launcher-planning/issues/139
- [x] - Do not see the codebase getting created in the OSIO dashboard from the `/osio/import` end point call https://github.com/fabric8-launcher/launcher-planning/issues/140

> Integration Getting Started into OSIO
- [x] - Identify the flow for Getting started in OSIO
- [x] - Integrating as per the flow
- [x] - Integrate with Space creation api **[Priority 1]**
- [ ] - Validation/error handling for space name 
- [x] - Change of overlay screen as per latest UXD
- [ ] - OSIO Launcher require few configurable options at Pipelines screen https://github.com/openshiftio/openshift.io/issues/2894
- [ ] - Build failing for wildfly-healthcheck **[Priority1]** 
https://github.com/fabric8-launcher/launcher-booster-catalog/issues/189 https://github.com/openshiftio/openshift.io/issues/2152
- [x] - New Configmaps has to be introduced in UI
- [ ] - Stage/Prod link doesn't appear in pipelines screen **[Priority1]** https://github.com/openshiftio/openshift.io/issues/2920
https://github.com/openshiftio/openshift.io/issues/3003
- [ ] - Sockets to be replaced with working solution https://github.com/fabric8-launcher/launcher-planning/issues/148
- [x] - CI/CD for ngx-forge **[Priority1]**
           https://github.com/openshiftio/openshift.io/issues/2945
- [ ] - Semantic release for ngx-forge **[Priority1]**

> Tasks based on Feedback
- [x] - Alignments of the mission and runtime text has to be centered vertically with respect to the drop down. - https://github.com/openshiftio/openshift.io/issues/2934
- [x] - Text has to be horizontally centered in Select Pipeline screen - https://github.com/openshiftio/openshift.io/issues/2935
- [x] - Empty spaces in the application summary page has to be taken care - https://github.com/openshiftio/openshift.io/issues/2936
- [x] - Consider changing the dropdown as the values are expected to be singular. - https://github.com/openshiftio/openshift.io/issues/2937

> Dependency Editor Step
- [ ] - Implementation of logic to modify the pom.xml in prod.[Priority1]
- [x] - Insert data in prod for categories endpoint.
- [ ] - End points to point to prod URL on UI side.[Priority1]
- [x] - License Piece should be integrated with the api.[Priority1]
- [ ] - Add jobs for data scraping from srping, vertx, wildfly-swarm.
- [ ] - Integration discussion for Dep Editor as internal feature.
- [x] - UX has to be in sync as per new UXD [Priority1]
- [x] - Handling UI layout post integrting with Launcher [Priority1]
- [x] - Issues with AOT compilation [Priority1]
- [x] - Unit test cases

Non functional tasks of dependency editor
- [ ] - Semantic Release
- [ ] - CICD
- [ ] - Integration Tests

**Comment by invincibleJai** [comment]
> Messages are long. It should be shorter and relevant to the user.
          https://github.com/fabric8io/kubernetes-client/issues/1019

We need to have a validation in client side for the project name. This should resolve it.

**Comment by arunkumars08** [comment]
Added a few issues as per Stevan's suggestions.

**Comment by animuk** [comment]
We dont update this tasklist for the new sprint. If required, we will make a new one. closing this
