### ISSUE TITLE
[20] (Deployments) Show deployment status events in real time 

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2380]
Parent: #287

# Description

As a user of OSIO's web application, I want to be able to see my deployment information update in real time.

# Notes

The Deployments API currently supports HTTP requests. This requires data to be polled for updates. The network usage for this is inefficient and the user experience on the page suffers because data cannot be updated 'live'.

For example, as a pod scales, it goes through a series of states that end at 'Running'. The UI is able to show these states with transitions, but because the data for this comes from polling, intermediate states are skipped if the polling request doesn't occur at the right time. With a websocket connection, this issue would be resolved.

Not all API endpoints need websocket support. The Deployments API should be updated to support websocket connections where appropriate so updates are written to consumers when available.

# Acceptance Criteria

- [ ] When I scale a pod up or down, I should see the states that it is going through 'live'
- [ ]  When someone else scales a pod up or down, I should see the states that it is going through 'live'
- [ ] When an event occurs regarding a deployment, I should be notified of the event

# Tasks

- [ ] #2528: API: Provide websocket support
- [ ] #2529: UI: Use websocket API for data

**Comment by andrewazores** [comment]
During the Platform weekly meeting today this was brought up and we discussed alternative approaches.

The first alternative is the possibility of simply polling faster, with the assumption that a GET every few seconds should not really be all that heavy of a load, and is perhaps preferable to a Websocket that is always held open. This requires no backend support, is a one-liner change on the front end, and would have consistent performance for both Deployments page scale requests and external scaling events from the OSO console or oc cli.

A rebuttal to the resources used by holding open a Websocket while the user is on that page is the possibility of opening a Websocket on scaling request, using the socket to do live updates of pod statuses, and then closing the socket when the pods' statuses have settled and the transitions are complete; the downside to this approach is that external pod scaling would not see smooth transition animations as no Websocket connection is present.

The last alternative is that on scaling request, the polling rate should be temporarily increased, say from the default 1/minute to say 30/minute poll cycles, until the pod statuses settle or a maximum period has elapsed. This avoids a Websocket connection being held open, or any Websocket connection at all (meaning no support from the backend required), and can provide relatively smooth pod status transitions while scaling occurs. The downsides are that this will likely not be as smooth or as real-time as a Websocket connection, and also will not see smooth transitions for external scaling from OSO console or oc cli.

I believe @jiekang is working on a Websockets prototype, and I am working on a prototype for "variable poll timing" (the last alternative).

**Comment by jiekang** [comment]
Moving out of train and back into backlog. This should be aligned with UX designs around notifying users.

cc @catrobson 

Michael gave us initial designs https://redhat.invisionapp.com/share/BHGPNUXCR9A 

I think it's still a WIP.

**Comment by jiekang** [comment]
@openshiftio/uxd-team

Could someone take a look at the designs given to us @ https://redhat.invisionapp.com/share/BHGPNUXCR9A

Were these reviewed or finalized in any way? Is this something that we want developers to work on? The backend support for some of the information required for these designs exists now.

**Comment by mceledonia** [comment]
@jiekang @catrobson 

I may be wrong but I believe the warning overlays and pod scaling disabled tooltip were the only "finalized" designs there. The tooltips are conceptually correct but the icons and language used on them are incorrect. The resource usage drawer was not reviewed by dev but seemed to be getting good feedback from design, so that certainly would be worth discussing and deciding on moving forward.
