### ISSUE TITLE
[13] Integration Test Suite for Booster support

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#2399]
### Description
As an OSIO Tester, I would like to increase UI Test coverage in support of all the boosters.

The boosters to be covered are:
* HTTP:  Vertx, Springboot, WildflySwarm
* HealthCheck: Vertx, Springboot, WildflySwarm
* ConfigMap: Vertx, Springboot, WildflySwarm

#### Acceptance Criteria
Integration Tests (to exercise the Boosters running in the context of OSIO) should increase the overall coverage w.r.t boosters that a normal OSIO users perform.

#### Modularize the Test Structure as Single Test Suites
One difficulty in testing Boosters in OSIO is that each test must perform significant setup tasks such as the creation of a space and quickstart before a test can be run. The current e2e tests perform these tasks once for each test. This results in each test requiring several minutes to execute, and has each test return a single pass/fail result value. 

For the Booster tests, we propose a different approach. While the Booster tests will exercise OSIO through its UI (as is the case with the e2e tests), the Booster tests will be organized in the following manner:

The tests will be divided into test suites. Each test will be include multiple tests.
The first test to be executed will perform all the set up steps required by the test suite.
The remaining tests will be structured as atomic units that can be run in any order. 
At the conclusion of the test suite, any resources created by the tests will be deleted.

#### Actions to be performed by the tests
- [x] Login
  - all test cases
- [x] Create a workspace
  - [x] https://github.com/openshiftio/openshift.io/issues/2568 Setup
- [ ] Add to space by selecting Import a Github Repo option
  - [ ] https://github.com/openshiftio/openshift.io/issues/2829 Import a Github repo
- [x] Create a new application using the new launcher wizard
  - [x] https://github.com/openshiftio/openshift.io/issues/2568 Setup 
- [x] Select Github Repo to import into
  - [x] https://github.com/openshiftio/openshift.io/issues/2568 Setup
- [x] Select the Pipelines
  - [x] https://github.com/openshiftio/openshift.io/issues/2571 Pipeline
  - [ ] https://github.com/openshiftio/openshift.io/issues/2829 Import a Github repo
  - [x] https://github.com/openshiftio/openshift.io/issues/2573 Check for Stack/Analytic reports
- [ ] Triggers the CD Build (Jenkins)
  - [ ] https://github.com/openshiftio/openshift.io/issues/2572 Triggers the CD Build (Jenkins)
- [ ] Check for Build success
  - [x] https://github.com/openshiftio/openshift.io/issues/2571 Pipeline
  - [ ] https://github.com/openshiftio/openshift.io/issues/2829 Import a Github repo
- [x] Verify deployment to stage and run, verify that ends can be reached
  - [x] https://github.com/openshiftio/openshift.io/issues/2571 Pipeline
  - [ ] https://github.com/openshiftio/openshift.io/issues/2829 Import a Github repo
- [ ] Make change to app, create PR, verify changes are deployed to run and stage #2505
  - [ ] https://github.com/openshiftio/openshift.io/issues/2572 Triggers the CD Build (Jenkins)
- [x] Check for Stack reports
  - [x] https://github.com/openshiftio/openshift.io/issues/2573 Check for Stack/Analytic reports
- [x] Open Openshift Console from OSIO
  - [x] https://github.com/openshiftio/openshift.io/issues/2570 Access project in OSO
- [x] Copy Login Command (under username right hand side)
  - [x] https://github.com/openshiftio/openshift.io/issues/2570 Access project in OSO
- [x] Open Che workspace
  - [x] https://github.com/openshiftio/openshift.io/issues/2568 Setup
  - [x] https://github.com/openshiftio/openshift.io/issues/2570 Access project in OSO
  - [x] https://github.com/openshiftio/openshift.io/issues/2574 Build the project using Maven in the Che terminal window
  - [x] https://github.com/openshiftio/openshift.io/issues/2575 Verify that the preview URL provided in the Che terminal is correct and can be accessed
  - [x] https://github.com/openshiftio/openshift.io/issues/2577 Run the project from the Che menu
  - [x] https://github.com/openshiftio/openshift.io/issues/2578 Debug the project from the Che menu
  - [x] https://github.com/openshiftio/openshift.io/issues/2579 Run the project's Junit tests from the Che menu
  - [x] https://github.com/openshiftio/openshift.io/issues/2580 Modify the project source code in Che - verify rebuild, redeploy
- [x] Check the success of importing github contents by opening a manifest file (pom.xml)
  - [x] https://github.com/openshiftio/openshift.io/issues/2570 Access project in OSO
- [x] Paste login command copied in step(j) inside of che terminal to login to Openshift
  - [x] https://github.com/openshiftio/openshift.io/issues/2570 Access project in OSO
- [x] Switch to user namespace by doing oc project <user-name-space> command
  - [x] https://github.com/openshiftio/openshift.io/issues/2570 Access project in OSO
- [x] Build the project using mvn clean install -Popenshift in the Che terminal window
  - [x] https://github.com/openshiftio/openshift.io/issues/2574 Build the project using Maven in the Che terminal window
- [x] Verify that the preview URL provided in the Che terminal is correct and can be accessed
  - [ ] https://github.com/openshiftio/openshift.io/issues/2575 Verify that the preview URL provided in the Che terminal is correct and can be accessed
  - [x] https://github.com/openshiftio/openshift.io/issues/2580 Modify the project source code in Che - verify rebuild, redeploy
  - [x] https://github.com/openshiftio/openshift.io/issues/2577 Run the project from the Che menu
- [x] Run the project from the Che menu
  - [x] https://github.com/openshiftio/openshift.io/issues/2577 Run the project from the Che menu
- [x] Debug the project from the Che menu
  - [x] https://github.com/openshiftio/openshift.io/issues/2578 Debug the project from the Che menu
- [x] Run JUnit tests from the Che menu
  - [x] https://github.com/openshiftio/openshift.io/issues/2579 Run the project's Junit tests from the Che menu
- [x] Modify the project source code in Che - verify rebuild, redeploy
  - [x] https://github.com/openshiftio/openshift.io/issues/2580 Modify the project source code in Che - verify rebuild, redeploy
- [ ] Commit and push the project source code to git repo - verify rebuild, redeploy
  - [ ] https://github.com/openshiftio/openshift.io/issues/2580 Modify the project source code in Che - verify rebuild, redeploy
- [x] Deletion or Reset Environment
  - [x] https://github.com/openshiftio/openshift.io/issues/2568 Setup
  - [x] https://github.com/openshiftio/openshift.io/issues/2581 Clean up
- [x] Logout
  - All test cases

#### Test Code Repo
Booster tests will be managed in the ee_test directory of this repo: https://github.com/fabric8io/fabric8-test/tree/master/ee_tests - and will leverage/extend the EE test framework.

#### Pull Requests
* POC test for Junit tests in Che - https://github.com/fabric8io/fabric8-test/pull/509
* POC test for running Maven build in Che - https://github.com/fabric8io/fabric8-test/pull/463
* POC tets for Che editor in OSIO - https://github.com/fabric8io/fabric8-test/pull/513
* Test for the new launcher UI:
   - https://github.com/fabric8io/fabric8-test/pull/522
   - https://github.com/fabric8io/fabric8-test/pull/562
* Integration Test Suite for Boosters - https://github.com/fabric8io/fabric8-test/pull/527
* Configure new Booster E2E tests to run daily on Centos CI - https://github.com/fabric8io/fabric8-test/issues/552

**Comment by ldimaggi** [comment]
Test to create a new Che workspace is running now:
https://ci.centos.org/view/Devtools/job/devtools-test-e2e-openshift.io-chetest-cluster-one/

**Comment by ldimaggi** [comment]
Test to run mvn build command in Che / OSIO - https://github.com/fabric8io/fabric8-test/pull/463

**Comment by miteshvp** [comment]
@ldimaggi - I have edited this issue to consider modularized test suites as discussed in our last meeting. Please let me know if there are any missing links or pieces to be added

**Comment by ldimaggi** [comment]
Test to run junit tests in Che for booster - https://github.com/fabric8io/fabric8-test/pull/509

**Comment by ldimaggi** [comment]
My thinking for the structure of the tests follows - and, by the way, I think that we should start to consider and refer to these tests not as E2E tests but as Booster-OSIO tests as the primary goal of the tests is to verify the operation of the Boosters in the context of OSIO. 

Each Booster will be verified by the same basis set of tests. We may additionally create Booster-specific tests as needed. 

The tests should be organized into test suites. The first case test in each suite will perform setup tasks and the final case test will perform tear down tasks. The remaining test cases will be structured such that they can be run in any combination and that any subset of the tests can be run.

Each test case will start with the test acocunt logging into OSIO and end with the test account logging out. Each test suite run will utilize a single OSIO userspace and Che workspace, both of which will be created during the test setup. We can use the same space and Che workspace name for each test suite execution as the workspace and space will be deleted as part of the test teardown. 

For the short term (sprint 146) the starting point for the execution of the tests will be after the Boosters have been installed into the test user account. Longer term, the tests will install the Boosters by using the new launcher. 

Test case: Setup
Steps: Login, reset the user environment, create a new boosters, space, Che workspace, logout.

Test case: Access project in OSO
Steps: Login, then:
 Open Openshift Console from OSIO
 Copy Login Command (under username right hand side)
 Open Che workspace
 Check the success of importing github contents by opening a manifest file (pom.xml)
 Paste login command copied in step(j) inside of che terminal to login to Openshift
 Switch to user namespace by doing oc project command
 Logout

Test case: Pipeline
Steps: Login, verify the completion of the build pipeline and deployment to stage and run. Verify successful operation of deployed booster at stage and run endpoints., logout.

Test case: Triggers the CD Build (Jenkins), 
 Commit and push the project source code to git repo - verify rebuild, redeploy
Steps: Login, modify source code, create PR, verify redeployment to stage and run, verify changes are deployed, logout.

Test case: Check for Stack/Analytic reports
Steps: Login, verify that build completion creates stack report, verify report contents by compariing to expected results, logout.

Test case: Build the project using mvn clean install -Popenshift in the Che terminal window
Steps: Login, open Che workspace, execute mvn clean install command in Che terminal window, logout.

Test case: Verify that the preview URL provided in the Che terminal is correct and can be accessed
Login, open Che workspace, execute mvn clean install command in Che terminal window, verify URL generated endpoint is reachable and that the deployed Booster functions correctly, logout.

Test case: Run the project from the Che menu 
Steps: Login, open Che workspace, run the Booster from the Che run menu, verify results, logout.

Test case: Debug the project from the Che menu 
Steps: Login, open Che workspace, debug the Booster from the Che run menu, verify results, logout.

Test case: Run the project's Junit tests from the Che menu 
Steps: Login, open Che workspace, run the Booster Junit tests from the Che run menu, verify results, logout.

Test case: Modify the project source code in Che - verify rebuild, redeploy
Steps: Login, open Che workspace, edit source code, verify rebuild and redeploy, verify redeployment to stage and run, verify changes are deployed, logout.

Test case: Teardown
Steps: Login, reset user environment, verify environment is cleaned, logout.

**Comment by ppitonak** [comment]
1. As you wrote in your description, Setup and Teardown are not test cases but setup/tear down tasks.
2. It's unnecessary to list login and logout  in every test case, see ^
3. What I'm missing most is the fact that these type of tests should not depend on production environment. We should think about how to test booster+one OSIO component outside of prod/prod-preview environment.

**Comment by pmacik** [comment]
@ppitonak That (3) would be very tricky since OSIO is an integration of many components KC, RHD, Auth etc. Our goal is to test the integration of boosters into OSIO. In order to test it all outside prod/prod-preview one would need to re-create the whole setup (and/or mock some components) which would be impractical.
@ldimaggi WDYT?

**Comment by sunilk747** [comment]
IMO it would be better to create userspace for a booster once and use it for further testing. Creating userspace for each test would be time taking and kind of redundant. 
@ldimaggi @pmacik What are your opinions on this.

**Comment by pmacik** [comment]
@sunilk747 Creating a userspace is not done for each test. It is done just once for the whole suite in the "Test case: Setup" and re-used for the rest of the tests.

**Comment by hrishin** [comment]
refer #2809

**Comment by ldimaggi** [comment]
See: https://github.com/openshiftio/openshift.io/issues/3566
