### ISSUE TITLE
Task list for Standalone Dependency Editor

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#2431]
### Standalones
- [ ] UI - Update the UI with respect to latest UXD - Sanket #2489, #2518, #2513  
- [ ] UI - Check License card UI logic if we refresh the list on every call - Sanket
- [x] UI - handle the repetitive licenses -  Sanket
- [x] UI - License donut % text - Sanket
- [x] UI - Show cve flag in each deps in browse dependency - Sanket/Jyasveer
- [ ] UI/API - /depeditor-analyses , /depeditor-cve-analyses, are not able to give responses if hit more 
       than once - Ravindra
- [x] UI - License analyses call should be async from the UI - Sanket
- [ ] UI - Test the alternate insights flow - Sanket
- [ ] UI - Integrate Get all dependency list API for the browse dependency modal screen - Sanket
- [ ] API - License data response form api to handle the repetitive licenses - Sunil( #2428)
- [x] API - Get all dependency list for the browse dependency modal screen - Ravindra

**Comment by sanketpathak** [comment]
This is redundant task list. So closing it. Refer here for dependency editor task list #2377
