### ISSUE TITLE
Sprint plan for Fabric8 Analytics: #146

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2433]
**IMPROVE current Insights for WF Swam based boosters**  

- [x] #2090

**Ingest RHAT specific downstream dependencies present at OSIO boosters** #2282
- [x] [Identify changes needed for supporting 3rd party package repositories](https://github.com/openshiftio/openshift.io/issues/2481) [5]

***Insights for Node ecosystem***

- [ ] [13] Productionizing Deep learning models [Get model training to run on EMR)  #2467 (part of #2434)

**Scale the platform to support 500 concurrent users** 
- [x] Extend the current test results for 500 concurrent users to include mixed traffic 
       (New Stack analysis initiation, Retrieval of stack report, LSP calls) #2491 (Part of #1144)
- [x] Work with SD team to get necessary resources
- [ ] Promote changes to OSIO

**Complete OSIO Gemini related activities related to Fabric8 Analytics integration** #2326
- [ ] https://github.com/openshiftio/openshift.io/issues/2494 [13]
- [ ] https://github.com/openshiftio/openshift.io/issues/2493 [13]
- [ ] https://github.com/openshiftio/openshift.io/issues/2496 [8]

**Map CVEs for the Maven, Node ecosystems**
- [x] Continue the current manual mapping from NVDB to individual packages [1]
- [ ] Continue POC for automating CPEs to individual dependencies #2106 
- [x] [Find a way how to get project name from NVD CVE data](https://github.com/openshiftio/openshift.io/issues/2485) [8]
- [ ] [Clean up Maven CVE false positives in graph database](https://github.com/openshiftio/openshift.io/issues/2480) [5]

***Close known SEV-2 bugs***
- [ ] #2335
- [ ] #2328
- [ ] #2313
- [ ] #2272
- [ ] [No such bucket error encountered](https://github.com/openshiftio/openshift.io/issues/2219) [3]
- [ ] [psycopg2.IntegrityError](https://github.com/openshiftio/openshift.io/issues/2218)
- [ ] [Different 'label' values are stored in the Graph database for package versions data](https://github.com/openshiftio/openshift.io/issues/1934) 
- [ ] #843
- [ ] #833
- [ ] #814

**Improve service side for better handle on service deployment**
- [ ] [Resilient infra for services of Analytics platform](https://github.com/openshiftio/openshift.io/issues/1084)
- [ ] [Use jobs service as a gateway for communicating with data-importer](https://github.com/openshiftio/openshift.io/issues/2484)
- [x] [Integrate data-importer with Sentry](https://github.com/openshiftio/openshift.io/issues/2483)  [3]
- [x] [Integrate f8a jobs service with Sentry](https://github.com/openshiftio/openshift.io/issues/2482)  [3]

**Data ingestion, sanity related activities**
- [x] [Scale the transfer of packages to graph database](https://github.com/openshiftio/openshift.io/issues/2315)  [5]
- [x] All the known Maven, Node dependencies are present at Graph
- [ ] Ingest Node components which have keywords and GitHub topics
- [ ] [Gradle support in f8a-worker](https://github.com/openshiftio/openshift.io/issues/1897)

**Quality**
- [x] #1635 [5] Implement Referential Integrity (RI) tests for the data stored in S3 database
- [ ] #1636 [5] Implement Referential Integrity (RI) tests for the data stored in graph database
- [ ] #2256
- [x] #2454 [2] RFE: Improve code quality in the following repository: fabric8-gemini-server
- [x] #1227 [1] RFE: Improve code quality in the following repository: fabric8-analytics-worker
- [x] #1089 [3] Configure Pydocstyle in all relevant fabric8-analytics repositories
- [ ] #1077 [4]
- [x] #1744 [3] Provide unit tests for the sources from repository fabric8-analytics-tagger
- [x] #2497 [1] Improve QA Dashboard to support list of files that are ignored by pylinter or pydocstyle checker
- [x] #2750 [1] Implement a tool to display code coverage weekly status
