### ISSUE TITLE
Sprint plan for OSIO Getting started experience : #146

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2440]
**Getting Started Experience**

- [x] Close all the open work items related to backend API, Integration #2377
- [ ] Get UI implementation closer to match the latest, baselined UX
- [x] Integrate Launcher component into OSIO Fabric8 UI
- [ ] Functional tests are in place for the end to end Launcher components
- [ ] CICD, Semantic release has to be implemented
- [x] Completely functional Launcher is available at prod-preview for testing 

**Dependency Editor**

- [ ] Dependency Editor: Close out TODO list #2492  

- [ ] Completely working Dependency editor is integrated into Launcher, enabled with feature flag

**Make the boosters work at OSIO user flow**
- [ ] End to end tests for the new Launcher available at prod-preview #2217
- [ ] Test Suite for booster support #2399

**Scale Launcher to support 500 concurrent users** 

- [x]  #2439

#### Associated User stories (Getting Started flow):
- [x] - Mission & Runtimes - https://github.com/openshiftio/openshift.io/issues/2507
- [x] - Target Environment - https://github.com/openshiftio/openshift.io/issues/2509
- [x] - Pipelines - https://github.com/openshiftio/openshift.io/issues/2510
- [x] - Git Provider - https://github.com/openshiftio/openshift.io/issues/2514
- [x] - Summary - https://github.com/openshiftio/openshift.io/issues/2511
- [x] - Progress - https://github.com/openshiftio/openshift.io/issues/2515
- [ ] - Integration Tests - https://github.com/openshiftio/openshift.io/issues/2517
- [ ] - CICD and Semantic Release - https://github.com/openshiftio/openshift.io/issues/2516
