### ISSUE TITLE
[13] Get the deep learning model to train on EMR through data collected from core

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#2467]
## User Story

As a fabric8-analytics user I should be able to get stack analyses results for the NPM ecosystem.

## Acceptance Criteria

- [x] The deep learning model should be able to train on EMR.

## Epic (Feature)

Part of the work being done towards #2434.

## Description

Extending our work from the previous issues #2264, #2002 and #2004 we have finalized on using the CVAE approach to get to a hybrid recommendation system for NPM to serve companion recommendations (stack analyses). Now that we have the POC and its results in place we need to get it into production, which the feature #2434 talks about. Find all relevant info [in this gdoc](https://docs.google.com/document/d/1LTAJRq60lNs-fDGsZLkLS0r8E8j5zDxK_7zkXJqLRxM/edit#). 

## Task List

- [x] Setup of EMR cluster with a custom deep learning AMI (#2487)
- [x] Get some sample Tensorflow code to work on EMR
- [x] Code changes to CVAE model to get it to train on EMR
- [x] Code changes to denoising autoencoder model to get pretraining to work on EMR
- [x] Ingest the data for all the relevant packages through the jobs api (/cc @msrb)
- [x] Collect the manifest files (`package.json`) for training made from a combination of these packages, from Github and the stacks of the packages. (/cc @msrb)
- [x] Write the swagger spec for the API
- [x] Ingestion of version information into the graph (/cc @miteshvp @msrb)
- [x] Changes to scoring module to accommodate new users (brand new combination)
- [x] Openshift template for the scoring module
- [x] Load testing the endpoint for this service standalone to figure out resource requirements (#2708)
##### STRETCH GOALS
- [ ] Write the pre-processing pipeline to aggregate and clean the data collected through the jobs API.
- [ ] Unit tests for the training/scoring logic [initial setup and sanity]
- [ ] Creation of CI/CD pipeline for the new repository
- [ ] Get the CI/CD job integrated into [openshiftio-cico-jobs](https://github.com/openshiftio/openshiftio-cico-jobs).
- [ ] Coordinate with service delivery to create a new "kronos" pod for this service on staging
- [ ] Make required changes to `fabric8-analytics-server` if any, required to integrate the service with the recommender API
- [ ] Get the end to end piece to work through the IDE extensions
- [ ] Write the e2e functional tests (API level only) for the recommender API with this service integrated.
- [ ] Ingestion of the EPV's coming in from the collected manifests.

**Comment by rootAvish** [comment]
Tracked in https://github.com/fabric8-analytics/fabric8-analytics-npm-insights/pull/1, demo was published on mailing list yesterday.
