### ISSUE TITLE
[8] Scale analytics platform to support 500 concurrent requests

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#2491]
## User Story
As a fabric8-analytics developer, I would like to figure out the analytics resource requirements so that the system supports 500 concurrent mixed API traffic within a minute.

## Epic
Part of the work done for #1144 

## Description
In this sprint, we plan to scale the analytics system to support 500 mixed requests within a minute which will include 'x' number of `/stack-analyses` POST requests without any cache involved in the kronos-maven, 'y' number of `stack-analyses` GET requests and 'z' number of `component-analyses` GET requests. The results are going to be published to the service delivery team and a communication will be initiated with that team to have the required resource on the production cluster.

## Task List
- [x] Develop a client script to simulate the mixed traffic.
- [x] Scale the dev cluster resources to support concurrent mixed traffic of 500 requests in a minute.
- [x] Publish the results in the [Scaling F8 Analytics with Mixed traffic](https://docs.google.com/spreadsheets/d/1xfc_gxPdp-sNkw3gNqe4KLC2wN_IQC1B11NFxIiWc2w/edit).
- [ ] Open a housekeeping issue for the service delivery team to assess the availability of required resources on production.
