### ISSUE TITLE
Task list for Integrating Dependency Editor with Launcher

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#2492]
### Integration with Launcher
- [x] Complete standalone work items https://github.com/openshiftio/openshift.io/issues/2431
- [ ] UI - Work on the styles to integrate it well with the launcher flow - Jyasveer
- [x] UI - do a Post call on load - Jyasveer
- [x] UI - Pass mission, runtime, github url to the dep editor component from the launcher component - 
       Arun/Jai
- [x] UI - Accept Input parameters in the dependency editor component :- github url, mission, runtime, 
       etc - Jyasveer
- [ ] UI - Send the added dependencies to the launcher component from the dep editor component - 
       Jyasveer
- [ ] UI - Get the added dependencies from the dep editor to the launcher component - Jyasveer
- [ ] UI - Pass the added dependencies (list of E,P,V) to the /osio/launch in the launcher UI - Jyasveer
- [ ] API - Modify /osio/launch api end point where it accepts list of (E,P,V) and modifies the pom.xml 
       with the new dependencies - Sunil/Anindya
- [x] API - Integrate the github utility with the post call in core api server - Ravindra

**Comment by joshuawilson** [comment]
I'm not sure this is really a `papercut`. @qodfathr can you please clarify?

**Comment by sanketpathak** [comment]
The tasks for integrating dependency editor  is present in master task list #2377 . This is redundant so closing it
