### ISSUE TITLE
[13] OSIO Gemini server tasks

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#2493]
## User Story
As a fabric8-analytics gemini user, I would like to consume use the register endpoint which will help me scan my github repo.

## Description
In this sprint, we plan to develop and deploy fabric8-analytics-gemini server on production with endpoint `/api/v1/register' and integrate it with OSIO workflow. 

## Task List
- [x] Develop endpoint '/api/v1/regsiter'
- [x] Ingest the data 
- [x] Write unit tests 
- [ ] Write integration tests.
- [x] Include e2e tests in jenkins build
- [ ] report generation task to collate CVE and license data for all dependencies
- [ ] report generation task to call license service to retrieve stack license.

## Parent
https://github.com/openshiftio/openshift.io/issues/2326

**Comment by GeetikaBatra** [comment]
@sivaavkd, I am closing this as I am no longer working on this one.
