### ISSUE TITLE
[8] Generalize GithubDependencyTreeTask to support multiple ecosystems

### ISSUE THREAD

**Issue by abs51295** [openshiftio/openshift.io#2496]
#### User Story

As on OSIO user, I will be able to get vulnerabilities for all my direct and transitive dependencies so that I can refine my stack to remove the vulnerabilities.

#### Description

Currently [GithubDependencyTreeTask](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/workers/dependency_parser.py) identifies the direct and transitive dependencies for a given maven repository. Need to extend this to extract direct and transitive dependencies for node, python and go ecosystem.

#### Acceptance Criteria

* Given a repository, the task should be able to identify the ecosystem and return the list of all direct and transitive dependencies.

#### Task list

- [x] Implement dependency parser for node ecosystem. 
    - [x] Identify the unique identifier that classifies the repository as a node repository.
    - [x] Run mercator command and parse the output to get all the direct and transitive dependencies.
- [x] Implement dependency parser for python ecosystem.
  - [x] Identify the unique identifier that classifies the repository as a python repository.
  - [ ] Run mercator command and parse the output to get all the direct and transitive dependencies.
- [x] Implement dependency parser for go ecosystem.
  - [x] Identify the unique identifier that classifies the repository as a Go repository.
  - [x] Run mercator command and parse the output to get all the direct and transitive dependencies.

#### Additional Task list

- [ ] Deploy worker-api with osioAnalysisFlow on production.
- [ ] Develop `/scan` endpoint to initiate osioAnalysisFlow.

**Comment by msrb** [comment]
One thing to keep in mind here is that if parsing dependencies requires executing code from users' `setup.py` files, or if `npm list` command requires the dependencies to be installed first (and thus executing untrusted [scripts](https://docs.npmjs.com/misc/scripts)), then this cannot be done in our current worker containers. Untrusted code could attempt to damage our infrastructure or to steal credentials as those are available in worker containers in environment variables.

**Comment by abs51295** [comment]
This has to be moved to Sprint 147 since there were different priorities worked upon in 146. Thanks.
/cc @sivaavkd
