### ISSUE TITLE
UI Architecture - Document, Improve, Clean, and Refactor

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#2498]
# Description
As a developer of the system, I want to be able to have a clean, fast, reliable build that is both CI and CD.

# Acceptance Criteria
- [ ] The builds should have consistent, repeatable, reliable, performant packaging, releasing and deployment
- [ ] The UI should be refactored to clear up immediate performance concerns 
- [ ] Automated end-2-end testing should be added to the build before release for verification of deployments
- [ ] Tree shaking should be set up and configured (as long as it improves performance)
- [ ] AoT, Ahead of Time compilation, should be set up and configured (as long as it improves performance)
- [ ] Service Workers should be set up and configured (as long as it improves performance)
(Service Workers - if it works correctly…)

**Comment by maxandersen** [comment]
@michaelkleinhenz @nimishamukherjee FYI

**Comment by qodfathr** [comment]
@joshuawilson how can this be two types at the same time? FYI, the way it is written, that's not a `fundamental`. If we are to adopt our proper planning methodology, this really should be built top-down from a real world problem. Maybe this is the decomposition of an existing `Experience`? If it is, can we link to that?

**Comment by joshuawilson** [comment]
It may not be written correctly for whatever label we end with. I'm fine if we need to update it. 
I had thought that a `fundamental` was something like architectural improvements. But from a dev perspective this is an `epic`. So if it doesn't need the agile boilerplate `As a developer of the system, I want to be able to` we can remove that. :)
