### ISSUE TITLE
[3](Getting Started) Select Release Strategy - Tasks

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#2510]
### User Story: 
As an OSIO user, I will be able to see the release strategy based on selected runtimes/missions in the previous step as per new UXD. [Quick Start flow]

### Acceptance Criteria:
OSIO user should be able to select release strategy, based on selected runtimes/missions in the previous step.

##### Task list
- [x] - Integration of Services in the new UX flow
- [x] - Unit test cases to handle the new ux changes
- [x] - Integration into OSIO
