### ISSUE TITLE
[5] (Getting Started) Authorize git provider - Tasks

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#2514]
### User Story: 
As an OSIO user, I will be able to link my account with GitHub, fetch user's authorized Organisations and validate if repository exists as per new UXD. [Quick Start flow]

### Acceptance Criteria:
OSIO user should be able to link his account to GitHub, fetch user's authorized Organisations and validate if repository.

##### Task list
- [x] - Integration of Services in the new UX flow
    - [x] - Integrate GitHub link
    - [x] - Integrate users Org API
    - [x] - Integrate check repository API
- [x] - Unit test for integrated service
- [x] - Integration into OSIO

**Comment by invincibleJai** [comment]
Associated PRs  https://github.com/fabric8-ui/fabric8-ui/pull/2615
