### ISSUE TITLE
Pod Deployment Status

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#2545]
Parent: #287 

# Description

As a user, I want to be able to see the status of pods in my deployments, and to be able to see issues that could potentially block the scaling of my pods.

# Relationships

- https://github.com/openshiftio/openshift.io/issues/2086

- https://github.com/openshiftio/openshift.io/issues/1658

# Acceptance Criteria

- [x] When my deployment has no issues, I should see an indication that everything is OK

- [ ] When my deployment has issues, I should see an indication of what those issues are

# Tasks

- [x] https://github.com/openshiftio/openshift.io/issues/1452

- [x] https://github.com/openshiftio/openshift.io/issues/1659

- [x] https://github.com/openshiftio/openshift.io/issues/2519

- [x] https://github.com/openshiftio/openshift.io/issues/2542

**Comment by andrewazores** [comment]
Closing. There is still related future work to be done from https://github.com/openshiftio/openshift.io/issues/2086 , but that's out of the current scope for this issue.
