### ISSUE TITLE
Boosters in OSIO - failures and gaps 

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#2558]
### Description
As an OSIO user, I should be able to select quickstart applications from pre-defined boosters, build and deploy successfully onto my OSO namespace.

#### Acceptance Criteria
- Boosters available OSIO Launcher
- Able to select a booster and trigger a build
- Able to Commit, Push changes to trigger a build
- Able to invoke unit tests from Che Terminal 
- Able to build using `mvn clean install -Popenshift,openshift-it` from Che Terminal
- Able to deploy using `mvn clean fabric8:deploy -Popenshift` from Che terminal
- Able to explicitly trigger build
- Able to create PR at GitHub to trigger build with integration tests
- Able to 'merge to master' at GitHub to trigger build with Integration tests
- Able to approve, deploy booster application 
- Able to validate application running at Stage environment
- Able to validate application running at RUN environment

#### Build Issues
- [x] Jenkins Build failure due to fmp version upgrade #2505 (works for fresh quickstarts + patching(if fmp version < 3.5.8) applied for already existing quickstarts )

#### CI Issues
- [ ] mvn build fails in Che for boosters (mvn clean install -Popenshift,openshift-it) #2556 (fabric8-launcher/launcher-planning#119)
- [ ] CI build fails on create a PR at Github #2556 

#### ConfigMap Issues
- [ ] Auto Apply configmaps to ConfigMap specific boosters #2564 (PR https://github.com/fabric8-launcher/launcher-backend/pull/216) #2837
- [ ] Failed to apply configmaps manually #2562 
- [ ] At Che, mvn fails to deploy to stage and run environments with oc command  #2557 

#### Che/Misc Issues
- [ ] Che RUN and DEBUG commands are missing for imported apps (inc. boosters) #2358
- [ ] HTTP 500 Error seen: space label missing from deployment config for application (imported booster) #2360 (PR https://github.com/fabric8io/fabric8-pipeline-library/pull/390 and https://github.com/fabric8io/fabric8-maven-plugin/pull/1252)
~~- [ ] Unable to perform Unit tests from Che #2559 (possible dup of #1060)~~

#### Analytics Issues
- [x] Identify, Ingest required stats for RHOAR dependencies #2481

**Comment by ldimaggi** [comment]
Just to confirm and set the context for this issue - the full set of Boosters to which this issue refers is:

* HTTP: Vertx, Springboot, WildflySwarm
* HealthCheck: Vertx, Springboot, WildflySwarm
* ConfigMap: Vertx, Springboot, WildflySwarm

Is this correct? Thanks!

**Comment by miteshvp** [comment]
@ldimaggi - I have just tested on Vertx Configmap and not any others. I will keep this issue updated if I am able to replicate the same behaviors for other boosters

**Comment by joshuawilson** [comment]
@miteshvp this reads like a `user-story`. `support` is for someone asking for help using the system, is that your intent?

**Comment by miteshvp** [comment]
@joshuawilson - thanks for the clarification. I have modified the type for now, but I still don't know the correct label here. Will talk to @krishnapaparaju and identify the correct ones.

**Comment by gastaldi** [comment]
@miteshvp the Configmap boosters do not work yet in OSIO, that's why it is not listed in the UI. We're working on it: https://github.com/fabric8-launcher/launcher-planning/issues/119

**Comment by miteshvp** [comment]
@gastaldi - noted. I am trying to collate all the problems across boosters so that it becomes easier to manage.

**Comment by animuk** [comment]
closing this at the moment. we have enabled community edition of the wildfly boosters at the moment until the latest version is not published from the wildflyboosters team. This is the current status below:
https://docs.google.com/spreadsheets/d/1dr1XfsGiGGf_Sh6s0DbAvtLSLzbrNaUf6nZxPz0WTyo/edit#gid=0
We will be tracking this from now on in a separate issues
