### ISSUE TITLE
[spike] investigate ngrx for fabric8-ui

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#2560]
Relate to [UI refactor performance](https://github.com/openshiftio/openshift.io/issues/2500) user story.
# Description
Evaluate how to use ngrx in `fabric8-ui`.
# Tasks
- [x] write UI architecture design, how to add new store
- [x] review planner PR on ngrx [Refactored planner with Redux technology with (ngrx/store and ngrx/effects)](https://github.com/fabric8-ui/fabric8-planner/pull/2482) and link with @sanbornsen for initial design
- [x] prototype with Add space flow.
cc @joshuawilson

**Comment by corinnekrych** [comment]
Done:
- [ ] Prototype available: https://github.com/fabric8-ui/fabric8-ui/pull/2647/files
- [ ] Wiki: 
Todo to finish add_space:
- [ ] modify new applauncher create space flow (here we have a feature toggle ie: code is duplicate new/old)
