### ISSUE TITLE
VSCODE Extension tasks

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#2617]
### User Story: 
As a VSCode user, I will be able to see stack reports for ` package.json`, feature for multi workspace support, change suggested version for CVEs with a click.

### Acceptance Criteria:
VSCode user, should be able to see stack reports for ` package.json`, get support for multi workspace, should be able change suggested version for CVEs with a click.

##### Task list
- [ ] - Code Action feature for component-analyses
- [ ] - Multi workspace support for VSCode
- [ ] - Node ecosystem support i.e stack analyses/ component analyses for package.json
- [ ] - CI/CD along with semantic release for LSP( we do have CI/CD for Jboss)
- [ ] - Setting up test env for LSP
- [ ] - Unit tests for LSP
- [ ] - Doc related changes

**Comment by joshuawilson** [comment]
Please set the `type`
