### ISSUE TITLE
[4] Reduce the number of API calls for feature-flag

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#2626]
Parent: https://github.com/openshiftio/openshift.io/issues/1165
# Description
As a user of OSiO, I want the app to perform. We want to make sure we reduce the number of API calls for feature-flag.
# Tasks
- [ ] spike: investigate browser cache for getFeatures([]) - todo corinne/xavier
- [ ] cache: getFeature('featurename') `cache-control` on header to stay this request is valid for 30mins, `last-modified` 304
- [ ] See how it fits with UI Context
