### ISSUE TITLE
[1] (Deployments) UI: Clean up DeploymentsService API

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2630]
Parent: #287

# Description

As a developer, I want to use a cleaner DeploymentsService API

# Acceptance Criteria
- [x] DeploymentsService "Environment" type can be replaced with string #2585
- [x] DeploymentsService function parameter orders are inconsistent #2586
- [x] Deployments files do not have any clutter (ex: unused imports) #2753
