### ISSUE TITLE
[5] Implement the logic in launcher-backend to insert the dependencies in pom.xml

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#2644]
#### User Story:

As an OSIO user, I will be able to insert the dependencies in pom.xml.

#### Description:
As dependency editor will be the part of launcher wizard flow which will allow users to add dependencies to their project. once he selected one of the boosters in the project creation wizard and which will provide the analytics insights to selected dependencies and these dependencies should be added in the pom.xml of the current booster that user has selected.

#### Task List:
- [ ] add `dependencySnapshot` optional form parameter `osio/launch` POST API call and add new method in createProjectileContext interface and implement that
- [ ] Read the dependency snapshot string and convert the string object into JSON object.
- [ ] Adding Unit test cases for the implementation.
- [ ] Process the dependency snapshot and get groupId, artifactId, versions and other information
- [ ] Implement the logic to insert the dependencies into the pom.xml
