### ISSUE TITLE
[8] Python module/library for comparing Maven versions

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#2702]
# Description

Maven versions can be [weird](http://central.maven.org/maven2/com/googlecode/owasp-java-html-sanitizer/owasp-java-html-sanitizer/). We need a way how to (Maven-reliably) compare two different versions of a package. This is how Maven does that: https://maven.apache.org/pom.html#Version_Order_Specification. And this is the implementation: https://github.com/apache/maven/blob/master/maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java.

Normally we would just use [the same library](https://mvnrepository.com/artifact/org.apache.maven/maven-artifact/3.5.3) as Maven uses internally, but our codebase is mostly Python, and we don't want to pull in JRE to every single image we have. Therefore we want check if there is an existing library that we could use, or we want to write our own.

Possible candidate is https://pypi.python.org/pypi/packaging.

## Task List
- [x] Understand how maven versioning works.
- [x] Create a method parse version which will  breakdown the version and push into respective stacks for comparison
- [x] Create a method to compare the items in stack.
- [x] Cover edge cases.
- [x] Set up py test config for the repository
- [x] Write unit tests for the methods implemented.
- [x] Package the code to a pypi module.
- [ ] ~~Make it available for public consumption.~~

**Comment by abs51295** [comment]
@msrb I was also exploring packaging module the other day and found it be a good candidate. Are there any problems that we faced while using that module?

**Comment by msrb** [comment]
@abs51295 not really, we just don't know how good it really is for comparing Maven versions.

**Comment by sara-02** [comment]
@msrb Since we need to perform sem-versioning for different ecosystems, and then use it different f8a modules, we can think of an uniform approach, maybe have a separate repo/create a package of it if needed, and use it as library when needed based on the parameters like `ecosystem, version, compare` etc.

**Comment by sara-02** [comment]
Also, I think we should have an `EPIC` if it not already there so that we can track progress for different ecosystems as and when we add them to f8a

**Comment by msrb** [comment]
> maybe have a separate repo/create a package of it if needed, and use it as library when needed

+1, definitely agree. That's why the title of the issue is "Python module/library for comparing Maven versions". I also prefer having a small library that would be easy to test and reuse in different services. We can then add support for other ecosystems as we go/need.

**Comment by bartoszmajsak** [comment]
Why not a  dedicated service (I won't call it micro... yet) written in Java? You can use Maven Model API and all the goodies which let you consume `pom`s and reason about them without trying to implement your understanding of maven model instead?

**Comment by msrb** [comment]
Hey @bartoszmajsak, thanks for getting in touch :wink:

In this case all we need is to be able to compare two Maven artifact versions, basically [this](https://github.com/apache/maven/blob/master/maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java), but in Python.
I initially linked a [wrong section](https://maven.apache.org/pom.html#Dependency_Version_Requirement_Specification) of the Maven documentation in the description - [fixed now](https://maven.apache.org/pom.html#Version_Order_Specification). If we were trying to do anything more complex than that, we would use Maven or its libraries, as you correctly suggested.

I am familiar with standard Maven tooling, but not with our stuff. What Maven goodies do we have? :)

**Comment by vasulakkaraju** [comment]
@msrb i could see that semantic_version is working with some of the maven artifact versions.Here is the reference  https://pypi.python.org/pypi/semantic_version/.It has been tested with some of the maven artifact version info for which it looks fine. Pls LMK if some of you have already tried this for this problem.

**Comment by GeetikaBatra** [comment]
@msrb, I presume, JRE would be present by default if the image makes use of maven artifacts. Maven cannot work without JDK(let alone be JRE). Can't we run a maven commands with python subprocess module to get the specific versions of artifacts? Please correct me if I am wrong.

**Comment by GeetikaBatra** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-version-comparator/pull/1

**Comment by GeetikaBatra** [comment]
@msrb, @sivaavkd . This will be a spill over.

**Comment by msrb** [comment]
@GeetikaBatra Ack, please add story points. Thanks :wink:

**Comment by GeetikaBatra** [comment]
@msrb, Sure, on it :D

**Comment by msrb** [comment]
@GeetikaBatra we still need the story points for this issue :wink:

**Comment by GeetikaBatra** [comment]
@msrb, updated :D.

**Comment by msrb** [comment]
Initial version is complete, thanks :wink:
