### ISSUE TITLE
Load testing of the Node insights model (CVAE based deep learning model) service endpoint independently

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#2708]
### Description

Load test the node insights (CVAE) model to get the optimal resource usage for it to request resources on production, also verify that the service scales and can support the currently committed concurrent user count and adhere to the SLA.Document the results of the same.

### Acceptance Criteria

- [x] Should have the optimal resource usage documented
- [x] Verify that the service scales

### Task List

- [x] Write the load testing script
- [x] Load test against various resource limits and document results

Relates to #2467

**Comment by rootAvish** [comment]
Link to load testing results document: https://docs.google.com/spreadsheets/d/18csKfkgIJ8nJ6neN2aWq_YkO0wh6f8XcP4pF2dXF2Os/edit?usp=sharing

**Comment by rootAvish** [comment]
Closing as load testing is done, results documented in the document above. Will work with SD based on these.
