### ISSUE TITLE
Sprint plan for Fabric8 Analytics: #147

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2775]
***Handle updates around OSIO user's application stacks***  #2774 

- [ ] Required scheduled jobs

- [ ] Communicate thru email

- [ ] Create an issue at user's repository

**Scale the platform to support 500 concurrent users** 
- [ ] ~~Promote changes to OSIO~~ (Details here [housekeeping#1708](https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1708))

***Insights for Node ecosystem*** #2806

- [ ]  Integrate into end to end workflow of Fabric8 Analytics platform (#2806)

- [ ] Production ready with end point at OSIO production

**Map CVEs**
- [ ] Continue the current manual mapping from NVDB to individual packages

- [ ] Start mapping CPEs for Node ecosystem

- [ ] Start mapping CPEs for Python ecosystem

***Close known SEV-2 bugs***

- [x] #2770 

- [x] #2769 

- [ ] #2720 

- [ ] #2694 

- [x] #2684 

- [ ] #2343

- [ ] #2335
- [ ] #2328
- [x] Current graph queries could be missing some package versions - #2313
- [x] #2272 

- [ ] #2801 

- [x] [psycopg2.IntegrityError](https://github.com/openshiftio/openshift.io/issues/2218)
- [x] [Different 'label' values are stored in the Graph database for package versions data](https://github.com/openshiftio/openshift.io/issues/1934) 
- [ ] #833
- [ ] #814

**Complete OSIO Gemini related activities related to Fabric8 Analytics integration** #2326
    
- [ ] Support Node based Images

- [ ] Support GO based Images

- [ ] Support Python based Images

- [ ] Productionize Gemini (F8A + Scanners at Pipelines)

- [ ] Test OSIO images after change in base Image to RHEL

- [ ] Work with SD team for setting Registry, test end to end flow from registry hosting OSIO images

**Improve service side for better handle on service deployment**

- [ ] Define scope for simulating failures

- [ ] [Resilient infra for services of Analytics platform](https://github.com/openshiftio/openshift.io/issues/1084)

**Data ingestion, sanity related activities**

- [ ] [Gradle support] #1897 

### Common processes ###
- [ ] update/finish DoD (definition of done) document

### Stack analysis + component analysis ###
- [ ] Integration tests cover all API endpoints
- [ ] 100% integration test coverage for all supported packages/components (vertx, ...)
- [ ] Data in S3 in perfect state for all supported packages (stage == prod)
- [ ] Data in Graph DB in perfect state for all supported packages (stage == prod)
- [ ] UI e2e tests (from the new repo to stack analysis) [leo]
- [ ] stability of REST API (longer tests with lower frequency of API calls) [100% responses expected on prod]

### Code quality related tasks ###
- [x] #2787 [1] Setup all CI jobs for `f8a-server-backbone`
- [x] #2789 [½] Add `f8a-server-backbone` to the QA Dashboard
- [ ] #2788 [1] Setup all CI jobs for `fabric8-analytics-auth`
- [ ] #2790 [½]  Add `fabric8-analytics-auth` to the QA Dashboard
- [x] #2898 [1] Setup all CI jobs for `fabric8-analytics-api-gateway` repository
- [x] #2899 [½] Add `fabric8-analytics-api-gateway` repository to the QA Dashboard
- [x] #2812 [½] Fix all sources in the `f8a-server-backbone` to pass Python linter and Pydoc checker
- [ ] #1636 [5] Implement Referential Integrity (RI) tests for the data stored in graph database
- [x] #2791 [½] Update CC script to create a stub for weekly mail sent to the devtools mail list
- [x] #2892 [½] Display link to actual Sprint plan on the QA Dashboard
- [x] #2792 [3] Improve unit test code coverage for `fabric8-analytics-server` to 50%
- [x] #2793 [2] Improve unit test code coverage for `fabric8-analytics-jobs` to 25%
- [x] #2794 [1] Improve unit test code coverage for `fabric8-stack-analysis` to 50%
- [x] #2795 [1] Improve unit test code coverage for `fabric8-analytics-tagger` above 95%
- [x] #2796 [2] Improve unit test code coverage for `fabric8-gemini-server` to 50%
- [x] #2855 [1] Improve unit test code coverage for `fabric8-data-importer` above 90%
