### ISSUE TITLE
Sprint plan for OSIO Getting started experience : #147

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2776]
**Getting Started Experience**

- [ ] Close all the open functional work items related to Launcher  #2377
- [ ] Close all the open functional work items related to Dependency Editor  #2377
- [ ] Tests are in place for the end to end Launcher components
- [ ] CI / CD, Semantic release has to be implemented #2516

**Make the boosters work at OSIO user flow**

- [ ] Make boosters work at OSIO, work thru the gaps #2558 
- [ ] Test Suite for booster support #2399 
- [ ] Redhat GA Booster ingestion to Analytics #2481

**Scale Launcher to support 500 concurrent users** 

- [x]  Promote changes to OSIO
