### ISSUE TITLE
Refactor ContextService to use central ngrx-store

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#2802]
# Description
Following the [spike](https://github.com/openshiftio/openshift.io/issues/2560) and based on the [architecture document](https://github.com/fabric8-ui/fabric8-ui/wiki/ngrx), implement a first ngrx store for Context.
Replace Context by Store with a structure like
```
{ 
  fabric8-ui: {
   currentSpace
   currentEntity
   recentSpaces[]
  }
}
```
We should look at implementing the model resolver (like [here] in planner) to provide a cache of data.

Given the Service si core to fabric8-ui, after a global search, I've listed and tried to group all components using `ContextService`. The idea is to work on a shared branch and progressively remove ContextService DI in those components in favor of the central store.

# Task
- [ ] Homecomponent, HeaderComponent
- [ ] CodebasesComponent, CodebasesAdd….
- [ ] PipelineComponent
- [ ] SpaceWizardComponent, AnalyseOverviewComponent (new launcher wizard: AddSpaceOverlayComponent)
- [ ] ForgeWizard: AbstractWizard, ImportWizard, QuickstartWizard, (new launcher wizard: CreateAppComponent, ImportAppComponent)
- [ ] ConnectedAccountComponent
- [ ] AreaComponent, CreateAreaDialogComponent
- [ ] CollaboratorsComponent, AddCollaboratorDialogComponent
- [ ] GithubService
- [ ] ContextResolverService, OwnerguardService, contextService, ProfileResolverService, OwnerGaurdResolver

@sanbornsen feel free to comment on the task.
cc @joshuawilson

**Comment by joshuawilson** [comment]
External project will use this as well, like the Planner.
