### ISSUE TITLE
[13] Setup NPM insights recommendation service on stage, prod and refine training logic pipelines and logic

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#2806]
## User Story

As a fabric8-analytics user I should be able to get stack analyses results for the NPM ecosystem.

## Acceptance Criteria

- [x] Should have the end to end NPM insights piece running in stage/prod.

## Epic (Feature)

Part of the work being done towards #2434.

## Description

Extending our work from the previous issues #2264, #2002, #2004 and #2467  we have a service for NPM companion insights running from the dev cluster. Following that, the work in this sprint incorporates unit testing, setup of a CI/CD pipeline and integration with the end to end piece (stack analyses) along with changes to the training piece to write it using the estimator pattern. All relevant info is covered [in this gdoc](https://docs.google.com/document/d/1LTAJRq60lNs-fDGsZLkLS0r8E8j5zDxK_7zkXJqLRxM/edit#).

Also need to coordinate with SD and core for resources on stage/prod and collection of EPV's coming in from the collected manifests to graph.

## Task List

- [ ] Write the pre-processing pipeline to aggregate and clean the data collected through the jobs API.
- [ ] Refactor DAE POC training code to follow the estimator pattern (retrain)
- [ ] Refacor CVAE POC training code to follow the estimator pattern (training)
- [x] Ingestion of EPV's coming in from the manifest files
- [x] Standardization of the manifest file collection process
- [x] Unit tests for the training/scoring logic [initial setup and sanity]
- [x] Creation of CI/CD pipeline for the new repository
- [x] Get the CI/CD job integrated into [openshiftio-cico-jobs](https://github.com/openshiftio/openshiftio-cico-jobs).
- [x] Coordinate with service delivery to create a new "kronos" pod for this service on staging, ~~prod~~
- [x] Changes to `f8a-server-backbone` to pick the new service
- [x] Make required changes to `fabric8-analytics-server` if any, required to integrate the service with the recommender API
- [x] Get the end to end piece to work through the recommender API
- [x] Write the e2e functional tests (API level only) for the recommender API with this service integrated.
- [x] Ingestion of the EPV's coming in from the collected manifests.

**Comment by rootAvish** [comment]
The remaining work around the training will be scoped in a separate issue in 149. Closing as done.
