### ISSUE TITLE
Platform - Build/Release/Deploy - Continuous Integration/Deployment

### ISSUE THREAD

**Issue by michaelvirgil** [openshiftio/openshift.io#281]
# Description
As a developer of the system, I want to be able to have a clean, fast, reliable build that is both CI and CD.

# Acceptance Criteria
- [x] The various UI components should "roll-up" into all consuming UI components as they are merged to their master repo, via CI/CD https://github.com/fabric8io/fabric8-ui/issues/1591
- [ ] The builds should have consistent, repeatable, reliable, performant packaging, releasing and deployment
- [ ] The UI should be refactored to clear up immediate performance concerns 
- [ ] Automated end-2-end testing should be added to the build before release for verification of deployments
- [ ] Tree shaking should be set up and configured (as long as it improves performance)
- [ ] AoT, Ahead of Time compilation, should be set up and configured (as long as it improves performance)
- [ ] Service Workers should be set up and configured (as long as it improves performance)
(Service Workers - if it works correctly…)
- [ ] Set up a system/pipeline to streamline updates of dependencies. It is preferred to have a central location that stores the dependencies and their version numbers. This allows all the components to point to this and derive the same version numbers and stay in sync.

**Note**: 
NEEDED to respond to customer issues and blockers
 
# Relationships
_Put linked Team/Product story links here_

**Comment by qodfathr** [comment]
Do we want to keep the Epic open? Although I don't disagree with the goals of this epic, I feel that much of these goals are being addressed and/or restated in other epics (both existing and to be existing). Moreover, some of these have been addressed yet not tracked here.

@michaelvirgil @joshuawilson thoughts on closing?

**Comment by joshuawilson** [comment]
This is on me. I need to update it. There are several things here that I still want to get done, so let's keep it open.

**Comment by joshuawilson** [comment]
This is has been replaced by a more complete set of user-stories in #2498. Closing.
