### ISSUE TITLE
Integrate dependency Editor into Getting Started flow as an optional step

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#2810]
### User Story
As an OSIO developer, I will be able to add my own dependencies by finding insights about components, securities by using Dependency editor feature.

### Acceptance Criteria
I should use dependency editor, if I wish to, for adding dependencies, finding security-related information and see some insights about it.

### Tasks

- [x] - Improve the existing dependency editor
    - [x] - Code refactor
    - [x] - Error handling
    - [x] - Unit tests
    - [x] - Minor UI fixes
    - [x] - Content for UX
    - [ ] - Documentation updates for the feature
- [x] - Integration with Getting started flow
    - [x] - Handle UI related changes
    - [x] - Unit tests to ensure the stability of the included module
    - [x] - Implementation of logic to modify the pom.xml in prod.[Priority1]
    - [x] - End points to point to prod URL on UI side.[Priority1]
    - [x] - Integration discussion for Dep Editor as internal feature.
    - [x] - UX has to be in sync as per new UXD [Priority1]
    - [x] - Handling UI layout post integrting with Launcher [Priority1]
    - [x] - Issues with AOT compilation [Priority1]

Parent Task List: https://github.com/openshiftio/openshift.io/issues/2377

**Comment by arunkumars08** [comment]
@sanketpathak Please update this issue list accordingly.

**Comment by sivaavkd** [comment]
@sanketpathak Where are we with this ?  Is this spilling over to 148 ?  Please update accordingly.
