### ISSUE TITLE
Platform Architecture - Performance & Scale

### ISSUE THREAD

**Issue by michaelvirgil** [openshiftio/openshift.io#284]
# Description
As a developer, I want to know and understand the architecture and I want it to be performant and reliable.

# Acceptance Criteria
- [ ] The architecture needs to be defined, documented, and published
    - [ ] Discuss, document, and share the current and progression of architecture
    - [ ] Architecture - Principles, planning the architectural runway...
    - [ ] Document the process for defining and documenting APIs
- [ ] Service deployment should support non-disruptive upgrades and improvements
- [ ] The system needs to scale (1000s registered users)
- [ ] The system should support Multi-Tenancy on Che and Jenkins

**Note**: 
 
# Relationships
_Put linked Team/Product story links here_

**Comment by qodfathr** [comment]
I feel this Epic has been captured by several other Epics (some which are planned but still need to be authored). Thoughts on closing this one in favor of several others?

**Comment by joshuawilson** [comment]
If you can point to the others that cover it then we can close this.

**Comment by qodfathr** [comment]
I could try and find them all. Or, I could also point out that this dates back to June 23 and not a single checkbox has been marked as completely, and no other issues reference this Epic indicating that it is being worked on. :)

I honestly don't feel it's worth the effort to track down and list all of the related issues which replace this one, so I am going to close. Anyone is welcome to reopen it, but, in doing do, that person will now own this epic and will have to ensure that there is a plan to get all of the acceptance criteria met.
