### ISSUE TITLE
Preparation for user testing navigation models

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#2847]
In order to test potential navigation models with users at Red Hat Summit, ensure we have 3 ideal navigation prototypes fully working and ready for testing.

- Nav model 1 (left-hand): https://github.com/fabric8-ui/fabric8-ux/issues/884 
- Nav model 2 (mega menu): https://github.com/fabric8-ui/fabric8-ux/issues/899
- Nav model 3 (center): https://github.com/fabric8-ui/fabric8-ux/issues/929

VERIFICATION CRITERIA:
- [x] 3 prototypes have been reviewed
- [x] 3 prototypes have been refined to be completely ready for summit testing (see list of related stories, below)
- [x] Scripts have been written for testing with users at Summit, and are posted into OSIO google drive
- [x] Surveys and Note taking files have been created and are ready for consumption by testers, posted into OSIO Google drive

RELATED STORIES:
- [x] View all spaces: https://github.com/openshiftio/openshift.io/issues/3010
- [x] Search: https://github.com/openshiftio/openshift.io/issues/3011
- [x] Help/doc: https://github.com/openshiftio/openshift.io/issues/3012
- [x] Animation (left-hand nav): https://github.com/openshiftio/openshift.io/issues/3013
- [x] Animation (centered nav): https://github.com/openshiftio/openshift.io/issues/3014
- [x] Space name: https://github.com/openshiftio/openshift.io/issues/3015
- [x] Dummy screen shots:  https://github.com/openshiftio/openshift.io/issues/3016
- [x] Notification: https://github.com/openshiftio/openshift.io/issues/3017
- [x] System status: https://github.com/openshiftio/openshift.io/issues/3018
