### ISSUE TITLE
Notifications of base/simple/common actions

### ISSUE THREAD

**Issue by michaelvirgil** [openshiftio/openshift.io#285]
Note: Functionality/mechanism provided by Platform 
- [ ] email notifications service - component based definition of what to send...
    - [ ] Investigate management of notifications - platform/components…
    - [ ] Discover/register notifications available and management within platform
    - [ ] https://openshift.io/openshiftio/openshiftio/plan/detail/953 
- [ ] Across component notifications - events/mentions or actions
    - [ ] In platform toast notifications, action/event notifications
    - [ ] Discover/register notifications available and management within platform
- [ ] UXD: Needs UX design 
- [ ] Planner - first customer - 
    - [ ] Get notified on updates to work items creator has added - creator notification - always
    - [ ] Get notified on all updates of work items you have participated on (creator, assignee, commenter, etc.)
    - [ ] Be able to mute notifications (all or nothing…) - by type of notification
- [ ] Support Mentions

**Comment by kwk** [comment]
Do we want to have a permanent storage for notification that can be served to the user somewhat like Github is doing here: https://github.com/notifications ?

**Comment by aslakknutsen** [comment]
@kwk Yea, we probably want some sort of 'Notification area' in the future. But as far as this sprint is concerned it's more about just getting some kind of notification out so people can know that something has happened.

**Comment by hectorj2f** [comment]
@aslakknutsen It depends of what we want but having some storage might be easy

**Comment by joshuawilson** [comment]
related to #245

**Comment by qodfathr** [comment]
This Epic is concerning email notifications, but I'd suggest the more proper epic is concerning notifications in general, of which email is just one kind (and therefore a child). UXD has been working on notification designs. Should we simply reword this Epic to capture the broader notification Scenario?

**Comment by joshuawilson** [comment]
If it is a major rewrite then you could just make a new one and reference this one and close it. If it is just adding a bit then do it here.
