### ISSUE TITLE
[EPIC]Different Graph Instances for each ecosystem

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#2851]
## Description:
With increase in data for each ecosystem, having a different graph instance per ecosystem will make the ingestion and updation task easier. It will also give us the flexibility to modify relations as per the ecosystem, as each ecosystem behaves differently in terms of metadata, versioning etc.

## Task List:
 - [ ] Revive the work around Janus to replace Titan
 - [ ] Set up different endpoints for each graph(CI/CD modification+ Resource count on staging/prod+ AWS)
-  [ ] Transfer the separate data
-  [ ] Technical debt for graph ingestion(to make it salable and faster and modify it to accommodate ecosystem level changes)

## Priority ecosystem: Node and Maven

**Comment by sara-02** [comment]
cc @krishnapaparaju

**Comment by miteshvp** [comment]
@sara-02 - please do not assign a work-item on other's behalf. Thanks.

**Comment by sara-02** [comment]
Closing this as the Planner Epic takes care of this https://openshift.io/openshiftio/openshiftio/plan/detail/2154
