### ISSUE TITLE
[POC-part1] Single DL model for OSIO Insights:Version 1.0

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#2853]
## Description:
Based on only manifest data, we are hoping to generate companion recommendations for the system. 

## Proposed methods to try:
* Autoencoder based:  https://arxiv.org/pdf/1708.01715.pdf 
* HPF based(HPF/HCPF): http://auai.org/uai2015/proceedings/papers/208.pdf, https://arxiv.org/pdf/1604.03853.pdf 

## Task List:
- [x] Find the similarity between current PMF approach and the proposed approaches
- [x] Check the existing code(external projects) for usability
- [x] Variational inference for hyperparameter tuning.
- [x] Generative process of the HPF model to form the user-item-feature matrix
- [x] Finalize the HPF approach, based on existing code bases and new code that is added.

Details can be found in this [doc](https://docs.google.com/document/d/1VFsisL65ye_L_awbbVjGdjLLOYGulFWHtxnGbSsla1I/edit?usp=sharing)

**Comment by sara-02** [comment]
cc: @krishnapaparaju

**Comment by sivaavkd** [comment]
@sara-02 please add story points

**Comment by sara-02** [comment]
@sivaavkd Some part of the work might extend into the next sprint as well. Should I add 13 as the story point or change this to EPIC?

**Comment by sivaavkd** [comment]
Please change this to EPIC, create a new user story with those tasks that you are planning to complete in this sprint along with story points... and you can create another user story for next sprint.

**Comment by sivaavkd** [comment]
@sara-02 ^^

**Comment by sara-02** [comment]
@sivaavkd The epic is already created. here https://github.com/openshiftio/openshift.io/issues/1809

**Comment by sivaavkd** [comment]
@sara-02 where are we with this ?  Is this spilling over to 148 ?

**Comment by sara-02** [comment]
@sivaavkd Yes.

**Comment by sara-02** [comment]
@sivaavkd I am updated the issue, as part1 of the work is complete. I will create a new issue to list and track the part2 of the PoC, which will be the main focus for this sprint.

**Comment by sara-02** [comment]
We tried the HPF based approach.
