### ISSUE TITLE
Register, Sign up, login flow - Platform UI flow

### ISSUE THREAD

**Issue by michaelvirgil** [openshiftio/openshift.io#286]
- [ ] Overall UX assessment and refinement [happening externally]
- [ ] Alexey/Aslak/JamesS/Dana Consider whether we need full AUTH against GitHub
- [ ] Remove requirement to have public full name and email from github profile
- [ ] UXD: Started page - Reconsider flow.

**Comment by qodfathr** [comment]
@catrobson & @joshuawilson how should we handle this? We've revised the registration and login process since this issue was created, and we have designs for even more enhancements.

I'm not sure the acceptance criteria, as defined in this issue, accurately matches the designs. Do we want to create a new epic (or maybe one already exists) for the overall registration and login process (or maybe it's two epics), and then create child issues for the unimplemented portions of the designs (once the designs are complete and signed off)? Or perhaps some other approach?

**Comment by joshuawilson** [comment]
I'm not sure. I know the main idea is still an issue. People don't like grant us access to everything they have in github.

**Comment by catrobson** [comment]
Let's update this existing issue with the new criteria together this week rather than create a different issue around this.
