### ISSUE TITLE
Deployments page

### ISSUE THREAD

**Issue by michaelvirgil** [openshiftio/openshift.io#287]
# Description
As a user, I would like to be able to easily understand how my application is currently deployed, including all of the services and their versions across multiple environments.

# Acceptance Criteria
- [x] As a user, I should be able to easily find my code deployments
- [x] As a user, I should be able to easily see which versions of which services are currently active on which environments
- [x] As a user, I should be able to understand any resource and capacity information around my deployments, especially when there are alerts or risks in capacity
- [x] The user should be able to view the resource consumed by the deployed application.
- [x] The user should be able to get basic information about each of the environments they have deployed without having to jump back and forth between OpenShift.io and the OpenShift console.  For advanced information, like logs, the user can be redirected to the OpenShift console.

-- Below feels like it should be a separate story ---
- [ ] The user should be easily able to assign pipeline steps to certain environments, and change the environments used for pipeline steps at any time

**Note**: 
Experience 1608E178 [P*] - The “planning a new project” end-to-end experience
While these pages do exist they have yet to have any UX work done on them.

# Relationships
- [x] #445
- [x] #773
- [x] #486
- [x] #489
- [x] #776 
- [x] #899
- [x] #900
- [x] #491
- [x] #492
- [x] #1567
- [x] #1561

Follow-on work:
- Upgrade to pro path #355

# User Stories
- [x] #1658 UI: Show deployment details
- [x] #1654 UI: Show environment resource usage
- [x] #1655 API: Provide API to support Deployments Page
- [x] #1751 UI: Show deployments tab
- [x] #1752 UI: Remove applications and environments pages
- [x] #2545 Pod Deployment Status
- [x] UI: Clean up DeploymentsService API #2630
- [ ] API: Clean up Deployments API #2636
- [x] #2682 Environment usage should always be displayed on Deployments screen, even if there is no deployment

## Associated Defects
- [x] #2037 
- [x] #2038
- [x] #2087 Usage of Hawkular REST Client in "Deployments" leak Go Routines
- [x] #2268 Intermittent, recurring server errors (500) when refreshing OSIO deployment page

## Parent Scenario
#2058

**Comment by rajdavies** [comment]
Would be great if the user can also retrieve information about how much free space they have available on their attached persistent volume.

**Comment by catrobson** [comment]
Designs for Deployments page - https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/257823464  (Replaces today's Application page)

**Comment by catrobson** [comment]
Original designs for the environments page.  Note that there is interest in discussing further whether the current deployments page covers our needs enough that we can get rid of this environments page, or if there is any particular value in the environments page that we should keep or roll into deployments.

https://redhat.invisionapp.com/share/3UAZNL1JQ#/226251975_Environments_Pods

**Comment by catrobson** [comment]
Final designs for the deployments page:
https://redhat.invisionapp.com/share/YSDL0KRKW#

We'll be reviewing any comments in InVision and replying as soon as possible.

**Comment by dgutride** [comment]
@joshuawilson - from meeting with team - can we rename this epic to "Deployments Page"

**Comment by andrewazores** [comment]
^ https://github.com/openshiftio/openshift.io/issues/1382

**Comment by jiekang** [comment]
#1033 does not seem related to this. I don't think it should be a 'relationship'.

**Comment by qodfathr** [comment]
I recommend removing #874 as a child, as that issue really needs to be captured under a larger epic regarding Quota and, as such, shouldn't block successful completion of the revised Deployments screen.

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2003

**Comment by joshuawilson** [comment]
I'm thinking not everything should be moved. This will be closed this sprint. So there will be no point in tracking it all alone in Planner.
