### ISSUE TITLE
Create UI Standards for OSIO

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#2871]
PROBLEM STATEMENT
PatternFly provides a basis of design consistency across Red Hat products.  Within the PatternFly framework, there is room for flexibility in how the patterns and styles are applied into a given project.  There are also cases where the PatternFly documentation might not cover enough detail to create a consistent UI experience across projects or designers using it.

USER STORY
As a designer in OpenShift.io, I would like a single place of truth for some of the UI design standards that have been established for the product that I can reference when designing new features into OpenShift.io.

CHILD TASKS:
- [ ] #2872 Create a location for a single source of truth for UI design standards for OSIO that designers can contribute to
- [ ] #2870 Standardize loading animations
- [ ] #2846 Overlay vs. Modal consistency
- [ ] #2874 Icon standardization

**Comment by mindreeper2420** [comment]
@catrobson I started a Sketch template (similar to PatternFly's) a while back that has some of the OpenShift.io specific items. It is under our Google Drive, [Sketch Symbols -> OSIO_Template.sketch]

**Comment by sdash-redhat** [comment]
@catrobson  should we close this one?

**Comment by catrobson** [comment]
Yup, closing.
