### ISSUE TITLE
Verify the Tags for quickstart and their recommendations

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#2882]
## Description
While @miteshvp was checking the `springboot-healthcheck` for the RHOAR version, we came across the recommendations that looked dubious. The details about the issue can be found here: https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/issues/204

Based on the above issue, we would need to perform the following to verify and validate the various recommendations around quickstarts.

## Task list:
- [x] Validate the tags for the quick starts, their current alternate and companion recommendations(approx 20 unique packages in total).
- [x] Modify the existing tags if required.
- [x] Retrain the model with new tags.
- [x] Test recommendations on staging for both community and RHOAR versions.
- [x] Test recommendations on prod for both community and RHOAR versions.

**Comment by sara-02** [comment]
cc @krishnapaparaju

**Comment by sara-02** [comment]
We can check the updated screenshot here:
https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/issues/204#issuecomment-380774494
