### ISSUE TITLE
Design: Intro to OpenShift.io

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#2886]
Design and Copy for introducing users to OpenShift.io as a first time user.

PARENT FEATURE:
#2885 

VERIFICATION CRITERIA:
- [x] Interaction design of how we will display this intro for first time users, and how they can dismiss it, into InVision and linked to https://github.com/openshiftio/openshift.io/issues/2885
- [x] Copy for the introduction of OpenShift.io to first time users, linked to https://github.com/openshiftio/openshift.io/issues/2885
- [x] Initial storyboards for how we will combine copy/imagery/other media to support telling the OpenShift.io intro to users, linked to https://github.com/openshiftio/openshift.io/issues/2885
- [x] Additional stories created for building final media assets to support this design being implemented

**Comment by Veethika** [comment]
Done: https://drive.google.com/file/d/1Mv5R_xgq4BwaPvyVmmR8DTjxJ-b3dTHD/view?usp=sharing
Interaction rules updated
Next: Visual design and animation for Carousel cards

**Comment by catrobson** [comment]
Can you create a story/issue to capture the visual design needs?

**Comment by Veethika** [comment]
Created a new story for 'Visual Design for Guided Tour': #3366

**Comment by stacymcauliffe** [comment]
This work is complete - additional visual work being addressed in #3366
