### ISSUE TITLE
Activity History

### ISSUE THREAD

**Issue by michaelvirgil** [openshiftio/openshift.io#290]
- [ ] UX Design needed
- [ ] Definition of what we need for MVP outstanding
- [ ] Need to be able to understand/track/debug changes in the WI/system
