### ISSUE TITLE
[8][Launcher] CICD and Semantic release setup for fabric8-launcher/ngx-launcher

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#2945]
This issue deals with the CICD and semantic release setup in place for https://github.com/fabric8-launcher/ngx-launcher

##Task List
### CICD
- [x] Create webhooks in ngx-launcher repo
- [x] Add the job configuration in almighty-jobs
- [x] Introduce necessary files in the repo like cico_*, etc

### Semantic Release
- [x] Add a entry into fabric8-ui/fabric8-npm-dependencies for ngx-forge
- [x] Add the logic to script file to release a version to NPM (**In Progress**)

**Comment by jyasveer** [comment]
Waiting for this issue to be resolved https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1721

**Comment by jyasveer** [comment]
Now we see that on PR merge a version is released to npm adhering to semantic versioning

**Comment by joshuawilson** [comment]
nice to see this done
