### ISSUE TITLE
OSIO Gemini Server: Productization

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#3167]
# Description
This user story contains the tasks required to productize the Gemini Analytics Server that scans OSIO applications for any existing security vulnerabilities in their respective dependencies set.

**Ecosystems To Be Supported:** Maven, Python, Node and Go.

## Task List
- [ ] ~~Gemini Server: Develop `/scan` endpoint to initiate osioAnalysisFlow.~~
- [ ] ~~Create a scheduled job to periodically run a scan on registered repositories.~~
- [ ] ~~Gemini Server: Develop `/scanner-error` endpoint to report scanner level errors via e-mail.~~
- [x] Gemini Server: Develop integration tests for Gemini server.
- [ ] ~~osioAnalysisFlow: e-mail intended recipients.~~
- [x] Deploy Gemini service on the production cluster.
- [x] Deploy worker API on the production cluster.
- [x] Make sure all OSIO repositories have lock files
   - [x] Maven repositories should have `pom.xml`
   - [x] Node repositories should have `package-lock.json` or `npm-shrinkwrap.json`
   - [x] Go repositories should have `Gopkg.lock` or `glide.lock`
   - [x] Python repositories should have `requirements.txt` generated through `pip-compile`

**Comment by samuzzal-choudhury** [comment]
Resource requested to the service delivery team: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1742

**Comment by samuzzal-choudhury** [comment]
Need to revert the PR https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/604 as the messaging to the feature team has to be private.

**Comment by abs51295** [comment]
`package-lock.json` is not available for https://github.com/openshiftio/openshift.io/ and hence we would only be able to scan direct dependencies.
