### ISSUE TITLE
Python module/library for comparing Maven versions 

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#3168]
## Task Description:
Currently, maven versions can be compared by utilizing maven versioning package that resides in maven-artifacts. Since most of the Fabric8 code is python based. This implementation will provide a python module for version comparison.

## Task List
- [ ] Understand how maven versioning works.
- [ ] Create a method parse version which will  breakdown the version and push into respective stacks for comparison
- [ ] Create a method to compare the items in stack.
- [ ] Cover edge cases.
- [ ] Set up py test config for the repository
- [ ] Write unit tests for the methods implemented.
- [ ] Package the code to a pypi module.
- [ ] Make it available for public consumption.

Ref: https://github.com/openshiftio/openshift.io/issues/2702

**Comment by msrb** [comment]
@GeetikaBatra I think we can move the task list to https://github.com/openshiftio/openshift.io/issues/2702 and close this issue.

**Comment by GeetikaBatra** [comment]
@msrb, sure. :)
