### ISSUE TITLE
Provide 100% integration test coverage for all supported packages/components (vertx, ...)

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#3189]
## This epic is about improving integration tests code coverage

- [x] #3490 [2] Implement check of any form of metadata against selected schema for package-level metadata
- [x] #3488 [3] Implement check of any form of metadata against selected schema for component-level metadata
- [x] Tests for package level metadata for `io.vertx-vertx.core` stored in the S3
- [x] Tests for component level metadata for `io.vertx-vertx.core` (all versions) stored in the S3
- [x] Tests for all analyses for package level metadata (vertx.core)
- [x] Tests for all analyses for component level metadata (vertx.core)

**Comment by tisnik** [comment]
Component-related part:
https://github.com/fabric8-analytics/fabric8-analytics-common/pull/537

**Comment by tisnik** [comment]
5th point is implemented via:
https://github.com/fabric8-analytics/fabric8-analytics-common/pull/552

**Comment by tisnik** [comment]
Blocked by https://github.com/openshiftio/openshift.io/issues/3661

**Comment by joshuawilson** [comment]
Can you please move this to the next sprint, your backlog, or close it?
