### ISSUE TITLE
Adding new Work Items using Quick Add in Planner

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#322]
# Description
As a user, I want to add new Work Items using a quick add function that creates new Work Items based on my current context, setting certain attributes on the new Work Item implicitly in a meaningful way.

# Acceptance Criteria
- [ ] The user can add Work Items using a quick add function from the list view.
- [ ] All existing features of the current quick add function are preserved.
- [ ] The current context view query configuration is recognized as the context for the new Work Item and the attributes are set to matching values. 
- [ ] If an entry/card is selected on the context view, the new Work Item will become a children of the specific Work Item. The Work Items recognized as children are linked to the parent using the parent-child relationship.
- [ ] Creating a children from the list view expands the parent, displaying the new children.
- [ ] The available Work Item Types in the types dropdown on the quick add depend on the current context. See the type hierachy story for details. Only a subset of types may be available following the hierarchy.
- [ ] The default selected Work Item Types in the types dropdown on the quick add is determined by the default type of the hierarchy for the current context. See the type hierarchy story for details. There may only be one default Work Item Type.

**Note**: On the context: for example, if the user has a current query configuration set to a specific iteration, the new Work Item will be added to that iteration.

**Note**: The context recognizing ensures the new Work Item is not just "vanishing" but will always be matching the current context and will thus be immediately displayed in the list or board that the user is looking at when adding the Work Item.
 
**Note**: The quick add is only available from the list view. This may change in the future.

**Todo**: We might need to elaborate on creating childrens on the board view. The new children may not be in the current context, so it could be "vanishing".

# Relationships
_Put linked Team/Product story links here_

**Comment by sdash-redhat** [comment]
Refer Interaction Design notes 
slide 68 -> 82 - https://redhat.invisionapp.com/share/6RCWHA1TX

Visual Design Notes: 
https://redhat.invisionapp.com/share/HTCX31SWC
(VD work in progress)
