### ISSUE TITLE
[3] Collect Telemetry events in the dependency editor

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#3239]
#### User Story: https://openshift.io/openshiftio/openshiftio/plan/detail/2210
OSIO should be able to track and collect telemetry events on how the dependency editor is being used.

Acceptance Criteria:
1. System should log: - 
           - How many dependencies added
          - Use of the search
          - Selection of a recommended dependency by analytics
          - Removal of a dependency

**Tasks**

- [x] - Integration with Woopra client side library
- [x] - Track events for **How many dependencies added**
- [x] - Track events for **Use of the search**
- [x] - Track events for **Selection of a recommended dependency by analytics**
- [x] - Track events for **Removal of a dependency**

**Comment by GeorgeActon** [comment]
@jyasveer any update on whether thie PR broke the tests? If it did this should be re-opened.

**Comment by aptmac** [comment]
The PR in question did break the unit tests, more specifically it's failing here [[0]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/analytics.service.spec.ts#L64), because of [[1]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/analytics.service.ts#L87).

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/analytics.service.spec.ts#L64
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/analytics.service.ts#L87

**Comment by jyasveer** [comment]
>> @jyasveer any update on whether thie PR broke the tests? If it did this should be re-opened.

@GeorgeActon This is a weird scenario, the tests in this PR passed in the PR build but it did fail in the commit build. We fixed this now. Tests passed in the build.

**Comment by GeorgeActon** [comment]
@jyasveer Remember to update planner status when work is done
