### ISSUE TITLE
[5] Collect Telemetry events for Launcher wizard

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#3241]
#### User Story: https://openshift.io/openshiftio/openshiftio/plan/detail/2107
Gather telemetry information which will support analysis of User behaviour in the launcher flow to guide improvements to the OSIO User Getting Started experience.

Track events inside the wizard
Runtime selected
Booster selected
Pipepline selected
What arrows used for navigation
How often use overview on left
Duration of session inside wizard
Acceptance:

As a pert of launcher flow, OSIO should be able to capture all the above telemetry events mentioned above at the time of user interaction with the system.
This events should be collected and passed to the woopra database for persistence of the user behavioral analysis data.
To validate, woopra dashboard should show the recently collected data in the analytics graphs and statistics.
Out of Scope: - woopra dashboard

Notes: - All teams should add telemetry (Woopra) so can see component usage

**Tasks**

- [x] - Basic understanding of Woopra and its working.
- [x] -  Integration with Woopra client side library
- [x] - Track events for **Runtime selected**
- [x] - Track events for **Booster selected**
- [x] - Track events for **Pipepline selected**
- [x] - Track events for **What arrows used for navigation**
- [x] - Track events for **How often use overview on left**
- [x] - Track events for **Duration of session inside wizard**
- [x] - Verify the events data in Segment and Woopra in prod-preview environemt
- [x] - Verify the events data in Segment and Woopra in prod environemt

Depends on :- #3511

**Comment by animuk** [comment]
@jyasveer Please refer this links for woopra implementations:
https://www.woopra.com/docs/setup/javascript-tracking-v3/
https://docs.woopra.com/v3.0/reference#intro-javscript-sdk
We need to use the woopra SDK in the JS files to achieve this.

**Comment by jyasveer** [comment]
Thanks @animuk for the info

**Comment by jyasveer** [comment]
@rahulmanchanda
I got to know from @joshuawilson that you are handling the `Woopra` integration in OSIO to capture User's behaviour data for analytics.

I want to understand more about this on the following points below :-
1. Are there any guidelines set to integrate this woopra service
2. Is there a implementation already in OSIO ?
3. As per the config object here https://docs.woopra.com/v3.0/reference#woopraconfig, I also need to know the subscription id and other credentials for the configuration to differentiate us in the woopra server

Thanks in advance
cc @animuk

**Comment by jyasveer** [comment]
Here are some informations regarding this task :-
In the current implementation this is what something is done in OSIO
1. This is the segment application which gives us tags to use. To understand more here is the link
https://segment.com/docs/sources/website/analytics.js/
2. Here the segment tags are implemented as of now: https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/analytics.service.ts
This should help us in getting started
The events mentioned in the code login/logout, context change etc. are just a few ones we are tracking at this point.

**Comment by jyasveer** [comment]
This user story depends on the initial work around `Woopra` and `Segment` integration which is being done by @rahulm0101 . So Rahul, if you could provide a user story link so that i can refer here that would be great.
cc @GeorgeActon @joshuawilson @animuk

**Comment by joshuawilson** [comment]
I don't know of anything @rahulm0101 needs to do first. You should just work together so that he knows what you are doing.

**Comment by jyasveer** [comment]
Here is a doc link for reference
https://docs.google.com/document/d/1Nuvv1gUrz4P51d_LbusipMjKx5nZpyPrO_50s7pN63o/edit#heading=h.ptsipi7o2i8u

**Comment by jyasveer** [comment]
We see events getting registered in woopra website now.

**Comment by jyasveer** [comment]
closing this as this is in prod now.
