### ISSUE TITLE
Improve the launcher flow

### ISSUE THREAD

**Issue by animuk** [openshiftio/openshift.io#3242]
As per User's feedback and telemetry analysis, New Launcher should be adjusted and changed to improve the user experience.

Acceptance:
The new launcher experience area improved and changes in launcher UI, UXD and Backend should be implemented as per the above scenarios.

**Tasks**

- [x] - Accommodating feature and feedback requests.
- [x] - All flows to Add/Import an application/codebase should be using the new Launcher https://github.com/openshiftio/openshift.io/issues/3363
- [x] - Show community badge in missions for selected Runtimes https://github.com/openshiftio/openshift.io/issues/3453
- [x] - Have same value for application name and repo name In new Launcher flow https://github.com/openshiftio/openshift.io/issues/3432
- [x] - In the Create Application overlay page, show a default application name that satisfies the rules for new application name
        Get a suggestion from UXD if we want to show the app name in the create application overlay
- [x] - Show a `cross icon` in the step indicator for the section that is incomplete

**Comment by GeorgeActon** [comment]
Closing because replaced by https://github.com/openshiftio/openshift.io/issues/3863
