### ISSUE TITLE
Board View for Work Items in Planner

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#330]
# Description
As a user, I want to view query results of Work Items in a board view that enables me to browse the resulting Work Items, open views on specific items and letting me update items in a meaningful way.

# Acceptance Criteria
- [ ] The user can switch to a board view of the current context. See the Context Views story for details on the context.
- [ ] The board view displays the Work Items in the context in a column form using cards.
- [ ] The columns resembles Work Item state values. 
- [ ] Each card has meaningful attribute views that identifies the Work Item represented by the card. This is not changed from the current implementation.
- [ ] Entries can be reordered by drag-and-drop vertically in a column, changing the order of execution. 
- [ ] Entries can be moved from one column to another column, effectively setting the Work Item state of the specific Work Item.
- [ ] The user can open the quick preview view from a card.
- [ ] The user can open the detail view from a card.
- [ ] The user can delete a Work Item from a card.

**Note**: This story does not describe the final feature set of the board view. As the board view is one of the central views in the Planner, this will evolve over time. The current story is the feature set we can provide in the first step of that journey.
 
**Note**: This story explicitly does not describe multi-selects and bulk operation. There will be a seperate story on this.

**Note**: This story does not touch the attributes displayed on a card. This will be unchanged from the current implementation. There will be a seperate story on a more dynamic approach on this later.
 
**Todo**: We need to clarify the meaning of the columns.

# Relationships
_Put linked Team/Product story links here_

**Comment by michaelkleinhenz** [comment]
This story needs to be updated with the latest discussion with PM. Nimisha did a document/minutes on it here: https://docs.google.com/document/d/1PL6cv5DfwV2VtkPzSX5_ZUwxYthKQjMKK-ZMbO72xDg/edit#heading=h.ce29mdponpxl

**Comment by michaelkleinhenz** [comment]
There is a document from Todd that describes a redesign of the board view.
https://docs.google.com/document/d/1VzcxKV5EVhBcVS_OvUj9oXfuKdK_tVL8SINSJbFIOCQ/edit#heading=h.68nstgzglraa

**Comment by michaelkleinhenz** [comment]
We had some good feedback from a community member who suggested that it would be helpful to have (an optional) Review stage that would sit between In Progress and Complete.
@bmicklea 

> For

 organizations which are using a gitflow and pull request paradigm this provides important visibility, plus (at some point) we could theoretically automate the movement of a work item to that stage based on the creation of a PR for the branch.

**Comment by michaelkleinhenz** [comment]
@qodfathr 

> The roadmap calls for a highly customizable board -- both in terms of columns and swim lanes. Note that there are all sorts of challenges which need to be considered, not the least of which is what does it mean to move a WI from one column to another. In other words, does moving a WI change its state? If yes, what are the rules for those state changes? What if the columns do not match the available states for the WIT 1:1? Alternatively, perhaps some columns imply the existence of a label on a WI.
These are all valid models, and we are looking to unify them. So, yes, on the roadmap, but lots of work to be done to clarify what this will look like. We'll be looking at this deeper in a couple of months.

**Comment by nimishamukherjee** [comment]
We have a new epic to track board view - https://openshift.io/openshiftio/Openshift_io/plan/detail/395
