### ISSUE TITLE
Implement capacity flag per cluster to rate limit tenant resources for che and jenkins

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#3320]
To avoid overloading clusters we need a way to limit total amount of che and jenkins instances running on each cluster.

- [ ] Capacity app sets capacity values to cluster config for Auth service
- [x] Implement flag in Cluster API in auth - https://github.com/fabric8-services/fabric8-auth/pull/477
- [x] Expose flag via Tenant Service 
- [x] Expose flag via User Services
- [x] jenkins proxy should not unidle jenkins flag if returning full - https://github.com/fabric8-services/fabric8-jenkins-idler/issues/223
- [x] jenkins proxy page should show message explaining capacity is full -https://github.com/fabric8-services/fabric8-jenkins-proxy/issues/243
- [x] Che should not start new instances/workspaces when flag is returning full 
- [x] Che shuold not resume existing workspaces when flag is returning full
- [x] Before creating / starting workspace via Codebases UI need to check cluster capacity, show error 
message and prevent workspace startup https://github.com/openshiftio/openshift.io/issues/3426

**Comment by ibuziuk** [comment]
Ideally, capacity verification for che should be done on both che-starter & che host sides that would cover workspace creation via Codebases UI & dashhboard

**Comment by chmouel** [comment]
@ibuziuk  I'd rather have the capacity verification and decision be done externally tho, at least for us (jenkins) we don't have to keep track and persist it and allow have the sd/pm team tweaking it easily,

**Comment by aslakknutsen** [comment]
@chmouel the actual calculations etc etc is done externally. All you (jenkins proxy/idler) should care about is a boolean flag from tenant service.

**Comment by alexeykazakov** [comment]
Added:
 - [ ] Capacity app sets capacity values to cluster config for Auth service

**Comment by pradeepto** [comment]
@maxandersen @chmouel This feels like an epic to me. Can this issue be broken into smaller tasks and be done individually?

**Comment by pradeepto** [comment]
And since it is tagged as P0, so can this whole issue be actually completed properly in next 7 days?

**Comment by aslakknutsen** [comment]
@pradeepto Spawn out sub tasks as you see fit

**Comment by ibuziuk** [comment]
@aslakknutsen @alexeykazakov PR for che-starter with suport of new property for tracking cluster capacity - https://github.com/redhat-developer/che-starter/pull/303
Currently tracker is dummy [1], so please let me know once API would be exposed on wit side

[1] https://github.com/redhat-developer/che-starter/pull/303/files#diff-73b76563f84c688f25035a1ee9fd691cR21

**Comment by aslakknutsen** [comment]
@kishansagathiya Depending on the entry point I guess one would need to tell the user something. A GitHub webhook could just wait, but a jenkins.proxy request from the user side should probably say something about not being able to start jenkins now due to X

**Comment by sbose78** [comment]
` Implement flag in Cluster API in auth - fabric8-services/fabric8-auth#477`  is merged and available in prod-preview.

**Comment by alexeykazakov** [comment]
> Implement flag in Cluster API in auth - fabric8-services/fabric8-auth#477 is merged and available in prod-preview.

It has been tested in prod-preview and now available in prod too.

**Comment by sthaha** [comment]
@maxandersen @aslakknutsen wouldn't all services polling the flag and scaling their services/pods still lead to over allocation as the state (`cluster-capacity-exhausted`) could change after the flag was queried? Are we trying to compensate this by setting the flag before the  capacity is fully reached?

**Comment by ibuziuk** [comment]
@joshuawilson @ashumilova will you be able to give a hand with https://github.com/openshiftio/openshift.io/issues/3426 ?

**Comment by ibuziuk** [comment]
PRs for handling `cluster-capacity-exhausted` for che-starter & rhche:
- https://github.com/redhat-developer/che-starter/pull/304
- https://github.com/redhat-developer/rh-che/pull/661

**Comment by sthaha** [comment]
### Proxy & Idler update

- Idler (deployed to prod-preview) now honours the `cluster-capacity-exhausted` flag and wakes up Jenkins only if the flag isn't set (`false`). 
- The patch to show the "Capacity full" when user visits https://is in progress and should be in prod-preview today

**Comment by ibuziuk** [comment]
validation of capacity is also done on codebases UI side thanks to @corinnekrych :+1: 

![image](https://user-images.githubusercontent.com/1461122/39629500-b587d4b2-4fac-11e8-813d-be0d6a7f5537.png)

**Comment by surajssd** [comment]
This can be safely closed, I think since it is done?

**Comment by sbose78** [comment]
`Capacity app sets capacity values to cluster config for Auth service` - looks like its automated from zabbix metrics. So we can close this.
