### ISSUE TITLE
Drop jenkins-mvn-local-repo PVs

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#3333]
From @jfchevrette [HK](https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1690)

```
now that our jenkins slave pods are not using the jenkins-mvn-local-repo PV anymore can we go ahead and delete all the PVCs and claim back the storage costs?
```

- [ ] Get the change to f8-tenan-jenkins merged https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/80
- [ ] Observe the new provisioned (or resetted) tenants working properly without the PV
- [ ] Work on a script to remove it from the cluster

**Comment by jfchevrette** [comment]
@chmouel it looks like the tests on fabric8-services/fabric8-tenant-jenkins#80 are failing for some reason?

**Comment by jfchevrette** [comment]
The PVs/PVCs have been deleted from the clusters. This should get done ASAP to avoid provisioning more of this PV when new tenants are initialized.

**Comment by jaseemabid** [comment]
@jfchevrette "Change author (Jaseem Abid, me!) is not a collaborator on the project, failing build until we support the [test] comment"

**Comment by jaseemabid** [comment]
I've a PR ready, but I'm unable to deploy this image to prod and test it. Blocked on https://github.com/openshiftio/openshift.io/issues/3408

**Comment by jaseemabid** [comment]
I've a PR ready, but I'm unable to deploy this image to prod and test it. Blocked on https://github.com/openshiftio/openshift.io/issues/3408
