### ISSUE TITLE
Viewing and Updating the Current Iteration

### ISSUE THREAD

**Issue by michaelkleinhenz** [openshiftio/openshift.io#336]
# Description
As a user, I want to see and update the current Iteration from the context views.

# Acceptance Criteria
- [ ] The user can set optional start and end dates for an Iteration.
- [ ] The user can set an "active" flag on an iteration. The active flag has a higher significance as the automatic calculation from the date.
- [ ] If a start and end date is set, the iteration is considered "active" when the current date is in that timeframe.

**Note**: The user can **not** force-deactivate an iteration (for now).

**Note**: There can be more than one iteration be active at any one time. This is due to technical reasons and the changing req's when the teams are added to the system.

**Note**: Later, there will be exactly one active Iteration per **team**. But as we do not have teams right now, we fall back to one active iteration per Space for now.

**Note**: Having exactly one active Iteration is necessary because there are operations like "move this item to the active Iteration".

**Todo**: We may need to rethink the conflict case for "active".
 
# Relationships
_Put linked Team/Product story links here_

**Comment by nimishamukherjee** [comment]
> If a start and end date is set, the iteration is considered "active" when the current date is in that timeframe.

- Does the "active" flag get auto-updated on iterations based on their start date or it needs to be set manually by the user?
- If an iteration is no longer active where does it move - future iterations or closed iterations?
- If an iteration is no longer active, what is the impact on the associated work items?

**Comment by michaelkleinhenz** [comment]
Yes an no. An iteration is "active" or "current" when the current date is in the timeframe. The "physical" active flag can just override this:

in timeframe && active flag -> active
in timeframe && !active flag -> active
not in timeframe && active -> active
not in timeframe && !active -> inactive

But I agree that we should talk about this. The handling appears clunky to me now.

The "future" or "past" iterations panels will be removed.

No impact on Work Items for now when an iteration is closing. For now.

**Comment by michaelkleinhenz** [comment]
Note: removed "only one active iteration" and "force-deactivate" due to technical considerations. These req's will be added back in a later story.
