### ISSUE TITLE
[8] Create a blank booster for each Runtime.

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#3400]
#### User Story:

As an OSIO user, I will be able to create an application from a blank booster for given runtime.

#### Description:

A user will be able to create an application using blank booster and can add or remove packages for his application.

#### Tasks:

- [x] Create a blank booster repository.
    - [x] create a default jenkinsfile for each runtime.
        - [x] springboot jenkinsfile
        - [x] vert.x jenkinsfile
        - [x] wildfly-swarm jenkinsfile
    - [x] create a default pom.xml with core dependencies of runtime
        - [x] springboot pom.xml
        - [x] vert.x pom.xml
        - [x] wildfly-swarm pom.xml
    - [x] create an openshift template for each runtime.
        - [x] springboot openshift template
        - [x] vert.x openshift template
        - [x] wildfly-swarm openshift template

**Comment by sunilk747** [comment]
Here is the link to all the blank booster for each runtime:
- [vert.x](https://github.com/fabric8-analytics/vertx-blank-booster.git)
- [springboot](https://github.com/fabric8-analytics/springboot-blank-booster.git)
- [wildflyswarm](https://github.com/fabric8-analytics/wfswarm-blank-booster.git)
