### ISSUE TITLE
[5]Perform load testing on all the APIs used by dependency editor

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#3401]
### User story: https://openshift.io/openshiftio/openshiftio/plan/detail/2259
As an OSIO developer I would like to figure out the dependency editor resource requirement so that it support 500 concurrent users.

### Description
In this sprint we plan to perform load testing on all the APIs used by dependency editor and observe if it is able to support 500 concurrent users and list out the various shortcomings which preventing dependency editor from achieving the desired target.

### Task list
- [x] Perform load testing on endpoint `api/v1/depeditor-analyses/?persist=false`
- [x] Perform load testing on endpoint `api/v1/license-recommender`
- [x] Perform load testing on endpoint `api/v1/depeditor-cve-analyses`
- [x] Perform load testing on endpoint `api/v1/component-search/${component}`
- [x] Perform load testing on endpoint `api/v1/categories/{runtime}`
- [x] List out the various shortcomings present in dependency editor and create a document around it.

**Comment by sunilk747** [comment]
Here is the report on load testing of above API endpoints - https://docs.google.com/spreadsheets/d/1a-1wYGpkuw7BWpguhQTBUnEHOEY5EQYnaJ_GSpH_FNQ/edit?usp=sharing
