### ISSUE TITLE
[3] Backend changes in Launcher-backend to support blank boosters.

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#3402]
#### User Story:

As an OSIO user, I will be able to create an application from a blank booster for given runtime.

#### Description:

A user will be able to create an application using blank booster and can add or remove packages for his application.

#### Tasks:

- [ ] make `runtime` input as an optional
- [ ] make `runtimeVersion` as an optional input
- [ ] implementation of to make changes in configs of blank booster.
- [ ] create unit test-cases for the blank boosters changes.

**Comment by animuk** [comment]
not needed. closed
