### ISSUE TITLE
[8+2]New analytical model to extend companion recommendation for the whole Maven Ecosystem

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#3506]
**Planner** [2149](https://openshift.io/openshiftio/openshiftio/plan/detail/2149) **and** [2150](https://openshift.io/openshiftio/openshiftio/plan/detail/2150)

## Description:
Extend the recommendations engine to support entire maven ecosystem and not the current subset of Vertx, Spring-boot and Wildfly.

## Task List:
- [x] Use Bigquery to collect the pom.xml
- [x]  Extract the EPs from the pom.xml and create the `manifest.json` list 
- [x] Extract the EPs from the pom.xml and create the `EPV` list
- [x] Standalone model on dev cluster- First iteration of training.
- [x] Testing/Accuracy Evaluation framework for the model

## Acceptance Criteria
Standalone Model is trained and evaluated on maven data.

**Comment by sara-02** [comment]
PoC Code can be tracked here:
https://github.com/fabric8-analytics/poc-maven-stack-analysis

**Comment by sara-02** [comment]
The scoring api is available at the devcluster here, http://bayesian-hpf-insights-maven-hpf-insights.dev.rdu2c.fabric8.io
sample POST
```
[
	{
            "ecosystem": "maven",
			"package_list": ["org.springframework.boot:spring-boot-actuator"]		
	} ]
```

**Comment by sara-02** [comment]
Closing this issue, a part of it will be continued in this sprint, as part of this issue
https://github.com/openshiftio/openshift.io/issues/3700
