### ISSUE TITLE
[8] Create a basic structure to support Node in launcher

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#3512]
## User Story

As an OSIO user, I will be able to create a project from a nodejs booster.

## Description:
As we are adding support for the node, to make it compatible with launcher we need to add generic classes for nodejs and we also need to add an extra field in OSIO endpoint to support this.
## Acceptance criteria
Node support in the launcher.

## Task List:
- [x] Create a node dependency param converter.
- [x] Create a node dependency param provider.
- [x] Create a Node Model and helper methods.
- [x]  Add an extra field in OSIO endpoint.
- [ ] Adding Unit test cases for the above implementation.

**Comment by bartoszmajsak** [comment]
@animuk I only see updates on the checklist in the issue description - can you point me to the code changes done if there were any? Was that work related to `launcher-backend` project as the title suggest?

**Comment by animuk** [comment]
@bartoszmajsak I dont think, those work on the checked ones are committed to any project.  this story might not be relevant right now. @sunilk747 please close this if it is not needed.

**Comment by GeorgeActon** [comment]
@animuk @sunilk747 @ravsa this story is NOT in Planner so it is definitely not in our plan any longer and not being worked on.

**Comment by ravsa** [comment]
I'm no longer is working on this so closing this issue.
