### ISSUE TITLE
[8] Update the user about the resource quota available.

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#3514]
####User Story: https://openshift.io/openshiftio/openshiftio/plan/detail/2253
As a user of OSIO, I should be informed about the resources available in order to proceed to create a application.

### Description
As seen in design link in parent issue, In case of OSIO Users exhausted the usage quota limit at Openshift , then Users should be prevented for creating another new application from Openshift.io launcher as application creation will fail in this scenario. 

**Acceptance:**
- OSIO Users will see an overlay explaining users about the insufficient resource available to create and deploy any new application at Openshift.
- OSIO Users should be notified about the recommended actions to be taken in this scenario.

**Tasks**
- [ ] Work with UXD to have a clear understanding of how the UI flow would look like
- [ ] Work with UXD to understand the trigger points to test the resource quota in UI
- [ ]  Implement the UI as per UX

This can be followed in this task https://github.com/openshiftio/openshift.io/issues/3346

**Comment by animuk** [comment]
@GeorgeActon As discussed with @krishnapaparaju Build team needs to handle this particular task going forward. So, We might be closing this as we are not actively working on this shortly.

**Comment by animuk** [comment]
Closing this after discussion with @krishnapaparaju
