### ISSUE TITLE
[8] Integrate Dependency Editor into Launcher flow as an optional step

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#3515]
### User Story: https://openshift.io/openshiftio/openshiftio/plan/detail/2180
As an openshift.io user, He should be able to see Dependency Editor in launcher flow as an internal feature.

### Acceptance:

- OSIO Users should be able to see Dependency Editor in launcher flow as an experimental feature.
- OSIO Users should able to search the relevant project dependencies from the dependency editor.
- OSIO Users should add the chosen selected dependencies to the quickstarts.
- Dependency Editor should show the insights about components and securities about the final set of dependencies chosen.
- OSIO Users should able to proceed with new application flow with the added new dependencies.

### Task

- [x] Add dependency editor as a dependency for ngx-launcher.
- [x] Bring in feature flags to ensure it can be initially seen only to internal users.
- [x] Integrate the modified ngx-launcher with fabric8-ui and test the flow.

**Comment by sanketpathak** [comment]
[Tasks](https://github.com/fabric8-analytics/fabric8-analytics-dependency-editor/issues/84
)

**Comment by GeorgeActon** [comment]
@arunkumars08 Get UXD to review the implementation if they have not already done so.

**Comment by joshuawilson** [comment]
@GeorgeActon if you want USD you can ping them with @openshiftio/uxd-team

**Comment by mindreeper2420** [comment]
It looks like the PR was merged 2 days ago, if I'm looking at the correct one?

**Comment by arunkumars08** [comment]
Closing the issue. The PR for the same is merged and the changes are already in production as an internal feature.
