### ISSUE TITLE
[8] CICD and Semantic release for Dependency editor

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#3521]
### Description: https://openshift.io/openshiftio/openshiftio/plan/detail/2271

As a developer, I should be able to seamlessly develop and deploy changes as and when pushed to master.

### Acceptance Criteria

- Pushing changes to master branch should release a new NPM version and release it to NPMJS.org
- Post that, it has to create pull requests to all the repositories that has this as a dependency (eg. ngx-launcher has fabric8-analytics-dependency-editor as a dependency)

### Tasks

- [x] - Bring in script files to handle the release when the changes are pushed to master.
- [x] - Use Semantic release to control the type of release
- [x] - Add webhooks for the two jobs
- [x] - CICD related changes.
- [x] - HK issue to add centos-ci as the collaborator https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1946
