### ISSUE TITLE
[8] Integration tests for dependency editor

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#3523]
### Description

As a developer, I need to make sure integration tests are run on every change pushed to master in order to ensure the stability of the application.

### Acceptance Criteria

- Run integration tests on each PR as well as push to master.

### Tasks

- [ ] - Bring in integration tests related infra.
- [ ] - Write tests to make sure the functionalities are covered.
- [ ] - Bring in CICO scripts to trigger tests on every PR
- [ ] - Bring in CICO scripts to trigger tests on every push to master.

**Comment by bartoszmajsak** [comment]
@animuk @GeorgeActon are there any tests created or will be?

**Comment by animuk** [comment]
@bartoszmajsak this is a backlog. tests yet to be created
