### ISSUE TITLE
Application Wizard

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#353]
# Description
As a user, I want to be able to automatically generate an application in a way that is easy to follow.

# Acceptance Criteria
- [ ] The quickstarts that made available should work all the way through the system.
- [ ] The app-wizard should be clear and easy to understand.

**Note**: 
Experience 1608E095 [P0] - create applications
Experience 1608E177 [P*] - The “new project wizard” end-to-end experience

# Relationships
_Put linked Team/Product story links here_

# Related issues
- [ ] Replace wizard framework with the angular wizard implemented in ngx-widgets [#182](https://github.com/fabric8-ui/fabric8-ui/issues/182) 
- [ ] Space wizard needs to select space template. [#390](https://github.com/fabric8-ui/fabric8-ui/issues/390)
- [ ] how should we allow users to pick the upstream quickstarts in addition to the RHOAR ones? [#1302](https://github.com/fabric8-ui/fabric8-ui/issues/1302)
- [ ] after creating a new app, the `Analyze` tab is kinda confusing as you don't really get to see the new app/pipeline [#1318](https://github.com/fabric8-ui/fabric8-ui/issues/1318)
- [ ] No way to recover from *cough* accidental *cough* OpenShift project deletion [#1352](https://github.com/fabric8-ui/fabric8-ui/issues/1352)
- [ ] Tests java.util.concurrent.TimeoutException [#1358](https://github.com/fabric8-ui/fabric8-ui/issues/1358)
- [ ] Doing an import codebase and selecting the default options seems to kick off master builds continually [#1362](https://github.com/fabric8-ui/fabric8-ui/issues/1362)
- [ ] created jenkinsfile refer to @master of library files [#1365](https://github.com/fabric8-ui/fabric8-ui/issues/1365)
- [ ] the Finish button should not need to invoke Validate again if there's been no change [#1380](https://github.com/fabric8-ui/fabric8-ui/issues/1380)
- [ ] App Wizard: if `KeyCloakFailureException` is returned lets display a button to link the user to the `Update Profile` page [#1405](https://github.com/fabric8-ui/fabric8-ui/issues/1405)
- [x] Markdown not rendering on pipelines selector page [#1410](https://github.com/fabric8-ui/fabric8-ui/issues/1410)
- [ ] on the new app quickstart wizard, if you type a name then hit Finish it validates but doesn't finish [#1440](https://github.com/fabric8-ui/fabric8-ui/issues/1440)
- [ ] Springboot CRUD quickstart failed to build [#1466](https://github.com/fabric8-ui/fabric8-ui/issues/1466)
- [ ] Create Space workflow does not throw you into the new space [#1485](https://github.com/fabric8-ui/fabric8-ui/issues/1485)
- [ ] New project creation should be in a transaction - so that users are not left to "clean up" after a failure [#1499](https://github.com/fabric8-ui/fabric8-ui/issues/1499)
- [ ] Create workspace failing on openshift.io - 504 error reported [#1515](https://github.com/fabric8-ui/fabric8-ui/issues/1515)
- [ ] The only Che stack that is used is the plain java one [#1534](https://github.com/fabric8-ui/fabric8-ui/issues/1534)
- [ ] Intermittent error - codebase not created when a new project is created [#1552](https://github.com/fabric8-ui/fabric8-ui/issues/1552)
- [ ] Quickstart wizard should have a back button [#1555](https://github.com/fabric8-ui/fabric8-ui/issues/1555)
- [ ] Cannot deselect checkbox options in QuickStart Wizard Step 4 [#1556](https://github.com/fabric8-ui/fabric8-ui/issues/1556)
- [ ] Pipeline display in OpenShift.io seems to not be connected to Jenkins builds (issue limited to a specific user account) [#1563](https://github.com/fabric8-ui/fabric8-ui/issues/1563)
- [ ] Build configuration appears twice in Create a new Starter project wizard [#1593](https://github.com/fabric8-ui/fabric8-ui/issues/1593)
- [ ] In promoting project to run, timing delays may cause user confusion as links are displayed before the corresponding assets are ready [#1619](https://github.com/fabric8-ui/fabric8-ui/issues/1619)
- [ ] Not reproducible - user accounts can be rendered unusable - "Already created BuildConfig" cited in logs - no build configs found [#1625](https://github.com/fabric8-ui/fabric8-ui/issues/1625)
- [ ] Intermittent but recurring problem - codebase not populated with project code [#1635](https://github.com/fabric8-ui/fabric8-ui/issues/1635)
- [ ] Creating a new project in a space results in new builds being created for all other projects in the space [#1642](https://github.com/fabric8-ui/fabric8-ui/issues/1642)
- [ ] Creating a new project results in Bayesian error [#1644](https://github.com/fabric8-ui/fabric8-ui/issues/1644)
- [ ] Error in pushing project to stage caused by timeout reported as success in OSIO UI [#1648](https://github.com/fabric8-ui/fabric8-ui/issues/1648)
- [ ] Create a new project - Secured Spring Boot Tomcat Quickstart - fails [#1660](https://github.com/fabric8-ui/fabric8-ui/issues/1660)
- [ ] Create a new project - Secured Vertx - Rest & Red Hat SSO Quickstart - fails [#1664](https://github.com/fabric8-ui/fabric8-ui/issues/1664)
- [ ] Failures in staging should prevent deployment to run - but they aren't [#1666](https://github.com/fabric8-ui/fabric8-ui/issues/1666)
- [ ] Create a new project - Vert.x CRUD - fails [#1667](https://github.com/fabric8-ui/fabric8-ui/issues/1667)
- [ ] Create a new project - Spring Boot CRUD - fails [#1668](https://github.com/fabric8-ui/fabric8-ui/issues/1668)
- [ ] Create a new project - Wildfly CRUD - fails [#1670](https://github.com/fabric8-ui/fabric8-ui/issues/1670)
- [ ] Create a new project - Wildfly Swarm - fails [#1671](https://github.com/fabric8-ui/fabric8-ui/issues/1671)
- [ ] Create a new project - Wildfly HTTP - fails [#1672](https://github.com/fabric8-ui/fabric8-ui/issues/1672)
- [ ] Create new project - WildFly Swarm - Health Checks - fails [#1673](https://github.com/fabric8-ui/fabric8-ui/issues/1673)
- [ ] Create new project - WildFly Swarm - REST and RH SSO - fails [#1674](https://github.com/fabric8-ui/fabric8-ui/issues/1674)
- [ ] User is now warned when Che/Openshift quotas are reached - https://github.com/fabric8-ui/fabric8-ui/issues/1681
- [x] Import repo wizard should show an error when no repos are selected -
 https://github.com/fabric8-ui/fabric8-ui/issues/1683

**Comment by joshuawilson** [comment]
@catrobson do you think the app-wizard needs UX to look at it again?

**Comment by catrobson** [comment]
@joshuawilson yes.

**Comment by joshuawilson** [comment]
For the quickstarts we need a way to fix them to work. Consider updating them to skip the tests that fail in OSIO.

**Comment by joshuawilson** [comment]
Closing to track issues individually.
cc @corinnekrych
