### ISSUE TITLE
Platform extensibility

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#354]
# Description
As a user, I want to be able to add my own components to OSIO. I also want to configure which components I have in my view and where they are displayed. It should be personalizable.

# Acceptance Criteria
- [ ] Developers should be able to create an extension that plugs into the OSIO framework.
- [ ] Approved extensions will be made available to all users of OSIO.
- [ ] The user should be able to select the widgets they want on the dashboards and place them where they want them.
- [ ] The user should be able to select the features they want included. This could mean that they remove Planner or Pipelines. Or just the board view of the Planner. 

**Note**: 
Experience 1702E270 [P0] -- Screen Sets
Experience 1702E271 [P0] -- Space/Team Screen Set
Experience 1702E272 [P0] -- Entity Screen Set
Experience 1702E273 [P0] -- Screen extension
Experience 1702E274 [P0] -- Screen extension extensibility point
Experience 1702E275 [P0] -- Dynamic extensions
Experience 1702E277 [P0] -- Composite extension
Experience 1702E278 [P0] -- What an extension can and cannot do

# Relationships
_Put linked Team/Product story links here_

**Comment by joshuawilson** [comment]
tracking in planner
