### ISSUE TITLE
Mockups and samples for API breaking changes AI use case

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#3545]
### Description

The idea with this use case is for analytics to better help developers to work with API breaking changes so they can stay up-to-date with the latest versions of their dependencies.

This involves predicting the fix for an API breaking change by using docstrings and code understanding to match the "intent" of functions and assign them a similarity score to figure out which new function 'b' works the same as function 'a', and printing migration path information. 

### Acceptance Criteria

Mockups should be up for PM review in invision.

### Task List

- [x] Come up with sample cases for the use case, and its supporting evidence (@rootavish)
- [x] Upload the use case into a Github repo for UX to import into Che. (@rootavish)
- [x] Mockups to be made and uploaded to invision (@parvathyvr)

#### Planner fundamental: https://openshift.io/openshiftio/openshiftio/plan/detail/2163

**Comment by parvathyvr** [comment]
Invision link for the mockups : https://redhat.invisionapp.com/share/4BJ3MCL9D3G#/298240619_Table_Of_Contents .Feel free to comment for any changes.

**Comment by rootAvish** [comment]
Closing as this is done.
