### ISSUE TITLE
Increase unit test coverage and complete training code in npm-insightes repo

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#3547]
### Description

The newly created https://github.com/fabric8-analytics/fabric8-analytics-npm-insights still needs the training job code and the aggregator scripts for S3 data, initial work around the same was done in the last sprint however some items to merge it are still pending.

In addition to that we need to add the coverage script to it so we can monitor increase unit test coverage.

### Acceptance Criteria

- [x] Unit test coverage for the scoring pieces should be greater than 90%

### Task List

- [x] Add `pytest-cov` coverage checking to the fabric8-analytics-npm-insights-repo
- [x] Read up on how to unit test tensorflow code
- [x] Complete the estimator code for CVAE
- [x] Unit test all the existing pieces and increase coverage from the previous numbers 

Partially linked to: https://openshift.io/openshiftio/openshiftio/plan/detail/2097

**Comment by sivaavkd** [comment]
@rootAvish task makes sense, thanks

**Comment by rootAvish** [comment]
PR is raised here: https://github.com/fabric8-analytics/fabric8-analytics-npm-insights/pull/28
