### ISSUE TITLE
Provide flexibility to ingest data from any 3rd party public repo of supported types on OSIO

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#3560]
Planner: https://openshift.io/openshiftio/openshiftio/plan/detail/2346

### Description

Create a RESTful service that would hold information about available packages in pre-configured repositories (multiple repositories per ecosystem need to be supported).

### Acceptance Criteria

- [x] Create data model service ready

- [x] Flask service with endpoints to ingest the data

### Task List

- [x] set up a new repository for the service

- [x] design database schema (with multiple repositories per ecosystem in mind)

- [x] create data model in SQLAlchemy

- [x] create initial Alembic migration scripts

- [x] Dockerize Alembic part and the service itself
