### ISSUE TITLE
[8] Standardize Booster Readiness Guidelines

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#3566]
#### Description: https://openshift.io/openshiftio/openshiftio/plan/detail/2348

As an OSIO Developer, I will be able to create a new booster and that will be able to add a booster in booster-catalog that will be available on osio.

As we are adding new boosters in OSIO and planning to improve/troubleshoot issues in existing booster this document will help to Booster owners and OSIO owners understand the end to end process (from creating booster to successfully running booster on OSIO platform)

**Acceptance:**
- A detailed document with the proper guidelines to create booster from scratch.
    - https://docs.google.com/document/d/1dk0VIf854_FbyvqNbR8MdrzSD1gl91FcC3nzV3-qCtk/edit?usp=sharing
- By following the document  booster should be able to pass these steps in openshift.
    - It should be able to pass CD Build (Jenkins) successfully.
    - It should be able to deploy on __Stage__  and __Run__ successfully.
    - It should be able to generate working links for  __Stage__  and __Run__.
    - A user should be able to open booster in the _Che_ workspace.
    - A user should be building the project using Maven in the _Che_ terminal window.
    - A user should be able to access preview URL
    - A user should be able to run and debug project from the _Che_ menu.
    - A user should be able to modify the project source code in _Che_  and rebuild, redeploy should work properly.
    - A user should be able to see changes in  __Stage__  and __Run__ links.

#### Tasks:

- [x] Create a booster catalog structure.
- [x] Booster-catalog `booster.yaml` file description.
- [x] How to declare runtime, missions and runtimeVersions in `booster.yaml` file.
- [x] All necessary files to make boosters successfully build  (CD jenkins).
- [x] Important dependencies to added in pom.xml to make booster build works.
- [x] Description for  the booster file structure.
- [x] Description for the files in `.openshiftio` directory.
- [ ] Description for the openshift templates / jenkins templates.
- [ ] Commands and flags to `build`, `deploy` and `run` boosters on OSIO/Che
- [x] Description for built-in automated tests.
- [x] Booster Testing flow.

**Comment by ldimaggi** [comment]
When you refer to redeploy - you're really talking about auto-recompile and auto-redeploy.

**Comment by ldimaggi** [comment]
See https://github.com/openshiftio/openshift.io/issues/2399 for the same type of list - with finer grained detail. I think that the lists are in sync.

**Comment by GeorgeActon** [comment]
@ravsa @animuk The acceptance criteria for **this story** should include the provision of a set of guidelines. That is the outcome we are looking for. Put a link to the document being produced in the  acceptance criteria section.

**Comment by ravsa** [comment]
I will add the link to the document once it is finished.

**Comment by GeorgeActon** [comment]
@ravsa  the acceptance criteria above is supposed to tell us how we would know this story is complete. The way i will know the story is complete is if you state that a documented set of guidelines is the final outcome as the last part of acceptance criteria

**Comment by ravsa** [comment]
yes @GeorgeActon, you are absolutely right. I'll change this.

**Comment by animuk** [comment]
As we completed the document stating the guidelines. This completes the user story.
