### ISSUE TITLE
Move Auth out of WIT

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#357]
# Description
- As a developer of the system, I want to be able to work on Auth in it's own repo.
- Delegate all Auth related calls from WIT to Auth

# Acceptance Criteria
- [x] Delegate space resource creation from WIT to AUTH  https://github.com/fabric8-services/fabric8-auth/issues/27
- [ ] Delegate userProfile+login requests from WIT to AUTH https://github.com/fabric8-services/fabric8-auth/issues/26
- [ ] Copy over all user/identity information from WIT DB to AUTH DB https://github.com/fabric8-services/fabric8-auth/issues/25

**Note**:

# Relationships
_Put linked Team/Product story links here_
https://github.com/fabric8-services/fabric8-auth/issues/20

**Comment by alexeykazakov** [comment]
Here is the related issue in the Auth repo - https://github.com/fabric8-services/fabric8-auth/issues/20

**Comment by joshuawilson** [comment]
You don't have to close it but you can't stay here. Please close or move to backlog or next sprint.

**Comment by alexeykazakov** [comment]
Done.
