### ISSUE TITLE
[5] Create a service to generate effective POM

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#3584]
#### User Story:

As an OSIO Developer, I will be able to get effective POM for normal POM.

#### Description:
In `Dependency-Editor` we are passing boosters or other maven projects which might not have an effective POM and `Dependency-Editor` further calls the Analytics APIs for insights and all which requires effective POM to process. So the goal is to create a service to automate the process of generating the effective POM from the normal POM and caching it to S3 and keep on watching the changes in existing boosters and update the cache in a fixed time interval.

**Acceptance:**
- It should be able to effectively watch the change in boosters.
- It should be able to store the POM using hash code.
- It should be able to fetch POM using hash code.
- It should be able to update the POM if the booster is updated.

#### Tasks:
- [ ] Implement a logic to add and remove new booster cache in the S3 bucket.
- [ ] Create a service to keep watching the changes.
    - [ ] changes in booster-catalog
    - [ ] changes in boosters
- [ ] Implement a logic to generate effective POM from normal POM.
- [ ] Create a funcationality to read/write the data from S3.
- [ ] Containerize the service and host on dev-cluster
- [ ] Create a scheduled cron job.
