### ISSUE TITLE
OSIO's behaviour should be well defined when visiting any feature belonging to another user

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#3638]
**User story:**

As an OSIO user, if I choose to visit anything directly related to another user's account, I should not be able to access any functionality that was only destined for the other user. 

**Description:**

As it stands, many features are available to users when they visit a foreign space or profile. Here, "foreign" is defined as "belonging to another OSIO user". Of the various functionality available in foreign spaces or profiles at the time of writing, some result in unhandled bugs whereas others allow for unprivileged access and changes to foreign accounts. Moreover, discussion of this matter is scattered and the solutions to these problems are left undefined. There has been work to disable features in the space dashboard, but broader decisions should be made before moving ahead with any outstanding issues. 

**Acceptance:**

- A detailed list of what should and should not be available to a user visiting anything owned by a foreign account
- For the aforementioned list, a decision on how these problematic features should be dealt with 
- Definition of an overall structure or service that can be applied to facilitate dealing with these problematic features

**Tasks:**

- [x] Features should not be available when visiting another user's profile https://github.com/openshiftio/openshift.io/issues/3635
- [ ] Features should not be available when visiting another user's space's create tab https://github.com/openshiftio/openshift.io/issues/3634 
- [ ] Features should not be available when visiting another user's space's pipelines tab https://github.com/openshiftio/openshift.io/issues/3636
- [ ] What features should not be available when visiting another user's/space's deployments tab?https://github.com/openshiftio/openshift.io/issues/3637 
- [x] User should not be able to add description to another users space https://github.com/openshiftio/openshift.io/issues/3423
- [x] User should not be able to add to other users space through my work items widget https://github.com/openshiftio/openshift.io/issues/3397
- [x] User should not be able to add to other users space through pipelines widget https://github.com/openshiftio/openshift.io/issues/3386

**Comment by chrislessard** [comment]
It wasn't really clear to me what to do about planner, so I havent documented it.
