### ISSUE TITLE
View model for teams, security groups, and users (13)

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#3653]
### Description
Decide on the view model for teams, security groups, and users so we have a consistent UI model across these designs for spaces and organizations.

### Verification Criteria
- [ ] Designs created for a page layout that can be used for the viewing of a list of teams, security groups, and people/users/members (terminology tbd).
- [ ] Designs created for inline edit if needed in coordination with story #3654
- [ ] Designs created for viewing details of a list item if needed in coordination with story #3654
- [ ] All designs captured in sketch, added to Google Drive, and posted to InVision
- [ ] Designs shared with UXD team members throughout design process for collaboration and discussion
- [ ] Designs shared with Auth, Platform team in meetings where possible, and with devtools-saas at appropriate times
- [ ] Once designs are finalized, determine how to provide in InVision along with #3654 and #3652 in a way that will be implementable by development.  Create final specs for development.

**Comment by lwrigh** [comment]
Link to the space permissions for reference: https://github.com/openshiftio/openshift.io/issues/2910

**Comment by muruGanesan** [comment]
#3142  
Teams (with users & permission) will be handled here.

**Comment by sdash-redhat** [comment]
Was taken care of by Michael in his holistic approach to team, security groups and users
