### ISSUE TITLE
Create and Edit model for Users, Teams, Security Groups (13)

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#3654]
### Description
Decide on the creation and edit model for teams, security groups, and users so we have a consistent UI model across these designs for spaces and organizations.

### Verification Criteria
- [ ] Designs created for a page layout that can be used for the creation and editing the objects of teams, security groups, and people/users/members (terminology tbd).
- [ ] Collaborate with designer on #3653 for inline edit if needed
- [ ] Collaborate with designer on #3653 for viewing details of a list item if needed 
- [ ] All designs captured in sketch, added to Google Drive, and posted to InVision
- [ ]  Designs shared with UXD team members throughout design process for collaboration and discussion
- [ ] Designs shared with Auth, Platform team in meetings where possible, and with devtools-saas at appropriate times
- [ ] Once designs are finalized, determine how to provide in InVision along with #3653 and #3652 in a way that will be implementable by development. Create final specs for development that can be implemented by experience/feature.

**Comment by lwrigh** [comment]
Link to the space permissions for reference: #2910

**Comment by lwrigh** [comment]
Here is a link to the in progress wireframes: https://redhat.invisionapp.com/share/GUJTFTJE3RY

**Comment by lwrigh** [comment]
Here's an updated link with the latest updates: https://redhat.invisionapp.com/share/KQKK0IADV2F

**Comment by lwrigh** [comment]
Here's the latest updates to the wireframes: https://redhat.invisionapp.com/share/9UKW89QM3ZH

**Comment by lwrigh** [comment]
Security groups has been added to the wireframes.

**Comment by lwrigh** [comment]
Interaction notes have been added to the wireframes.
