### ISSUE TITLE
[3] Move away from having Github repository name and Application name the same.

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#3662]
### Description

Currently, the getting started flow supports the manual entering of Github repository name (in case of quick start flow) and application name. Due to some technical challenges in the background, both github repo name and application name is made to be same.
This user story tracks the removal dependency in name between these once the technical challenges are resolved.

### Acceptance Criteria

User should be able to input different names for Github repo as well as application. All the setup process has to run without problems.

### Tasks

- [x] Testing of build system for the support of different names.
- [x] Handling the logic in the ui to make sure there is no coupling or dependency between the names of Github repo and application name.
- [ ] Tests to validate the same.
- [ ] Manual testing to ensure the flow works fine without any regressions.

**Comment by piyush1594** [comment]
@arunkumars08 JFYI, changes on pipeline side are done if you see https://github.com/openshiftio/openshift.io/issues/3095#issuecomment-391841163 This has been fixed in Jenkins sync plugin and the fix is available in Jenkins version 4.0.80 in OSIO. Let me know if you find something else.

**Comment by arunkumars08** [comment]
Sure @piyush1594 will connect with you when testing the feature in case of any problems. Thanks!

**Comment by piyush1594** [comment]
And please make sure of the third task. I really liked it a lot :wink: as it was not there previously.

**Comment by GeorgeActon** [comment]
@jyasveer This needs link to feature in planner

**Comment by piyush1594** [comment]
@jyasveer is this in prod now?

**Comment by jyasveer** [comment]
@GeorgeActon this is yet to be moved to prod. once we test in prod we can close this.

**Comment by jyasveer** [comment]
@piyush1594 no it is not yet in prod

**Comment by animuk** [comment]
@GeorgeActon This feature is alredy in the planner: https://openshift.io/openshiftio/openshiftio/plan/detail/2454

**Comment by jyasveer** [comment]
@piyush1594 @GeorgeActon This is available in prod. So I am closing it.

**Comment by bmicklea** [comment]
There are two checkboxes in the description for testing - were those completed?

**Comment by jyasveer** [comment]
I had missed those ;-)
