### ISSUE TITLE
[3]  Setup Jenkins locally to test Booster environment.

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#3663]
**UserStory**: https://openshift.io/openshiftio/openshiftio/plan/detail/2459
    As an OSIO Developer, I will be able to run boosters locally on Jenkins.

As we are adding new boosters in OSIO and planning to improve/troubleshoot issues in the existing booster. we want to run and test new boosters locally to know how it will behave on Jenkins pipelines.

**Acceptance:**
- A booster should able to build successfully on Jenkins.
- A booster should able to run successfully on Jenkins.

#### Tasks:
- [x] Setup Jenkins environment and successfully run it on a local system.
- [x] Create JenkinsFile with essential steps to run booster on Jenkins.
- [x] Install right plugins in Jenkins to mock the similar environment.
- [x] Build and Run Booster on Jenkins.

**Comment by GeorgeActon** [comment]
@ravsa is this closed?

**Comment by GeorgeActon** [comment]
@ravsa Is this closed
