### ISSUE TITLE
[13] Technical feasibility research - Suggest alternatives to API breaking changes

### ISSUE THREAD

**Issue by abs51295** [openshiftio/openshift.io#3678]
### Planner Item

https://openshift.io/openshiftio/openshiftio/plan/detail/2415

### User Story

As an OSIO user, I should be able to get suggestions when there are breaking changes to APIs that I used in my code, so that my code doesn't break.

### Description

The idea with this use case is for analytics to better help developers to work with API breaking changes so they can stay up-to-date with the latest versions of their dependencies.

This involves predicting the fix for an API breaking change by using doc strings and code understanding to match the "intent" of functions and assign them a similarity score to figure out which new function 'b' works the same as function 'a', and printing migration path information. 

### Acceptance Criteria

Definite answer to the technical feasibility of the approach. 

### Task List

- [ ] Decide the scope of API(s) we are going to target (For example: Web based APIs or language APIs).
- [ ] Estimate the data required to be collected. 
- [ ] Evaluate various machine learning models and decide which model looks best for the use case.
- [ ] Document the findings.
