### ISSUE TITLE
[8] UX support to provide security notifications to Openshift.io users

### ISSUE THREAD

**Issue by parvathyvr** [openshiftio/openshift.io#3679]
**Details:**
As an openshift.io engineer design UX for the notification service so that
 Openshift.io users are able to opt-in for such a service and get notifications via email

link to feature in planner:https://openshift.io/openshiftio/openshiftio/plan/detail/2389

Acceptance:
- [x] UX screens are designed and approved by the PM

Assumption: None

**Tasks List**
- [x] UX-opt-in setting to receive notifications for user 
       link to task in planner:https://openshift.io/openshiftio/openshiftio/plan/detail/2455
- [x] UX-format of email that user gets
        link to task in planner:https://openshift.io/openshiftio/openshiftio/plan/detail/2456

**Comment by parvathyvr** [comment]
**Invision mockups to the earlier explorations**
1) opt-in settings in OSIO to receive notifications:
https://redhat.invisionapp.com/share/CZKEK78TF4G#/screens/301742862_Table_Of_Contents
2)for the email notification:
https://redhat.invisionapp.com/share/65GBNCQ32ER#/285431424_email_Notification_V2

**Comment by parvathyvr** [comment]
Invision Mockup with the latest updates:https://redhat.invisionapp.com/share/VPKMQPFMF8U#/screens/302332659

**Comment by parvathyvr** [comment]
UX mockup screens are completed and reviewed.Hence closing this.
