### ISSUE TITLE
[3] Create the training pipeline for the new model

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#3680]
**Planner** [2151](https://openshift.io/openshiftio/openshiftio/plan/detail/2151)

## Description
As an Openshift.io Engineer, I need to create a necessary training pipeline so that the new model can be trained and retrained on AWS EMR.

## Tasks:

- [ ]  Add code for EMR training
- [ ]  Perform training on EMR
- [ ] Update the S3 bucket with the EMR trained model.

## Acceptance
*  EMR jobs pipeline implemented.

**Comment by sara-02** [comment]
Covered here: https://github.com/fabric8-analytics/f8a-hpf-insights/pull/30 and https://github.com/fabric8-analytics/f8a-hpf-insights/pull/45
