### ISSUE TITLE
[5] New maven scoring model to be available on Production

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#3681]
**Planner** [2152](https://openshift.io/openshiftio/openshiftio/plan/detail/2152)

##  Description:
As an Openshift.io Engineer, I need to productionise the scoring service so that it can be consumed via API services.

## Tasks:

- [x] Integrate the model E2E
- [x] Test the model on staging
- [x] Test the model on the production
- [x] Load test the standalone model on Dev-cluster
- [x] Request for resources for this model on staging and prod(@miteshvp @sivaavkd )
- [x] Start Maven data collection in the graph. (@msrb )

## Acceptance: 
* The model is integrated E2E.
* Maven stacks recommendations get served from the new model in production.
*  Model is load tested.

**Comment by sara-02** [comment]
Quick Updates:
As per @msrb, during the first batch of data collection, 63%(of 10k) packages were not found in maven central.
And we have placed a resource request for the service here: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2036
The results of load testing can be found here: https://docs.google.com/spreadsheets/d/1YZzEDFFtLsEVksMOnY2Dqe_bsJgnqmci1QVN1VBtDeA/edit?usp=sharing
The load testing was performed against a 900 Mb model(trained with approx 9k manifest and 20k packages), deployed here: http://bayesian-hpf-insights-maven-hpf-insights.dev.rdu2c.fabric8.io
The load testing script can be found here: https://github.com/fabric8-analytics/f8a-hpf-insights/blob/master/perf_tests/locust_tests.py

**Comment by miteshvp** [comment]
@sara-02 - any updates here? Can this be closed or comments edited to point to correct planner items?
