### ISSUE TITLE
[5] [Technical feisability Research] Automatic generation of git commit messages - Part I

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#3682]
#### User story

As a user of Che, or the VSCode IDE extension instead of seeing a standard placeholder I would get a commit message.

#### Description

This issue is the first part of the TFR that will be done to scope the work required and feasibility of the auto generation of git commit messages use-case.

#### Acceptance Criteria

- [ ] The work required for this use case and the underlying technologies that need to be worked on needs to be scoped and documented.

#### Task List

- [ ] Come up with a proposal for the "code understanding framework" that forms the technological base for this and future use cases
- [ ] Scope out the work involved in this particular use case (git commit messages)
- [ ] Figure out the data that needs to be collected to make the use case possible
- [ ] Skim through available literature to form an approach for the key sentence extraction part of this use case
- [ ] Document possible approaches for the use case

**Comment by rootAvish** [comment]
This work was de-prioritized and hence not taken up in the sprint. Moving to backlog.
