### ISSUE TITLE
[8] Incorporate new evaluation metric to accomodate user feedback

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#3700]
**EPIC: 2172 on Planner
Feature: 2151 & 2153 on Planner**

## Description:
As a part of the current testing and evaluation framework, I have added an implementation of Precision, Recall and MAP(mean of average precision) functions. In the next sprint, we will be focusing on accommodating a user feedback matrix as well. One of the ways in which we can do that is to use for the evaluating the model via NDCG(normalised discounted cumulative gain),
The main difference between MAP and NDCG is: 

> While MAP assumes binary relevance(an item in our case package is either of interest or not). NDCG allows relevance scores in form of real numbers. [1]

So using the feedback matrix, we can generate a relevance score(a non-negative number) for each package. To start with, since we will not have any feedback, we can assume the `gain` for the packages to be zero. 

## Tasks:
- [ ] Implement an NDCG function.
- [ ] Explore feedback mechanism
- [ ]  Implement feedback and training.

## Acceptance Criteria:
* A new evaluation function is implemented and added to the evaluation framework.

## Additional Links:
[1]: http://fastml.com/evaluating-recommender-systems/

**Comment by sara-02** [comment]
As the feedback matrix is now a part of scoring, we will not this.
