### ISSUE TITLE
[3] CICD for fabric8-recommender

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#3745]
As a developer, I should be able to seamlessly develop and deploy changes as and when pushed to master in the `fabric8-ui/fabric8-recommender` repository

### Acceptance Criteria

- Stop the GKE way of build and deploy.
- CICD should happen in the CentOS environment. Pushing changes to master branch should release a new NPM version and release it to NPMJS.org

### Tasks

- [x] - Bring in script files to handle the release when the changes are pushed to master.
- [x] - Use Semantic release to control the type of release
- [x] - Add webhooks for the two jobs
- [x] - Add corresponding PRs in almighty-jobs
- [x] - HK issue to add centos-ci as the collaborator
            https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2091

**Comment by invincibleJai** [comment]
update on the above story is, as per my understanding @jyasveer has all needed PRs in place.
Webhooks for the repo has been added by @joshuawilson. Centos-ci as the collaborator has been added based on issue comment. 

Still it needs to validated and tested. @jyasveer can add more.

**Comment by jyasveer** [comment]
Work is done for this task. However i am facing a issue in the npm release process. Looking into the issue to fix it. Here is the jenkins logs for the build error https://ci.centos.org/view/Devtools/job/devtools-fabric8-recommender-npm-publish-build-master/2/console

**Comment by jyasveer** [comment]
To decouple GKE build from this repo :-
1. Need to remove the GKE relate files
    Here is the PR which deletes the files https://github.com/fabric8-ui/fabric8-recommender/pull/460
2. Delete the GKE related webhooks from the github repo. @joshuawilson you can help here with 
    deleting the webhooks

**Comment by invincibleJai** [comment]
@jyasveer can't we get required rights from @joshuawilson , so that we can verify and test it on our own?
