### ISSUE TITLE
[5]Add description for each dependencies shown in dependency editor

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#3777]
### User Story: https://openshift.io/openshiftio/openshiftio/plan/detail/2619
As an OSIO user, I will be able to see the description for each dependencies shown in dependency editor.

## Description:
Currently we don't show any description for dependencies shown in dependency editor screen. As per the UX there should be some short description for each dependencies show in dependency editor. This user story aims to investigate how we can collect some short description for each dependencies ans show it while showing dependencies. 
## Acceptance Criteria
There should be a short description for each dependencies shown in dependency editor.

## Task List:
- [x] Investigate the possibilities of collecting description data for each dependencies.
- [x] Implement crawlers to collect the dependencies description data from identified sources.
- [x] Store the collected description data in graph database.

**Comment by GeorgeActon** [comment]
@sunilk747 @animuk This needs an estimate &a the link to the planner feature

**Comment by animuk** [comment]
@GeorgeActon This user story is in planning stage. candidate for analytics backlog right now.

**Comment by spicemit** [comment]
Description added in graph at Staging and Prod.

**Comment by sunilk747** [comment]
@spicemit I don't see any description in prod as well as staging.

**Comment by sunilk747** [comment]
Descriptions were added for each package in stage as well as prod.
