### ISSUE TITLE
Design Standards Wiki

### ISSUE THREAD

**Issue by sdash-redhat** [openshiftio/openshift.io#3799]
## Description:
Design Standardization Wiki has the two following focus areas:  

- For our team of designers to know what to use when designing screens at a more granular level than PatternFly can achieve as a design system.  Clear guidance on how we do typical screen layouts, CRUD actions, and when to use which patterns.

- For our team to have a discussion with other teams like Tectonic, OpenShift, Middleware teams about the design standards we use above and beyond PatternFly to see if we can standardize across the Red Hat portfolio, and especially those products that it is likely the same user would use.  Serena can help guide these conversations.

## Verification Criteria
  

- [ ] Ensure the Design Standards Wiki (DSW) is setup 
- [ ] Review the different common components used across the different applications. 
- [ ] Compare the commonly used components/patterns with the ones from Patternfly. 
- [ ] Identify and set up a process to update content to the DSW.
- [ ] Draft initial guidelines and engage with the team in the review process. 
- [ ] Update the content and guidelines to the DSW.

## Associated Issues
TBD

**Comment by mindreeper2420** [comment]
Linking this with https://github.com/openshiftio/openshift.io/issues/2871, as they both relate to design standards in OSIO.

**Comment by sdash-redhat** [comment]
Changing the type to epic, to make sure the type is more meaningful

**Comment by sdash-redhat** [comment]
Being an epic, I am unassigning individuals, let's assign the stories that we will be working under this, so that they can be tracked for progress.

**Comment by serenamarie125** [comment]
Closing out all design wiki stories
