### ISSUE TITLE
[5] UI support to enable Openshift.io users to opt-in for monitoring their stacks

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#3823]
### User Story : https://openshift.io/openshiftio/openshiftio/plan/detail/2090

As an openshift.io user it should be possible to get notified of any security issues in their application stack. Also, it should be possible for OSIO users to opt-out of such service for any repositories under their codebases. 

**Acceptance:**

- OSIO users are by default opted-in to monitor their application stacks for any security issue and get notified via email
- OSIO users can opt-out of monitoring their application stacks for any security issues
- OSIO users can see what repositories they have subscribed to for getting security notifications on the codebases page

**Assumption:**

- Users token for a git of their choice is available to analytics via platform

**Task**
- [x] - Showing subscription status for repositories in Codebases view under Create in form for toggle radio as suggested by UXD
   - [x] - Design and integrate switch in codebases list
   - [x] - Integrate with codebases API
- [x] -  User may choose to unsubscribe from a particular repository, using toggle radio
   - [x] - Integrate with API for unsubscribing
- [x] -  Making API call to Platform API for Subscribing and unsubscribing 
- [x] -  Designing the email template as suggested by UXD
- [x] -  Integration of the email template

**Comment by invincibleJai** [comment]
Closing the task as above changes  are in prod CC @miteshvp
