### ISSUE TITLE
[1] `f8a-hpf-insights` processed by all QA-related scripts and displayed on the QA Dashboard

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#3848]
## Planner issue:

https://openshift.io/openshiftio/openshiftio/plan/detail/2676

## Task description

Add `https://github.com/fabric8-analytics/f8a-hpf-insights/` repository to QA Dashboard and setup all QA-related scripts.

## Acceptance criteria

- [x] `f8a-hpf-insights` repository is displayed on QA Dashboard
- [x] all QA-related scripts are prepared in the repository
- [x] all Python code checked by linter
- [x] all Python code checked by PyDocstyle
- [x] unit tests are started for each PR
- [x] code coverage threshold checked in the CI job

**Comment by tisnik** [comment]
1st part: https://fabric8-analytics.github.io/dashboard/dashboard.html
2nd part: https://github.com/fabric8-analytics/f8a-hpf-insights/pull/17
3rd and 4nd part: dtto
5th part: https://github.com/fabric8-analytics/fabric8-analytics-common/pull/566
