### ISSUE TITLE
Design Standardization :  Layout

### ISSUE THREAD

**Issue by sdash-redhat** [openshiftio/openshift.io#3899]
### Description:
This is a parent story to manage the individual standardization stories related to the Layout. 
Each of the stories below would be added to the Design Standard Wiki (DSW)

This focus area will address the following stories:
- [ ] Design Standardization : Layout > List View
- [ ] Design Standardization : Layout > Card View  
- [ ] Design Standardization : Layout > Empty States 
- [ ] Design Standardization : Layout > Overlay
- [ ] Design Standardization : Layout > Dashboard 
- [ ] Design Standardization : Layout > Mastheads
- [ ] Design Standardization : Layout > Header Bar
- [ ] Design Standardization : Layout > Overview Section of Wiki

### Verification Criteria
For each of the stories listed in the description, the following activities need to be performed and completed: 

- Review the usage across the different existing applications.
- Compare ones from Patternfly.
- Provide the proposal 
- Review the Proposal with the team (UX, Engg., PM)
- Draft initial guidelines and engage with the team in the review process.
- Update the content and guidelines to the DSW

### Parent Issue / Reference
Design Standards Wiki #3799

**Comment by serenamarie125** [comment]
Closing out Design Standardization tasks as related to the wiki
