### ISSUE TITLE
Design Standardization : CRUD

### ISSUE THREAD

**Issue by sdash-redhat** [openshiftio/openshift.io#3911]
### Description:
This is a parent story to manage the individual standardization stories related to CRUD interaction aspect across the applications. 

Each of the stories below would be added to the Design Standard Wiki (DSW)

This focus area will address the following stories:
- [ ] Design Standardization : CRUD > Create
- [ ] Design Standardization : CRUD > Rename
- [ ] Design Standardization : CRUD > Update
- [ ] Design Standardization : CRUD > Delete
- [ ] Design Standardization : CRUD > Inline Edit
- [ ] Design Standardization : CRUD > Delete Confirmation

### Verification Criteria
For each of the stories listed in the description, the following activities need to be performed and completed: 
- Review the usage across the different existing applications.
- Compare ones from Patternfly.
- Provide the proposal 
- Review the Proposal with the team (UX, Engg., PM)
- Draft initial guidelines and engage with the team in the review process.
- Update the content and guidelines to the DSW

### Parent Issue / Reference
Design Standards Wiki #3799

**Comment by serenamarie125** [comment]
Closing out Design Standardization tasks as related to the wiki
