### ISSUE TITLE
Design the workflow to check for newer version availability

### ISSUE THREAD

**Issue by yzainee** [openshiftio/openshift.io#3976]
#### **Planner:** [235](https://openshift.io/openshiftio/Openshift_io/plan/detail/235)

**Tasks**:
- [x] Decide on the various trigger points to trigger the flow

- [x] Design the workflow

- [x] Decide on the json structure

- [x] Document the details in a doc/ppt

**Comment by yzainee** [comment]
https://docs.google.com/presentation/d/1QOYGmtw-YsfymjEr902_XQDF-_i-HYSKBzaieX9f1SQ/edit#slide=id.g3cfd439a6e_0_56
