### ISSUE TITLE
[3] Enable Wildfly-Swam redhat runtime version boosters

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#3977]
As an OSIO Developer, I will be able to create a Wildfly-Swam redhat runtime version boosters
#### Description:
As wildfly-swam redhat runtime version boosters(Mission: rest-http, health-check, configmap) are working fine. we want to enable those boosters and disable the community version boosters in openshift launcher flow.
**Acceptance:**
- Boosters should be able to pass these steps in openshift.
    - It should be able to pass CD Build (Jenkins) successfully.
    - It should be able to deploy on __Stage__  and __Run__ successfully.
    - It should be able to generate working links for  __Stage__  and __Run__.
    - A user should be able to open booster in the _Che_ workspace.
    - A user should be building the project using Maven in the _Che_ terminal window.
    - A user should be able to access preview URL
    - A user should be able to run and debug project from the _Che_ menu.
    - A user should be able to modify the project source code in _Che_  and auto-recompile and auto-redeploy. should work properly.
    - A user should be able to see changes in  __Stage__  and __Run__ links.

#### Tasks:
- [ ] Test following boosters and enable it in booster-catalog.
    - [ ] Runtime: `Wildfly-swarm` runtimeVersion: `redhat` Mission: `rest-http` 
    - [ ] Runtime: `Wildfly-swarm` runtimeVersion: `redhat` Mission: `health-check` 
    - [ ] Runtime: `Wildfly-swarm` runtimeVersion: `redhat` Mission: `configmap`

**Comment by bartoszmajsak** [comment]
> It should be able to generate working links for Stage and Run.

@ravsa Could you elaborate which links and where?

@ldimaggi can we use existing Booster e2e tests to cover all the steps from this acceptance criteria?

**Comment by ravsa** [comment]
@bartoszmajsak I'm talking about the deployed application links to stage and run on pipeline screen.

**Comment by bartoszmajsak** [comment]
@ravsa Configmap booster is currently not enabled on prod - do you know what was the reason for that?

**Comment by bartoszmajsak** [comment]
- Before running tests in any IDE (including Che) execute `mvn package fabric8:resource fabric8:build`
- The above command would execute unit tests, in order to run integration tests execute `mvn install -Popenshift-it`
- Verify if pipeline is able to execute builds (both from master and `PR`)

**Comment by bartoszmajsak** [comment]
As per discussion here https://openshift.io/openshiftio/Openshift_io/plan/detail/119 we are closing this and stick with community versions due to multiple issues encountered which are either old product version or our infra related. Latest community version does not suffer from it.
