### ISSUE TITLE
[8] Recommendation support for Golang - Deployment configuration and Load Testing

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#3980]
#### User Story

The analytics platform should be able to run the Golang recommendation service on the internal OSD cluster so that recommendations can be served from a REST endpoint.

#### **Description**

This task involves the tasks required to deploy the model as a standalone service so that it can be tested using a REST client, as well as load testing this service to identify resource needs and scaling challenges.

#### **Acceptance Criteria**

- Load testing results for the standalone service should be available
- There should be a standalone endpoint available for this service that is deployable on dev cluster and in staging.

#### Task List

- [x] Calculate recall@300
- [x] Calculate recall@50
- [x] Evaluate the association rules
- [ ] Perform load testing
- [x] Write the REST API endpoint as service for insights

**Comment by rootAvish** [comment]
This is done, so closing. Load testing numbers shared with SD and service is in staging.
