### ISSUE TITLE
Understanding the architecture and codebase of chat.openshift.io

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#4038]
Planner : https://openshift.io/openshiftio/Openshift_io/plan/detail/242

## Task List:
- [x] Understanding code base and all associated repos/services.
     - [x] Understand the chat.openshift.io deployment process and associated repository.
     - [x] Understand the mattermost-server upstream code repository.
- [x] Come up with HLD document which could help others to understand code flow.
- [x] Should be able to setup / build / run it on dev machine/ dev cluster.
- [x] Have KT with team based on above task

**Comment by sunilk747** [comment]
Here is the HLD for chat.openshift.io :- https://docs.google.com/document/d/1wo0K4VVrIWt5bqtnDubB6NeJ_CBsq6yC37ocVdjVVg4/edit?usp=sharing

**Comment by sunilk747** [comment]
Architecture details and high level view of mattermost-server :-
https://docs.google.com/document/d/131ItiDmOxMRvcll4G6-Tzst3uUYtrYKejo10RQFmq8I/edit?usp=sharing
