### ISSUE TITLE
Analysing reusability of various components/modules in chat.openshift.io

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#4039]
**PLANNER LINK** :- https://openshift.io/openshiftio/Openshift_io/plan/detail/246

#### User Story: 
As an OSIO Developer, I will be able to reuse various components/modules of chat.openshift.io for User-Analytics(ChatBot) use case.

#### Description:
As we are going to integrate the chatbot with chat.openshift.io so we want to analyze all the backend and frontend components that can be reused for the chatbot.

**Acceptance:**
- Identified some UI/Backend components.
- Identification of the integration plug in component which can be resused.

#### Tasks:
- [x] API/Components which can be reused for backend
- [x] Components which can be reused for frontend
- [x] Understanding how to make custom bots/plugin in chat.openshift.io

**Comment by stevengutz** [comment]
One this is captured in Planner this work item and the child work items should be closed.

**Comment by jyasveer** [comment]
UI code of chat.openshift.io is in React. As fabric8-ui is in Angular framework, ui components of chat.openshift.io cannot be reused
