### ISSUE TITLE
Identifying the Data sources which would be useful for User-analytics use cases.

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#4040]
**PLANNER LINK** :- https://openshift.io/openshiftio/Openshift_io/plan/detail/241

#### User Story: 
As an OSIO Developer, I will be identifying the Data sources which would be useful for user-analytics use cases.

#### Description:
As we are going to develop user analytics AI use cases, It will require data for that so the goal is identifying the different Data sources.

**Acceptance:**
- Identify the raw data sources.

#### Tasks:
- [x] Analyzing available data of chat.openshift.io.
- [x] Analyzing other data sources other than chat.openshift.io.
- [x] Analyzing OSIO APIs like Build API, Platform API, Openshift API
