### ISSUE TITLE
 Exploring Tensorflow.js and understand how it works

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4041]
**PLANNER LINK** :- To Be updated

#### User Story: 

As an Analytics Developer, I would like to explore and understand `tensorflow.js`, it's API's and working.

#### Description:
As we are going to have  chatbot powered by analytics so we want to analyze tensorflow.js for same to see if we can leverage some of it's capabilities. an Analytics Developer, I would like to explore and understand `tensorflow.js`, it's API's and working.

**Acceptance Criteria:**
- Understanding of tensorflow and it's API's 
- Have a basic model to demonstrate and understand it's working.

**Tasks:**
- [ ]  Understand fundamentals of ML ( Come up with documentation )
- [ ]  Explore/understand tensorflow.js
- [ ]  Understand Tensorflow APIs
- [ ]  Create a basic model in tensorflow

**Comment by stevengutz** [comment]
Story work should now be in the Planner.  Talk to @GeorgeActon to get help
