### ISSUE TITLE
Design of Chat bot for OSIO

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#4043]
**PLANNER LINK** :- https://openshift.io/openshiftio/Openshift_io/plan/detail/250

#### User Story: 
As an OSIO Developer, I will have proper High-Level Design for the OSIO Chatbot.

#### Description:
As we are going to develop a chatbot for User-Analytics AI use case. That bot will be able to handle basic queries asked by the OSIO user and will provide the solutions for that if available. And this chatbot will be integrated with the chat.openshift.io, so the goal is to come up with the high-level design for the chatbot.

**Acceptance:**
- A High-level design document.

#### Tasks:
- [x] Identifying the various layers and integration points for the chatbot
- [x] Identifying Models and Libraries to be used for this.
- [x] Designing the architecture for UI/Backend.
