### ISSUE TITLE
Implement the draft version of the UI Angular Component for chat bot

### ISSUE THREAD

**Issue by jyasveer** [openshiftio/openshift.io#4044]
### Tasks
- [x] Modify the angular cli way of building the UI Application to the Webpack way of building UI app.
- [x] Show the chatbot on click of a button which should remain fixed on any given page. (like we see the feature button in OSIO)
- [x] Create a npm package and publish it.
- [x] Consume the UI Component from npm and bring up the chatbot. We should see a fixed button when we import the chat component.
- [x] Integrate patternfly-ng library with the UI component to standardise the style

**Comment by stevengutz** [comment]
Why are we still putting story work in GH.  This should be in the Planner.  @GeorgeActon can point you to the right place
