### ISSUE TITLE
Design and feasibility study for the UI Component for chat bot

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4062]
### User Story
As a OSIO developer i need to a feasibility study and come up with the design of UI component for chatbot that would help the user to get analytics insights/suggestions for OSIO

### Acceptance Criteria
1. Document a list of features that have to be present in the chatbot
2. Come up with design/specification approach for it.

### Tasks
- [ ] Document a list of features that have to be present in the chatbot.
- [ ] Explore the available open source chatbot implementations
- [ ] Do a feasibility study and filter out the best three options
- [ ] Prepare demo-able code for all the options
- [ ] Finalise one option.

**Comment by jyasveer** [comment]
I went through various chat bot implementations which is listed below :-

1. https://github.com/llSourcell/tensorflow_chatbot
2. https://github.com/mrfishie/js-chatbot
3. https://github.com/ovh-ux/ovh-angular-chatbot
4. https://github.com/AngularFirebase/angular-chatbot
5. https://github.com/mlabouardy/dialogflow-angular5
6. https://github.com/mariohmol/ng-ai-chatbot
7. https://github.com/PKief/angular-events-chatbot

Out of the above list, I went with **option 5** to start with. Reasons are :-

1. It has a MIT license
2. As fabric8-ui is implemented in Angular, we needed a chatbot that would sit well with Angular framework.
3. All other options were in javascript or jquery or Angular 1 which is not feasible to integrate with fabric8-ui

What did I do :-

1. Did a code cleanup
2. Forked the repo into my user space which is here https://github.com/jyasveer/osio-chatbot
3. Fixed the unit tests as per the code changes.
4. Integrated the UI component with the mock rest service that we have for the chatbot
