### ISSUE TITLE
Exploring integration of chat bot with Fabric8-UI

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4090]
### Tasks

- [x] Understand the areas in OSIO where this chatbot can be integrated
- [x] Integrate the chatbot UI into fabric8-ui (Dev Mode)
- [x] Chatbot ui should popup if the user clicks on "chat with us"
- [x] Chatbot ui should be shown on the bottom right corner of the screen
- [x] Chatbot ui should be closed if user clicks on close icon
- [x] Chatbot ui should be binded with data sources.
