### ISSUE TITLE
Validate the extension for last two releases of VSCode

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4091]
### Tasks : 

- [x] Test Component analysis (LSP)  and stack analysis feature in VSCode 1.25.* 
- [x] Test Component analysis (LSP)  and stack analysis feature in VSCode 1.24.* 
- [x] Test Component analysis (LSP)  and stack analysis feature in VSCode 1.23.*
- [x] Perform above validation for Mac
- [x] Perform above validation for Fedora

**Comment by invincibleJai** [comment]
@samuzzal-choudhury have completed this task as planned, hence closing it. 

CC @miteshvp @sivaavkd
