### ISSUE TITLE
Support analysis of semantically versioned node stacks

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4092]
### Tasks : 
- [x] For node ecosystem in case of stack analysis, identify exact dependencies of packages mentioned in package.json 
- [x] Resolve dependencies in package.json with `npm list`
- [x] Implement the logic to have semantically versioned direct dependencies resolved on VSCode with `npm list/package-lock.json`
- [x] Validate it for single manifest file
- [x] Validate it for workspace level
- [x] Validate Stack-report generated.
