### ISSUE TITLE
Load test the analytics backend services with Maven and Node traffic

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#4097]
### Tasks : 
- [x] Identification mixed traffic sample
- [x] Carry out load testing on stack analysis
- [x] Publish the result 
- [x] Explain the process for
       - Requesting production resources to scale the analytics system.
       - Calculating KPI for concurrent users

**Comment by samuzzal-choudhury** [comment]
Blocked because of Dev Cluster issue https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2201

**Comment by samuzzal-choudhury** [comment]
The dev cluster issue is still open, but I am able to scale the services up to 3 and try out different traffic mix for now. Hence, removed the `status/blocked` atm.

**Comment by samuzzal-choudhury** [comment]
The results for 300 concurrent user requests for both Maven and NPM mixed traffic is available in this spreadsheet - https://docs.google.com/spreadsheets/d/1xfc_gxPdp-sNkw3gNqe4KLC2wN_IQC1B11NFxIiWc2w/edit#gid=6958124

A housekeeping issue https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2203 has been opened to get acknowledgment about the required resources for running 3 npm-insights service replicas on the production cluster. On getting successful acknowledgment from the service delivery team, a Saas-analytics PR will be opened to increase the production replica count for the service `f8a-npm-insights` to 3.

**Comment by miteshvp** [comment]
@samuzzal-choudhury - We can close this issue as you have explained the process in the above comment on how to scale up the resources. Plese re-open if you think otherwise.

**Comment by samuzzal-choudhury** [comment]
Here is a document that describes the overall process of scaling the analytics system resources and setting 3scale rate limits https://docs.google.com/document/d/1mtR9wjUeLgWuOGDo7QWbCW0LG3CeCRh-4vN3SnUYYhc/edit#heading=h.4cvs8jees3ts
