### ISSUE TITLE
Generating the Structured data for the AI model training

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4106]
### Tasks : 

- [x] Generating structured data for getting started story, classify intent, entity and intent type.
- [x] Generating structured data for analytics story, classify intent, entity and intent type.
- [x] Data should be in the proper format that can be consumable by the AI model
