### ISSUE TITLE
Productionize analytics notification service

### ISSUE THREAD

**Issue by abs51295** [openshiftio/openshift.io#4108]
## Planner Issue

https://openshift.io/openshiftio/Openshift_io/plan/detail/354

## Task List

- [x] Productize the CVE ingestion flow to call analytics notification.
- [x] Productize the Build pipeline flow to call analytics notification.
- [x] Complete the development of integration tests for the `/user-repo/*` service workflows.
- [x] Add functionality to `user-repo/drop` endpoint.
- [x] Pass the files from server api to gemini server directly.
- [x] Add ecosystem in response for gemini server.
- [x] Modify `/report` endpoint response in gemini server to notify CCP regarding missing lock files.

**Comment by abs51295** [comment]
@yzainee please update the planner issue number once it's there.

**Comment by abs51295** [comment]
PRs pending merge are: https://github.com/fabric8-analytics/fabric8-gemini-server/pull/84, https://github.com/fabric8-analytics/fabric8-analytics-common/pull/605

**Comment by abs51295** [comment]
Some minor issues were found. PRs have been raised accordingly to fix them: https://github.com/fabric8-analytics/fabric8-gemini-server/pull/95 and https://github.com/fabric8-analytics/fabric8-analytics-server/pull/358. Closing this issue since those issues will be taken care of as a part of productionizing the experimental endpoint in Sprint 154. /cc: @samuzzal-choudhury @miteshvp @sivaavkd
