### ISSUE TITLE
Setup Maven model training on EMR

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#4109]
#### Planner Link

https://openshift.io/openshiftio/Openshift_io/plan/detail/327

#### Task List

- [x] Write the job to zip the code and upload to S3
- [x] Write the EMR cluster configuration
- [x] Write the code for write back to S3 from EMR
- [x] Ensure training happens

**Comment by rootAvish** [comment]
Closing as this is done, as demonstrated during weekly demos.
