### ISSUE TITLE
Retrain Maven model with all the ingested data to increase coverage

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#4111]
#### Planner Link
https://openshift.io/openshiftio/Openshift_io/plan/detail/328

#### Task list

- [x] The maven model should be retrained with all the data available for the ecosystem, to the extent possible
- [x] Need to perform load testing of the model in isolation again
- [x] The new model needs to be available in production

**Comment by rootAvish** [comment]
Resolved with https://github.com/openshiftio/saas-analytics/pull/460
