### ISSUE TITLE
Validate recommendations using real world Maven stacks, automated accuracy evaluation

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#4113]
#### Planner Link

https://openshift.io/openshiftio/Openshift_io/plan/detail/329

#### Task list

- [x] Document results from the automated evaluation of the complete maven model
- [x] Sync the metrics report with that of NPM (calculate recall@300, recall@50)
- [x] Conduct UAT meetings every week where the team tests the quality of the recommendations on real world stacks
