### ISSUE TITLE
Re-implement the fold-in logic for hpf-insights

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#4212]
#### Planner Link

https://openshift.io/openshiftio/Openshift_io/plan/detail/437

#### Task List

- [ ] Implement the fold-in logic
- [ ] Write the unit tests
- [ ] Push to production
