### ISSUE TITLE
Identify and collect the manifests to be used for training of Python recommendation model

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#4213]
#### Planner Link

https://openshift.io/openshiftio/Openshift_io/plan/detail/438

#### Task List

- [ ] Collect all the Github manifests for Python (requirements.txt)
- [ ] Normalize data and load to S3
- [ ] Pass list of EPVs for collection

/cc @msrb

**Comment by miteshvp** [comment]
@abs51295 - any updates in this issue?

**Comment by abs51295** [comment]
@miteshvp All the manifests files have been collected and passed to @msrb for ingestion.
