### ISSUE TITLE
Automatic release process for LSP

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#4223]
### Planner Link:
https://openshift.io/openshiftio/Openshift_io/plan/detail/452

### Tasks:
- [ ]  CI: Unit test creation (Stretch)
- [x]  CI: Run PR build
- [x]  CI: Run PR merge build
- [x]  CI: Release the LSP server on NPM registry
- [x]  CI: Implementing Semantic version release for LSP server
- [x]  CI: The LSP server tar is to be release on Github
- [x]  CD: Automate PR creation for rh-che
- [x]  CD: Automate PR creation for VsCode extension

**Comment by jyasveer** [comment]
Associated PRs:
- https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/51
- https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/53
- https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/55

**Comment by jyasveer** [comment]
This is done.
