### ISSUE TITLE
[5] Implement Database model and API endpoint to access the chat history

### ISSUE THREAD

**Issue by ravsa** [openshiftio/openshift.io#4230]
** Task: **
- [ ] Setup database server
- [ ] Integrate the database server with current http server
- [ ] Create  database schemas
     - [ ] Create a GET API to access the chat history in chunks
     - [ ] Modify the current [POST] `api/v1/query` API to store the data in database asynchronously
