### ISSUE TITLE
WORKSHOP: Java development with Eclipse Che / che.openshift.io on OpenShift

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#4243]
Workshop doc [1] 

- [x] PR flow for che.openshift.io dashboard does not work - https://github.com/redhat-developer/rh-che/issues/727 / https://github.com/redhat-developer/rh-che/pull/810
- [x] The factories workflow after login doesn't work on Firefox (Works fine in Chrome) https://github.com/redhat-developer/rh-che/issues/832
- [x] Frames are not shown, when debugging on rh-che https://github.com/redhat-developer/rh-che/issues/762
- [x] Initial `catalina.sh run` logs for `web-java-spring-petclinic` / `build and run` command are printed in red in the terminal https://github.com/eclipse/che/issues/10973 - workaround is described in https://github.com/openshiftio/openshift.io/issues/4243#issuecomment-417578394 

[1] https://docs.google.com/document/d/1Vsk0A6xjgxQ9_pdpfLgXCZATGvi3Q1yS9DxRVOkKZEY/edit

**Comment by rafabene** [comment]
We need to add or reference the color pattern used in the console. Lines starting with date are presented in red, even when they are not errors.

<img width="508" alt="screenshot 2018-08-27 12 59 59" src="https://user-images.githubusercontent.com/30131/44737404-ead36c80-aabf-11e8-859b-084091518e5c.png">
<img width="507" alt="screenshot 2018-08-27 13 00 09" src="https://user-images.githubusercontent.com/30131/44737417-f161e400-aabf-11e8-847d-91f213aaf17b.png">

**Comment by ibuziuk** [comment]
@rafabene have created an issue upstream and added to the list of sub-tasks

**Comment by ibuziuk** [comment]
most of the issues (debugging frames / PR flow) have been fixed after today's update of rhche on prod. 
red output for `catalina.sh run` seems to be expected behaviour - https://github.com/eclipse/che/issues/10973#issuecomment-416835533

**Comment by ibuziuk** [comment]
@rafabene the easiest way to get rid of the red output would be redirecting  stderr to stdout via  `2>&1` on the command level e.g. 
`mvn -f ${current.project.path} clean install 2>&1 && cp ${current.project.path}/target/*.war $TOMCAT_HOME/webapps/ROOT.war && $TOMCAT_HOME/bin/catalina.sh run 2>&1`
tested on osio and this seem to work just fine:

![image](https://user-images.githubusercontent.com/1461122/44898776-22c8f280-ad00-11e8-8f76-9a1e22a86f18.png)

**Comment by rafabene** [comment]
@slemeur Do you think we should update the factory with the command above?

**Comment by slemeur** [comment]
Factory updated.

**Comment by rafabene** [comment]
Mine, doesn't show. Does it only work if I update the tenant?
<img width="988" alt="screenshot 2018-09-05 11 36 37" src="https://user-images.githubusercontent.com/30131/45104406-0e219b80-b100-11e8-9aea-89f566f6213c.png">

**Comment by ibuziuk** [comment]
Closing since all the issues have been resolved and the fixes are available on prod.
