### ISSUE TITLE
Identification of "Kubernetes ecosystem" projects and collection of manifest files

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#4260]
#### Planner Link

https://openshift.io/openshiftio/Openshift_io/plan/detail/492

#### Task List

- [x] Write the bigquery script to collect manifests from bigquery
- [x] Pass on the manifests to @msrb so that component ingestion can take place
- [x] Document the project names in a Google spreadsheet and share it
