### ISSUE TITLE
OSIO analytics platform integration with RACHEL

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#4311]
## Planner Link
https://openshift.io/openshiftio/Openshift_io/plan/detail/569

### Description
In order to integrate RACHEL with the analytics platform, a new API service has to be developed that will work without OSIO token-based authentication. The new service is going to handle the RACHEL traffic independent of the OSIO traffic and will be then rate limited separately using 3scale gateway using different 3scale accounts.

### Acceptance Criteria
* A new API service that handles stack analysis and component analysis requests from RACHEL without an OSIO user token.
* The new API service honours the 3scale rate limit set for different endpoints.

## Task List
- [x] API: Implement the auth mechanism for the new API.
- [x] Script: develop a script to automate 3scale application creation process.
- [x] SD team: to create a new secret on prod and prod-preview for custom header set on 3scale.
- [x] Implement integration tests for new APIs
- [x] ~~API: develop a new API to process RACHEL requests.~~
- [x] ~~API: Update the Swagger specification.~~
- [x] ~~SD team: create new 3scale accounts for che-server prod and prod-preview~~
- [x] ~~SD team: acknowledgment for resources to host new API server to accept RACHEL requests.~~ 
- [x] ~~Stretch testing: mixed traffic to the new API.~~
