### ISSUE TITLE
Reducing API traffic passing through LSP server

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4312]
### Planner link : 
https://openshift.io/openshiftio/Openshift_io/plan/detail/625

### Task : 

- [x] - For npm ecosystem we make component-analyses call for all dependencies i.e dependencies, dev-dependencies. We can limit it only for Runtime dependencies.
- [x] - For maven ecosystem we make component-analyses call for all dependencies. We can limit it only for runtime and compile dependencies.
- [x] - Currently, component-analyses call is made for all dependencies even if their versions are not resolved or not provided, in such scenarios Component-analyses call should be avoided.

**Comment by invincibleJai** [comment]
closing it as fixed

**Comment by bartoszmajsak** [comment]
Link to PRs would help to understand the changes made.
