### ISSUE TITLE
Document ecosystem commands to differentiate between direct and transitive dependencies

### ISSUE THREAD

**Issue by abs51295** [openshiftio/openshift.io#4315]
### Planner Link

https://openshift.io/openshiftio/Openshift_io/plan/detail/475

### Task List

- [ ] Identify the command(s) required for maven ecosystem.
- [ ] Identify the command(s) required for Node ecosystem.
- [ ] Identify the command(s) required for Go ecosystem.
- [ ] Identify the command(s) required for Python ecosystem.

**Comment by abs51295** [comment]
Please find the findings here: https://docs.google.com/spreadsheets/d/1xDGVbIfWeAqQIqDBzCBY5CXYG7EkkPFNmzMoaIcf4KI/edit#gid=1303215311
