### ISSUE TITLE
Promote experimental user scan endpoint of gemini to production

### ISSUE THREAD

**Issue by abs51295** [openshiftio/openshift.io#4324]
### Planner Link
TBD

### Task List

- [ ] Make the [experimental](https://github.com/fabric8-analytics/fabric8-gemini-server/blob/master/src/rest_api.py#L160) endpoint as a primary endpoint for user scans.
- [ ] Modify unit tests to reflect the new endpoint schema.
- [ ] Modify the integration tests to reflect the new endpoint schema.
- [ ] Implement unit/integration tests for newly introduced code.
- [ ] Test the new workflow on production.
- [ ] Mark the current scan endpoint as experimental endpoint for the time being. Once we test successfully the whole e2e flow on production, remove this endpoint.

**Comment by abs51295** [comment]
Blocked on failing e2e tests for https://github.com/fabric8-analytics/fabric8-analytics-server.

**Comment by abs51295** [comment]
Blocked on: https://github.com/openshiftio/openshift.io/issues/4399

**Comment by miteshvp** [comment]
@abs51295 - changes are in prod-preview - https://github.com/fabric8-analytics/fabric8-analytics-server/commit/67e1fc1cbdf6629a6f5ccb126ee9a2476f8ce9da

**Comment by abs51295** [comment]
Blocked on: https://github.com/openshiftio/openshift.io/issues/4407

**Comment by miteshvp** [comment]
@abs51295 - can you please test this changes now? It seems the core is deployed on prod-preview
