### ISSUE TITLE
Enable VSCode extension to generate direct and transitive dependencies

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4355]
### Task List :

- [x] - Support for direct-dependencies and transitive-dependencies  in `stack-analyses` POST call
- [x] - Impliment changes in VSCode extension to generate direct-dependencies and transitive-dependencies
- [x] - Making stack-analyses call from the extension, post generation of direct/transitive dependencies
- [x] - Implement support at API server
- [x] - Generate stack aggregation for both direct and transitive dependencies
- [x] - Make changes in stack report UI to accommodate transitive deps as a new tab under security card
- [x] - Make changes in stack report UI to accommodate transitive deps as a new tab under analyzed card
- [x] - Change position of companion and usage outliers tab under insights card

**Comment by invincibleJai** [comment]
@abs51295 FYI, pls add if any more tasks are needed.

**Comment by yzainee** [comment]
The API server changes are done and can be found here : https://github.com/fabric8-analytics/fabric8-analytics-server/pull/408
