### ISSUE TITLE
Openshift.io rebranding

### ISSUE THREAD

**Issue by gorkem** [openshiftio/openshift.io#4364]
This is the top level issue to collect and followup different items related to the rebranding of OSIO. 

### Priority One
- [ ] [RH Developer Site](http://developers.redhat.com/) OPENSHIFT.IO - Nav Item 
- [ ] RH Developer Site OPENSHIFT.IO - [Overview](http://developers.redhat.com/products/openshiftio/overview)
- [ ]  Manage.openshift.com - OpenShift.io tile shown as an active subscription
- [ ] OpenShift.io Web properties
    - [ ] OpenShift.io Web properties - Footer 
    - [ ] OpenShift.io Web properties - Features
    - [ ] OpenShift.io Web properties - Get Involved
- [ ] OpenShift.io Web properties - Documentation
- [ ] [Docs.openshift.io](http://docs.openshift.io) 
    - [ ] OpenShift.io User Guide
    - [ ] OpenShift.io Getting Started Guide
- [ ] OSIO : Home
- [ ] OSIO : “About OpenShift.io” item in the Help menu in the OSIO top banner
- [ ] OSIO About screen 
- [ ] [che.openshift.io](che.osio) branding
- [ ] Twitter [account](https://twitter.com/openshiftio)
- [ ] Labels on [Youtube](https://www.youtube.com/watch?v=_N5rr2Qe66w&list=PLf3vm0UK6HKq-ZgG3q-gp-MDLzlaH_tQo) 

### Priority Two 
- [ ] URL Change
- [ ] GitHub organization and repository
- [ ] Launcher and booster changes 
    - [ ] rename .openshiftio folder 
    - [ ] boosters have io.openshift as default package/groupId name for Java-based projects
    - [ ] rename launcher-backend “osio-addon”

**Comment by joshuawilson** [comment]
@gorkem should this be in planner, since we track most work there?

**Comment by gorkem** [comment]
I guess so, I am still confused about what goes where.

**Comment by joshuawilson** [comment]
stuff that we plan to work on
This github thing is used for bug tracking mostly

**Comment by nimishamukherjee** [comment]
@gorkem @serenamarie125 we need to cover the Login and Sign Up screens also
![loginsignup](https://user-images.githubusercontent.com/1892722/49205269-8b456f80-f3d4-11e8-899c-d2451b7cc6c9.png)

**Comment by gorkem** [comment]
Thanks @nimishamukherjee I have added it to the list
