### ISSUE TITLE
Implement necessary DB schema for Clair

### ISSUE THREAD

**Issue by Avni-Sharma** [openshiftio/openshift.io#4392]
#### **Description**

Understanding Clair's Postgres database and generating an ER for the same. Also getting insights about what all tables would be affected in Clair Scanner integration work.

#### **Task list**

- [x]     Get the understanding on current Clair DB schema
- [x]     Identify properties that needs to be persisted in Clair DB for a CVE
- [x]     Document all the gaps for CVE details we have presently
- [x]     Identify new tables or properties created at Clair DB
