### ISSUE TITLE
Extend Clair Wrappers to be integrated with Analytics services

### ISSUE THREAD

**Issue by Avni-Sharma** [openshiftio/openshift.io#4393]
#### **Description**

Understanding Clair's codebase, designing and documenting the approach of wrappers mechanism.

#### **Tasks list**

- [x]     Understand the source code for Clair wrappers
- [x]     Architect and document the workflow
- [x]     Implement the code for adding OSIO as a source of CVE information
