### ISSUE TITLE
[VSCode] Remove user authorization extension as dependency from Service extension (analytics)

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4398]
Currently, the user needs to authorize with OpenShift.io for consuming services from analytics in VSCode extension, With the proposed approach Authorization with OpenShift.io would not be needed instead will be leveraging RACHEL integration work.

**TASKS**

- [x] Remove Auth extension dependency from analytics VSCode extension.
- [x] Refactor/remove auth related code changes.
- [x] Configuring 3scale dashboard to have application/service/rate limits in place 
- [x] Integration of extension with 3scale gateway changes
- [x] Publish a VSIX (internal) for testing

**Comment by invincibleJai** [comment]
closing it as the requested feature is in prod.
