### ISSUE TITLE
Firefox add-On Server compatibility with openshift

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#4428]
## Description
As a part of the pre investigation to be done in order to reuse the mozilla addon-server we need to investigate if the server and the services on which it is dependent can be deployed to openshift. This task aims to verify the compatibility of all the services collectively on openshift. 

## Acceptance Criteria
A running instance of addon server on openshift and a document tracking various shortcomings that need to be  addressed in order to deploy it successfully.

## Task List
- [x] Build and run the addon-server on local machine.
- [ ] Deploy individual service to openshift.
     - [ ] addonsserver_web
     - [ ] addonsserver_worker
     - [x] addonsserver_memcached
     - [x] addonsserver_redis
     - [x] addonsserver_mysqld
     - [x] addonsserver_autograph
     - [x] addonsserver_elasticsearch
     - [x] addonsserver_nginx
     - [x] addons_frontend
     - [x] addonsservers_selenium_firefox
     - [x] addonsserver_rabbitmq
- [ ] Deploy the whole application with each service interacting to each other.

**Comment by sunilk747** [comment]
Refer this link for more information :- https://docs.google.com/document/d/1hZFo1aZp1DG2zgpztejuUmj8OeVGGUNjgzPO8-FF0Ac/edit?usp=sharing
