### ISSUE TITLE
EPIC: Build Service: Documentation

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#4447]
Add build service documentation : 

https://github.com/fabric8-services/fabric8-auth/tree/master/docs

- [x] Readme #4562 and fabric8-services/fabric8-build#89
- [x] swagger API openshiftio/openshift.io#4584 and closes fabric8-services/fabric8-build#113
- [ ] Add comprehensive guidebook like f8-auth is doing https://fabric8-services.github.io/fabric8-auth/

**Comment by chmouel** [comment]
README => openshiftio/openshift.io#4562 and fabric8-services/fabric8-build#89
