### ISSUE TITLE
Show proper status messages for progress for stack report generation

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4487]
- Show proper status messages for progress for stack report generation, currently it just shows "Generate Application Stack Report". 
- There is no indication when LSP gets initialized.
- Some indication would be good for the user when LSP is consumed.
- Change the diagnostic messages shown from LSP in problems "Component Analysis" to "Dependency Analytics" and word "Package"  to "Application dependency".

### Task list : 
- [x] Show proper status messages for progress for stack report generation i.e in two stages
- [x] Updating language server and client to 4.0
- [x] Ability for LS to send the custom notification to the client.
- [x] Send progress in VSCode as when LSP calls gets triggered
- [x] Change the diagnostic messages shown from LSP in problems "Component Analysis" to "Dependency Analytics" and word "Package"  to "Application dependency".
- [x] Add "changelog.md" for VScode extension to track changes going in with each release.
- [x] Test in stage all above changes in Fedora/mac/ubuntu/windows
- [x] Release VSCode extension to marketplace

**Comment by invincibleJai** [comment]
closing as changes are in Marketplace
