### ISSUE TITLE
Platform support for users to opt-in for Analytics PR collaboration

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#4496]
**Planner Link :** https://openshift.io/openshiftio/Openshift_io/plan/detail/286
**Tasks**

- [x] Learn type script

- [ ] Understand Multiple Workspace API

- [ ] Implement the functionality
