### ISSUE TITLE
Test coverage for VSCode Extension

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4502]
### Tasks : 

- [x] Configuration needed to show coverage report
- [x] Adds unit tests for all files
- [x] Refacor code wherever needed
- [x] Updates e2e tests
- [x]  test should run as part of CI on each PR and on release

**Comment by invincibleJai** [comment]
Associated PRs : 
- https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/206
- https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/208
- https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/211
- https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/212
