### ISSUE TITLE
Support Quick fixes with codeAction in case of CVEs flagged from LSP

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4516]
### Planner Link : https://openshift.io/openshiftio/Openshift_io/plan/detail/948

Currently in VSCode Extension, we flag CVEs for any core dependencies, proposed would be to enable quick fixes to those with enabling codeAction from Language Server.

### Tasks:
- [x]  Update language server and client version
- [x] Bind codeAction supportin Language Server
- [x] Register command in client to listen and apply edits

**Comment by invincibleJai** [comment]
changes are in prod, closing it.
