### ISSUE TITLE
Single command to generate stack analyses in VSCode Extension

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4518]
### Planner Link : https://openshift.io/openshiftio/Openshift_io/plan/detail/950

Currently, there two separate commands to trigger stack analyses
- Generate Stack Analyses on Manifest
- Generate Stack Analyses on Workspace

With this change, user will have just one command
- View Dependency Analytics Report ... 
It'll handle both workspace and manifest flow depending on the context from it's being triggered.

### Tasks:
- [x] Update multiple commands shown in explorer/commands/contexts as single command
- [x] If IDEs active editor has `package.json/pom.xml` trigger stack analyses at manifest level internally
- [x] If IDEs doesn't have active editor has `package.json/pom.xml` trigger stack analyses at workspace level internally
- [x] If IDEs  have active editor has `pom.xml` and if it's a root pom, trigger stack analyses at workspace level internally
- [x] Introduce keybindings for the command `ctrl+d` to trigger Dependency Analytics Report.

**Comment by invincibleJai** [comment]
Changes are in prod, closing it.
