### ISSUE TITLE
Integrate the Backend with Frontend model to make this design work end to end

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#4548]
### Description
This task aims to integrate the available APIs with frontend component and make the whole application work end to end.

Backend Component - https://github.com/msehnout/che-marketplace-backend

Frontned Component - https://github.com/jeff-phillips-18/catalog-test-app

### Acceptance criteria
A running instance of che marketplace on openshift.

### Task List

- [ ] Understand the UI component code base.
- [ ] Integrate the available APIs with the frontend.
- [ ] Test the end to end workflow.
- [ ] Deploy the whole application with each service interacting to each other.
- [ ] Add CI/CD
