### ISSUE TITLE
Investigation on the Frontend Architecture for Openshift Marketplace

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#4549]
**Planner Link: https://openshift.io/openshiftio/Openshift_io/plan/detail/971**

### **Description**
Our Main Aim is to analyse, understand the Underlying frontend architecture of the Openshift Marketplace so that we can re-use its code base as initial design of Che Marketplace.

### **Acceptance Criteria**
A clear understanding of the openshift marketplace frontend codebase.

### **Task List**
- [ ] Investigate and record the frontend architecture and design including technical stack.
- [ ] Detail Code Walkthrough to be executed for the frontend model.
- [ ] Check the integration points and extensibility so that the base code could be customised according to the requirement.
- [ ] Publish the result in a document.
