### ISSUE TITLE
Gemini changes to support the new json format

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#4623]
**Planner Link :** https://openshift.io/openshiftio/Openshift_io/plan/detail/1215
**Tasks**

- [x] Setup Gemini

- [x] Understand Code base

- [x] Remove parser code

- [x] Add functionality to change json formats

- [x] Update tests

**Comment by GeetikaBatra** [comment]
Closing this one as done
