### ISSUE TITLE
API Server support for maven for vscode and build

### ISSUE THREAD

**Issue by GeetikaBatra** [openshiftio/openshift.io#4624]
**Planner Link :** https://openshift.io/openshiftio/Openshift_io/plan/detail/1213
**Tasks**

- [ ] Setup API Server

- [ ] Understand Code Integration point for Vscode

- [ ] Remove dependency from parser code

- [ ] Point to the Utils parser

- [ ] Update tests
