### ISSUE TITLE
Space - management

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#478]
# Description
As a user, I want to be able to manage the spaces that I own.

# Acceptance Criteria
- [ ] When deleting a space, care needs to be taken as to what is deleted along with it. The user should be presented with child artifacts and asked it they want them deleted too. (delete my pipelines but not my repos)  #915 #920 #925 
- [ ] Gather requirements, agree on delete workflow fabric8-ui/fabric8-ux#573
- [ ] The user should be able to clean up their space. As a user makes use of OSIO over time, his/her PVs can become full - once this happens manual steps must be performed to "clean up" space and enable the user to create new projects. #389

## Parent Scenario
 #2026 Finding meaningful and actionable information within a large development project

**Comment by catrobson** [comment]
Designs can be found here:  https://redhat.invisionapp.com/share/2BD1C1GQY

**Comment by joshuawilson** [comment]
@dgutride is this something you are working on?

**Comment by qodfathr** [comment]
Awaiting a determination on #915, but I think this is implemented to the extent needed for now. If we need additional capabilities, we'll add the separately to the backlog.

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/1995
