### ISSUE TITLE
Improve and Validate recommendations for Python ecosystem

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#611]
### Description
End-user should be able to see improved recommendations for the **Python** ecosystem for identified Supported Github Stacks

#### Acceptance Criteria
- Automated Tagging is implemented for Springboot ecosystem
- Target Recommendations of **70% accuracy**
- Recommendations will fit into the [definition](https://docs.google.com/document/d/1VM5JLrM1DCd-hKdB2RAXrarT4sZhtliXV1wRgYLi7Tg/edit) of Companion, Alternative, Usage based outliers and License based outliers
- All these improved recommendations would need to be served through all the integration points
  - OSIO dashboard
  - Devstudio/Eclipse plugin
  - VSCode Extension

##### Tasks
- [ ] Ingest all Manifest files for Python ecosystem
- [ ] Develop tagger for Python manifest files
- [ ] Run the tagger against Python manifests and collect the tags
- [ ] Determine the **% of manual tagging required** for Python components
          to determine the resource requirements for future sprints
- [ ] Determine the **support %** based on automated tagging for Python manifests
- [ ] Train the PGM Model based on identified support manifests
- [ ] Generate Alternate Component recommendations 
- [ ] Generate Companion Component recommendations 
- [ ] Generate License Outlier recommendations
- [ ] Apply version filters and usage based filters
- [ ] Prepare baseline test data set for Python ecosystem based on GitHub repositories
- [ ] Measure Accuracy of the model against the baseline test data set
- [ ] Display reasoning for Alternate/Companion components recommendations
- [ ] Push to Production

**Comment by krishnapaparaju** [comment]
Changed the label for the milestone

**Comment by miteshvp** [comment]
Closing this as this is not relevant any longer
