### ISSUE TITLE
[8]Enable External  users to consume a specific OSIO service

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#614]
Currently users get registered at openshift.io and get approved to start using OSIO services.
This approval would let these users consume any of the OSIO services (Planner, Che, Analytics).

To enable more users to start consuming analytics API / validate the recommendations being generated by OSIO Analytics,  the ask is to expose Analytics API (only) for external users (IDE Marketplace users: VSCode, DevStudio).  This would enable quick Onboarding of these external users to start consuming Analytics API 

#### Subtasks
1. Log in a redhat developer by means of OSIO login page and redirect the user to the fabric8-analytics UI portal to view a stack report.
2. Improve the above spike to use 3scale URL instead of recommender.api.openshift.io. Also, the logged in user token management is in place.

#### Related Tasks
https://github.com/openshiftio/openshift.io/issues/701

#### Acceptance Criteria
* A redhat developer can access the stack reports from the independent fabric8-analytics UI portal by logging in.

#### Sub task VSCode : 
- [x] Conclude on design discussion for dedicated OSIO login for IDEs  
- [x] Conclude on design discussion for landing view for IDEs which will have token
- [x] Get information from auth team on parameters needs to be passed while login/register is triggered.
- [x] Get information from Platform team where this code will reside and as it has to be in OSIO namespace , so what will be the routes
- [x] Capture redirections happening if opening OSIO from IDEs
- [x] Develop dedicated OSIO login screen ( will be using design of existing OSIO login )
- [x] Integrate and test the complete flow with RHD login/registration

 
#### Sub task VSCode Auth client (Based on discussion post int Cabal): 
- [x] Spin a webserver from extension  
- [x] Develop basic html view to handle redirect uri for login
- [x] Develop a basic rest api [GET]- to get token
- [x] Handle redirect and token access login in above HTML and host in webserver
- [x] Store token in VSCode extnsion with context scope, so it can be accessed by f8-analytics/Other OSIO services through VSCode

**Comment by GeorgeActon** [comment]
@krishnapaparaju do not assing theese to me. If you want to bring them to my attention just put a comment in it.

**Comment by invincibleJai** [comment]
Documentation for workflow : https://docs.google.com/a/redhat.com/presentation/d/1MUEh9cOiDpMdQoiJW_ptbwjhF1SRmWm1y66MCAC4o8Q/edit?usp=sharing

**Comment by samuzzal-choudhury** [comment]
[This is the related issue](https://github.com/openshiftio/openshift.io/issues/466) which the DevStudio team is working on.

**Comment by krishnapaparaju** [comment]
@invincibleJai @samuzzal-choudhury this issue needs to cover the availability of 3Scale gateway and end to end workflow with all the IDE traffic to OSIO Analytics platform go thru 3Scale gateway..
