### ISSUE TITLE
[User Story] Improve and Validate recommendations for SpringBoot ecosystem

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#622]
### Description
End-user should be able to see improved recommendations for the **SpringBoot** ecosystem for identified Supported Github Stacks

#### Acceptance Criteria
- Automated Tagging is implemented for Springboot ecosystem
- Target Recommendations of **70% accuracy**
- Recommendations will fit into the [definition](https://docs.google.com/document/d/1VM5JLrM1DCd-hKdB2RAXrarT4sZhtliXV1wRgYLi7Tg/edit) of Companion, Alternative, Usage based outliers and License based outliers
- All these improved recommendations would need to be served through all the integration points
  - OSIO dashboard
  - Devstudio/Eclipse plugin
  - VSCode Extension

##### Tasks
- [x] Ingest all Manifest files for SpringBoot ecosystem
- [x] Develop tagger for SpringBoot manifest files
- [x] Run the tagger against SpringBoot manifests and collect the tags
- [x] Determine the **% of manual tagging required** for SpringBoot components
          to determine the resource requirements for future sprints (@SaketJNU) (https://github.com/openshiftio/openshift.io/issues/780)
- [x] Determine the **support %** based on automated tagging for SpringBoot manifests
- [x] Determine the **accuracy** of automated tags with manual tags collected earlier(@rootAvish)
- [x] Train the PGM Model based on identified support manifests(@sara-02)
- [x] Generate Alternate Component recommendations(@sara-02) 
- [x] Generate Companion Component recommendations(@sara-02) 
- [x] Generate License Outlier recommendations( @harjinder-hari #640 )
- [x] Apply version filters (@miteshvp)
- [x] Apply license based filters( @harjinder-hari #640 )
- [x] License analysis for recommended packages ( @harjinder-hari #640 )
- [x] Measure Accuracy of the model against the known manifets files Github(@sara-02 #807 #806 )
- [x] Display reasoning for Alternate/Companion components recommendations ( stretch-goal for @harjinder-hari #771 )
- [x] Push to Production

**Comment by krishnapaparaju** [comment]
@GeorgeActon please take a look, will be adding more details to firm up this Epic
