### ISSUE TITLE
[User Story] Improve and Validate recommendations for VertX ecosystem

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#623]
### Description
End-user should be able to see improved recommendations for the **Vertx** ecosystem for identified Supported Github Stacks

#### Acceptance Criteria
- Automated Tagging is implemented for Springboot ecosystem
- Target Recommendations of **70% accuracy**
- Recommendations will fit into the [definition](https://docs.google.com/document/d/1VM5JLrM1DCd-hKdB2RAXrarT4sZhtliXV1wRgYLi7Tg/edit) of Companion, Alternative, Usage based outliers and License based outliers
- All these improved recommendations would need to be served through all the integration points
  - OSIO dashboard
  - Devstudio/Eclipse plugin
  - VSCode Extension

##### Tasks
- [x] Ingest all Manifest files for Vertx ecosystem
- [x] Develop tagger for Vertx manifest files (@fridex)
- [x] Run the tagger against Vertx manifests and collect the tags (@fridex)
- [x] Determine the **% of manual tagging required** for Vertx components
          to determine the resource requirements for future sprints @SaketJNU  (https://github.com/openshiftio/openshift.io/issues/781)
- [x] Determine the **support %** based on automated tagging for Vertx manifests
- [x] Determine the **accuracy** of automated tags with manual tags collected earlier
- [x] Train the PGM Model based on identified support manifests (@sara-02)
- [x] Generate Alternate Component recommendations (@sara-02)
- [x] Generate Companion Component recommendations (@sara-02)
- [x] Generate License Outlier recommendations(@harjinder-hari)
- [x] Apply version filters (@miteshvp)
- [x] Apply license based filters(@harjinder-hari)
- [x] License analysis for recommended packages (@harjinder-hari)
- [x] Measure Accuracy of the model against the known manifets files Github(@sara-02 #807 #806)
- [x] Display reasoning for Alternate/Companion components recommendations (stretch-goal for @harjinder-hari)
- [x] Push to Production

**Comment by krishnapaparaju** [comment]
@GeorgeActon  please take a look at this Epic. Will add more details to add more details for this Epic
