### ISSUE TITLE
[EPIC] Improve and Validate recommendations for Node ecosystem

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#683]
### Description
End-user should be able to see improved recommendations for the **Node** ecosystem for identified Supported Github Stacks

#### Acceptance Criteria
- Automated Tagging is implemented for Springboot ecosystem
- Target Recommendations of **70% accuracy**
- Recommendations will fit into the [definition](https://docs.google.com/document/d/1VM5JLrM1DCd-hKdB2RAXrarT4sZhtliXV1wRgYLi7Tg/edit) of Companion, Alternative, Usage based outliers and License based outliers
- All these improved recommendations would need to be served through all the integration points
  - OSIO dashboard
  - Devstudio/Eclipse plugin
  - VSCode Extension

##### Tasks
- [ ] Ingest all Manifest files for Node ecosystem
- [ ] Develop tagger for Node manifest files
- [ ] Run the tagger against Node manifests and collect the tags
- [ ] Determine the **% of manual tagging required** for Node components
          to determine the resource requirements for future sprints
- [ ] Determine the **support %** based on automated tagging for Node manifests
- [ ] Train the PGM Model based on identified support manifests
- [ ] Generate Alternate Component recommendations 
- [ ] Generate Companion Component recommendations 
- [ ] Generate License Outlier recommendations
- [ ] Apply version filters and usage based filters
- [ ] Prepare baseline test data set for Node ecosystem based on GitHub repositories
- [ ] Measure Accuracy of the model against the baseline test data set
- [ ] CI/CD of PGM scoring for Node ecosystem
- [ ] Display reasoning for Alternate/Companion components recommendations
- [ ] Push to Production

**Comment by miteshvp** [comment]
Closing this for https://github.com/openshiftio/openshift.io/issues/1248
