### ISSUE TITLE
[13](8) Develop and deploy VSCode fabric8-analytics plugin

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#698]
###### Acceptance Criteria:

* A VSCode plugin with the support for both fabric8-analytics LSP and stack analysis is available in a public marketplace.
* User authentication and token management is in place for the plugin.
* All required integration tests for the plugin are functional.
* CI/CD for the plugin repository is in place with the integration tests.
* Plugin supports stack analysis of multiple manifest files present in the project.

###### Related Tasks:
https://github.com/openshiftio/openshift.io/issues/702
https://github.com/openshiftio/openshift.io/issues/704
https://github.com/openshiftio/openshift.io/issues/614

##### Sub Tasks
- [x] Add integration test 
- [x] Changes in order to enable SSO from OSIO ( https://github.com/openshiftio/openshift.io/issues/614 )
- [x] Handle workflow for new user with SSO
- [x] Handle workflow for existing user with SSO

##### Sub Tasks - Authorise OSIO
- [x] Enable commands from VSCode to authorize user at any point in time for f8-analytics
- [x] Enable commands from VSCode to unauthorize user at any point in time for f8-analytics
- [x] Bring in the mechanism in place which would check for validity of refresh token provided
- [x] Bring in the mechanism in place which would fetch access token  with refresh token provided
- [x] Bring in the mechanism in place to update refresh token every 24 hours

##### Sub Tasks - Centos-CI
- [x] Bring CI/CD in place with Centos CI
- [x] Add relevant cici-* files for build, setup and tests 
- [x] Register VScode repo to almighty-jobs
- [x] Trigger test from CI/CD on each PR
- [x] Trigger CI/CD on merge
- [x] Notify about Centos CI status on github interface

##### Sub Tasks - 3Scale
- [ ] Finalise on workflow for 3scale api's consumption from IDE ( https://github.com/openshiftio/openshift.io/issues/701 )
- [ ] handle workflow for 3scale api's consumption from IDE ( https://github.com/openshiftio/openshift.io/issues/701 )
- [ ] Consume 3Scale service by passing access token and retrieving app related key's and url, needed for subsequent calls
- [ ] Consume 3scale stack-analysis services 
- [ ] Consume 3scale component-analysis services , figuring out a way to pass it to server code (LSP) as it's different code base altogether  

##### Sub Tasks - Publish Extension to marketplace
- [x] Publishing in VSC Marketplace
- [ ] Publishing in VSC Marketplace via CI/CD

#### Sub task VSCode Auth client (Based on discussion post int Cabal): 
- [x] Create a repo in f8-analytics
- [x] Implements CI with centos-CI 
- [x] Setup test environment Adds test
- [x] Adds test cases

#### Related bugs
- [x] https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/21
- [x] https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/20
- [ ] https://github.com/fabric8-analytics/vscode-osio-auth/issues?utf8=%E2%9C%93&q=is%3Aissue
- [ ] fabric8-analytics issue list https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues
- [x] Handle auth wrt osio-auth extension for all scenarios https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/24
- [x] Refactor and remove language server code from this extension, should handle LSP from it's own repo https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/25
- [x] Update refresh token at interval of 24 hours https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/26

**Comment by miteshvp** [comment]
Closing this as all the necessary things are covered. Waiting for publishing to VsCode marketplace.
