### ISSUE TITLE
[13](13) Integration: OSIO Analytics platform, 3Scale API Gateway

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#701]
In the context of integrating OSIO analytics platform with IDE extensions, DDoS protection from API gateway and API  life cycle management features would become key enablers for scaling the OSIO analytics platform to broader group of users.

To achieve this target, OSIO analytics platform would need to be integrated with 3Scale API Gateway . This is a mandatory requirement for exposing OSIO analytics platform to external users.

##### Subtasks:
1. New IDE users would need to registered with OSIO platform (with in IDE view)
2. Already registered IDE users would need to authenticated with OSIO platform (with in IDE view)
3. IDE users would need to be redirected to OSIO analytics API after authentication
4. OSIO token would need to be propagated to 3Scale Gateway which is setup at OSIO 

##### Acceptance criteria:

* All the IDE user related traffic would need to be reaching OSIO analytics platform thru 3Scale Gateway

Subtasks:

https://github.com/openshiftio/openshift.io/issues/959

#### Tasks for Sprint 139
- [x] Setting up of a separate 3 scale app, service, limits and route for 3 scale container API
- [ ] CICD for 3 scale container API repository
- [ ] Map production routes
- [ ] Make sure to have a rollback mechanism in the API layer itself. (The reason being, we hit multiple 3 Scale APIs and we have no idea when one can fail, so basically if one service fails, we might have to rollback the created one's or find another efficient way.

##### Testing
- [ ] Test the whole flow integrating with Visual Studio Code IDE
- [ ] Test the whole flow integrating with Dev Studio IDE

**Comment by arunkumars08** [comment]
@krishnapaparaju As per my understanding, we need to have an authentication mechanism (say Registration and Login) right inside IDEs just like we have an ability to receive tokens from the users. Since it can be cached, we don't expect the user to login every time.

If that can be achieved, we can authenticate users right at the root and that still leaves me thinking how portal's hit will be authenticated? 

Please help me understand!

**Comment by krishnapaparaju** [comment]
Yes,  these IDE extensions would have API token once IDE users get registered at OSIO

**Comment by invincibleJai** [comment]
Documentation for workflow : https://docs.google.com/a/redhat.com/presentation/d/1MUEh9cOiDpMdQoiJW_ptbwjhF1SRmWm1y66MCAC4o8Q/edit?usp=sharing

**Comment by miteshvp** [comment]
The workflow is already developed. Some of the items may not be relevant any longer. Hence closing
