### ISSUE TITLE
[13](5) User Story: Improve the Independent UI portal

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#702]
##### Acceptance Criteria:
Improve the following in the independent UI portal for fabric8-analytics:
1. UX as per the latest OSIO benchmark.
2. Deployment scripts are developed to deploy the portal on Bayesian project on prod.
3. CI/CD is in place with the required integration tests.
4. Update the UI to incorporate the new license data

Tasks:

- [x] https://github.com/openshiftio/openshift.io/issues/743 - Revamping the UI design in the portal to the latest UX.
- [x] https://github.com/openshiftio/openshift.io/issues/796 Introduce CI/CD
- [x] https://github.com/openshiftio/openshift.io/issues/958 - Incorporate Feedback Comments in UI for both Independent Portal and OSIO Stack report
- [x] Accommodate justification for analytics recommendations
- [x] https://github.com/openshiftio/openshift.io/issues/1008 - Update the UI in the recommender modal to accommodate the new license data
- [x] https://github.com/openshiftio/openshift.io/issues/1078 - Update the UI in the ops portal to accommodate the new license data
- [x] UI fixes in license changes and improve the representation of unknown and component conflict licenses

- [x] Things needed to make it production ready
    - [x] Authenticating Portal from IDE
        - [x] Receive the access_token via url as a JSON
        - [x] Handle the logic changes to pick the token from the url.
        - [x] Test the changes from IDE
    - [x] Bring in routes via CICD. 

Related Tasks:
https://github.com/openshiftio/openshift.io/issues/614
https://github.com/openshiftio/openshift.io/issues/624
