### ISSUE TITLE
Analytics stream: Current Checklist

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#706]
Success criteria for improving recommendations require accuracy of 70% across entire spectrum of GitHub repositories  for VertX, SpringBoot, Python, .NET ecosystems. 

Along the trend around registered users at OSIO, Python has been de-prioritised (for the current train) and replaced with Node ecosystem. Any of the below tasks related to Python are stretch goals.

These tasks been derived from these following epics:

#622 
#623 
#683 
#742
#611 
#613 

- [ ] Wrap up License outlier work items
- [ ] Ingest All manifest files (at GitHub) for VertX, SpringBoot, Node and .NET
- [ ] Algorithm for generating tags for Maven and feed these tags to Analytical models
- [ ] Algorithm for generating tags for .NET and feed these tags to Analytical models
- [ ] Algorithm for generating tags for Node and feed these tags to Analytical models
- [ ] Algorithm for generating tags for Python and feed these tags to Analytical models
- [ ] Determine the % of manual tagging required for Maven (Vertx and Springboot)
- [ ] Determine the % of manual tagging required for Node
- [ ] Determine the % of manual tagging required for .NET
- [ ] Determine the % of manual tagging required for Python
- [ ] Setup new OpenShift container for .NET ecosystem
- [ ] Setup new OpenShift container for Node ecosystem
- [ ] Display reason (to OSIO user) for recommending an alternative package 
- [ ] Generate recommendations for alternative packages as per https://docs.google.com/document/d/1VM5JLrM1DCd-hKdB2RAXrarT4sZhtliXV1wRgYLi7Tg/
- [ ] Display reason (to OSIO user) for recommending a companion package 
- [ ] Generate recommendations for companion packages as per https://docs.google.com/document/d/1VM5JLrM1DCd-hKdB2RAXrarT4sZhtliXV1wRgYLi7Tg/ 
- [ ] Prepare ground truth, plan, measure accuracy for Maven ecosystem across GitHub repositories
- [ ] Prepare ground truth, plan, measure accuracy for Node ecosystem across GitHub repositories
- [ ] Prepare ground truth, plan, measure accuracy for .NET ecosystem across GitHub repositories
- [ ] Prepare ground truth, plan, measure accuracy for Python ecosystem across GitHub repositories

**Comment by miteshvp** [comment]
Closing this as no longer relevant
