### ISSUE TITLE
Tags and free text gathering 

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#726]
This epic covers tags gathering that would help us tag different projects based on gathered files written in natural language.

- Tags gathering - ordered by priority
  - [x] Gather tags from MVN Repository #712
  - [ ] Gather tags from StackOverflow #710
  - [ ] Gather tags from npm.js #725 - not part of sprint 137
  - [ ] Gather tags from nuget.org #810 - not part of sprint 137

- Free text gathering - ordered by priority
  * Maven ecosystem (Java)
    - [x] Project's README file if project is hosted on GitHub
    - [x] Project description
    - [ ] TBD - other sources? - no other known sources for this ecosystem
  * NPM ecosystem (JavaScript)
    - [x] Gather free text present at NPM project description page and collect keywords present #728
    - [x] Project's README file if project is hosted on GitHub
    - [x] Project description
  * PyPI ecosystem (Python)
    - [x] Gather free text present at PyPI project description page and collect keywords present #727
    - [x] Project's README file if project is hosted on GitHub
    - [x] Project description
  * Nuget ecosystem (.NET)
    - [x] Project description
    - [x] Project's README file if project is hosted on GitHub
    - [ ] Project description on nuget.org #808 - not part of sprint 137

**Comment by fridex** [comment]
An overview that was done by @msrb on sources and tags availability https://docs.google.com/document/d/1_-Jf84fAl1DvJ5piim44pAgaaM1cSowJuFiYdqs7XzU/edit

**Comment by miteshvp** [comment]
@fridex - For python ecosystem there are two tasks that sounds similar. Is Project description different from Gather free text present at PyPI project description page and collect keywords present #727. Same for other ecosystems as well.

**Comment by fridex** [comment]
> @fridex - For python ecosystem there are two tasks that sounds similar. Is Project description different from Gather free text present at PyPI project description page and collect keywords present #727. Same for other ecosystems as well.

Yes, it's different. By PyPI description page I mean pages such as [this one](https://pypi.python.org/pypi/celery/) that state a brief overview for projects. By description I mean short project description that is present in releases - e.g. [setup.py](https://github.com/celery/celery/blob/master/setup.py#L207). The same applies for other ecosystems,

**Comment by joshuawilson** [comment]
You don't have to close it but you can't stay here. Please close or move to backlog or next sprint.

**Comment by miteshvp** [comment]
@fridex @pkajaba - Any updates here? Is there more work to be done or can we close this issue?

**Comment by fridex** [comment]
> @fridex @pkajaba - Any updates here? Is there more work to be done or can we close this issue?

The status of this epic is up2date. The open (linked) workitems were not planned for the upcoming sprint.

**Comment by miteshvp** [comment]
This work is no longer relevant. Closing this.
