### ISSUE TITLE
Local Setup for PGM Training + Scoring

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#747]
#### Description
Users should be able to get recommendations for a sample stack in local environment

##### Tasks
- [ ] Local docker environment for PGM training with one sample stack
- [ ] Local docker environment for PGM scoring
- [ ] Integrate docker setup with main fabric8-analytics

**Comment by krishnapaparaju** [comment]
Does this involve changing the current 'compose' script to bring up docker containers on the local machine ?

**Comment by miteshvp** [comment]
@krishnapaparaju - yes, PGM local deployment scripts needs to be added and docker-compose under common repo needs to be modified.

**Comment by miteshvp** [comment]
moving back to Analtyics backlog. Will pick up this task as part of sprint 139 based on resource availability

**Comment by krishnapaparaju** [comment]
@miteshvp Dev. cluster would need to be the starting point for development activity, can close this issue.

**Comment by miteshvp** [comment]
@krishnapaparaju makes sense.
