### ISSUE TITLE
Improve UX when creating a Work Item 

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#782]
## Goal
The goal of this issue is to list issues in the UX, in the flow and in the delivered experiences when a user wants to create a work item.

## Current Flow 
Starting from an empty space, there are two entry points to create a new WI:
- From the "WI Widget" on the dashboard
- After going on "Plan" tab and clicking on the "create" button either in the center of the screen or top right.

**Stage 1**
![screen shot 2017-09-08 at 09 16 39](https://user-images.githubusercontent.com/1636769/30200247-74e7d0ca-9476-11e7-8283-8c53c1a791c1.png)

Once the user clicked on that button - he is getting a new page. This page is missing all the application context: there is no navigation and there is a single choice to do. It takes all user's browser window. 

**Stage 2**
![screen shot 2017-09-08 at 09 17 11](https://user-images.githubusercontent.com/1636769/30200380-e633e44e-9476-11e7-9622-3be80c402aa3.png)

Once the user choose a work item type. There is a succession of screens loaded. First the user is redirected to the list of the WI and then a new window is displayed - the WI detail page.

**Stage 3**
![when-creating](https://user-images.githubusercontent.com/1636769/30200456-4756f8e2-9477-11e7-8fce-b6fd2653325d.gif)

Once the user is in the WI detail page - the layout is different from **Stage 2**. User is getting application context.

![screen shot 2017-09-08 at 09 23 34](https://user-images.githubusercontent.com/1636769/30200569-ca35aba0-9477-11e7-8b59-055f7022e6db.png)

A new work item is created but with empty/placeholder fields. User can't really understand what he has to do, what are the requested actions. User is not able to create the WI without selecting the fields with his mouse - he can't use only his keyboard. Moreover - if the user selected a wrong WI type, he is now not able to change it.

## Improvements 
The flow should be more logical - defining a WI type should not be the only field that is mandatory in order to create a WI. There should be only a single "Modal" to create a WI, not 2. 

We need to rework the WI creation modal:
- [ ] Provide a clear title "New Work Item" 
- [ ] The first field should be the title
- [ ] The second field should be the WI Type
- [ ] The third field will be the description 
- [ ] We put a 'Cancel button' and a 'Create Work Item" button at the bottom of the flow
- [ ] We handle keyboard navigation - so it's possible to move from field to fields and create the WI without having to take the mouse
- [ ] We handle "esc" key to hide the modal

That modal, needs to be displayed in the current navigation context of the user. 

Here is a mockup:
![wi-creation](https://user-images.githubusercontent.com/1636769/30203347-1a3019a6-9482-11e7-97dd-23c3e8ced9ec.png)

Once the Work Item is created, the user is redirected in the WI detail screen. 
- [ ] We remove the loading behavior that is described in **Stage 3**

Note: This is just "basic" improvements - there is much things to think about and include in this flow (defining labels, area, assigning). But at least it makes the flow a bit more understandable/usable.

**Comment by joshuawilson** [comment]
cc @michaelkleinhenz @catrobson

**Comment by catrobson** [comment]
@mganesan @smahil

@slemeur - Please also refer to the "end game vision" of creating work items here: https://redhat.invisionapp.com/share/6RCWHA1TX#/245740015_Slide068

**Comment by qodfathr** [comment]
Closing as this UI has been radically redesigned.
