### ISSUE TITLE
File attachments with descriptions and comments in a Work Item

### ISSUE THREAD

**Issue by slemeur** [openshiftio/openshift.io#795]
# Description
As a user, I want to add attachments to Work Items which can be helpful along with the description of the WI, and also along with a comment.

# Acceptance Criteria
- [ ] The user is able to upload files when creating a work item.
- [ ] The user is able to upload files after a work item has been created and add it to the description of the WI
- [ ] The user is able to upload files when he is adding a comment.
- [ ] The user can remove an attachment from a WI description or from a comment.
- [ ] An attachment's size is limited to 10Mo (to start)
- [ ] It is possible to attach: png, gif, jpeg, txt, pdf, zip and gz
- [ ] A user can view images (png, gif, jpeg) directly from the WI by clicking on them, other files will be downloaded.
- [ ] A user can download all attachments of an WI in a single archive

Ideally:
- [ ] The user is able to add an attachment by using drag&drop in the description/comment text area, if it's an image it will be inserted and rendered in the description/comment.

## Linked issues
https://github.com/fabric8-ui/fabric8-planner/issues/2027

**Comment by joshuawilson** [comment]
@michaelkleinhenz since this appears to be focused on the Planner, I'm adding it to your backlog.

**Comment by debloper** [comment]
I believe we are to design it to save and receive files over a CDN server instead of the Planner web-server from the get go? This will save the overhead work of _readjustments_ later on.

In that case the process for uploading the files goes like:
- User intents to attach a file to a Planner entity (not necessarily WI only, but that's good first cut)
- User is given a file uploading interface (browse OR drag-n-drop)
- On submission, the file is POSTed to the CDN for storing, and success response is received along with the UUID to refer the file from now on
- Planner inserts this information in the entity (WI) and POSTs this to WIT server (which puts it in the DB)
- If all goes well, now the file is stored and can be retrieved with the UUID. Failure cases can be handled in generic manner

And to retrieve the file, we simply:
- Acquire the UUID over API request from WIT
- CDN is requested to provide the file by UUID (optionally, specifying custom resolution for media)
- CDN sends the file with proper MIME type (optionally, after converting the media as requested)
- Client renders the file or allows the user to download it depending on the MIME type

How about that?

**Comment by nimishamukherjee** [comment]
@openshiftio/uxd-team do we want to support file attachments in comments, description, etc

**Comment by joshuawilson** [comment]
@nimishamukherjee since the request is coming from a PM, I think we should be asking them to add this to their backlog. (and work out the details with PM and Eng)

**Comment by Veethika** [comment]
@serenamarie125 ^
