### ISSUE TITLE
[EPIC] Run linters on Python code

### ISSUE THREAD

**Issue by fridex** [openshiftio/openshift.io#829]
# Description

As Python is a dynamic programming scripting language with dynamic typing, some programming errors are not easy to catch in any other way except by running directly code. To cover at least some errors that can be issued it would be nice to set up linters that can find and report some errors that we can prevent from before pushing code to production. Linters also help with code quality and respect general programming coding guidelines and Python coding guidelines ([PEP8](https://www.python.org/dev/peps/pep-0008/)) making code easier to read, easier to maintain, easier to extend and easier to contribute to.

We could check and set up well known linters used in Python community. Strong candidates are [Pylint](https://www.pylint.org/) and [Coala](https://github.com/PyCQA/pydocstyle/) bears. It would be also great to keep Python's docstrings well formatted according to Python's standard ([PEP257](https://www.python.org/dev/peps/pep-0257/)) so we can use docstrings to automatically generate documentation for project - for this reason we could set up [pydocstyle](https://github.com/PyCQA/pydocstyle/).

These linters should be run in CI on every PR to check code consistency and also to save reviewer's time. We can report only errors as a starting point and later rework old code that does not respect Python standards so we fix also warnings.

Take a look at [proposal regarding code guidelines](https://github.com/fridex/coding-guidelines/blob/master/new_project/Makefile) that has already mentioned linters set up.

# Acceptance criteria

- [x] linters are set up, suggestions and on linters configuration are discussed so configuration of linters is unified across the whole team (configuration is not very strict not to reduce devs productivity)
- [x] code is checked by linters against general programming errors in CI on every PR and CI fails if linters report errors
- [x] there is a mechanism to check for linter errors also on local development so a dev can check code quality before opening a PR
- [x] old code that is not compliant to errors is re-factored to at least fix error reports

**Comment by msrb** [comment]
This looks complete-ish to me. @pkajaba @tisnik could you guys please confirm?

**Comment by fridex** [comment]
> This looks complete-ish to me. @pkajaba @tisnik could you guys please confirm?

I would say yes - marking as completed. Feel free to adjust task status if there are some other bits necessary that I missed.
