### ISSUE TITLE
Add unit test to improve code coverage

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#923]
_From @corinnekrych on May 2, 2017 13:54_

Test in isolation:
- services,
- components/directives,
- modules

Let's sub-task the uni tests per module (ie: functionalities of fabric8-ui):
- [ ] unit test for [space-wizard module](https://github.com/fabric8io/fabric8-ui/issues/1545)
- [ ] unit test for settings-wizard module
- [ ] unit test for profile module
- [ ] unit test for shared module
- [ ] unit test for settings module
- [ ] unit test for dashboard module
- [ ] unit test for about-modal module 
- [ ] unit test for landing-page / home / getting started / header / footer

_Copied from original issue: fabric8-ui/fabric8-ui#1238_

**Comment by joshuawilson** [comment]
Cleaned up the and moved the listed to the main description so that it would be easier to track.

**Comment by aptmac** [comment]
@joshuawilson when you mention modules, say profile for instance, does that mean including tests for the components under src/app/profile? So adding tests for profile/tenant, profile/update, etc?

**Comment by joshuawilson** [comment]
Yes, we need unit tests for each component.

**Comment by aptmac** [comment]
I cannot find any mention of the "settings-wizard" module, is this the space-settings module?

**Comment by joshuawilson** [comment]
We don't have anything like that. I have to wonder if she meant the `app-wizard`.
