### ISSUE TITLE
3 Scale Gateway - Setting up and consuming

### ISSUE THREAD

**Issue by arunkumars08** [openshiftio/openshift.io#959]
## Description
This task will provide a layer/API to set up basic things necessary to have a 3 scale configuration ready.

## How
We currently segregate based on every unique organization. For every org., there will be a new 3 scale infrastructure setup and route created.

## Usage
Based on the JWT auth token, we identify the organization. Using that, we register in the case where the org is not already registered, or retrieve the route from the already registered org.

## Tasks
We go ahead with a manually created account, so that that can be used for all orgs.

- [x] Automate creation of Service,
- [x] Automate creation of Service plan,
- [x] Automate creation of Application Plan,
- [x] Automate creation of Application,
- [x] Automate creation of Rate Limitings,
- [x] Automate creation of Metric,
- [x] Automate creation of Mappings,
- [x] Automate creation of Proxy,
- [x] Automate creation of Promote to Prod.

All the above tasks are necessary for setting up a full scaled environment in 3Scale for an organization.

In case of Retrieving, we just have to use 

Service, Application, Proxy APIs of 3 Scale to get the registered route and other required information.

**Comment by arunkumars08** [comment]
Changes are moved to a new repository under fabric8-analytics organization - https://github.com/fabric8-analytics/3scale-admin-gateway

For rollback, we need to think of a good mechanism. That is still pending in this story.

**Comment by samuzzal-choudhury** [comment]
This work is completed in the sprint 138 and the rest of the works are going to be tracked in the user story https://github.com/openshiftio/openshift.io/issues/701

**Comment by joshuawilson** [comment]
Added to Sprint 138 so we can track what we closed.
