### ISSUE TITLE
Accounting for weighted dependency set for PGM training

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#973]
### Description
Currently all GitHub stacks used for training the model have same weight-age. i.e the model treats all stacks to be equally popular and used. But if there a very popular GitHub stack, then we need to assign it more weight-age to account for its popularity and usage.

#### Acceptance Criteria
Need to train PGM model to account for weight-age and check the results against the quick starter applications.

##### Tasks
- [x] Define the format for the new raw input manifest.json [Merged here](https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/61)
- [x] Add the weights in the occurrence matrix, (if this does not work then do the next step)
- [x] Pre-process the raw manifest.json to generate the clean manifest list to be fed to the  PGM
- [x] Add tests for the pre-processing.
- [ ] Re-train the model.
- [ ] Check difference in results for quick starter.

##### Depends on
- [x] Capture Github Statistics for each manifest we collect (@Saket)

**Comment by sara-02** [comment]
@miteshvp Just repeating the dependencies in the `manifest.json` will explode the JSON. We can look at improving the co-occurrence matrix to account for the weights instead. Changing at the manifest level will be the last resort.

**Comment by miteshvp** [comment]
@sara02 - think about normalizing the weighted factor

**Comment by miteshvp** [comment]
@sara02 - can you please update this issue. Please update here with your findings/observations

**Comment by miteshvp** [comment]
@sara02 - Why is this issue not being closed yet? Please share your findings and close this issue.

**Comment by sara-02** [comment]
Closing this issue and the corresponding PR, as it is no longer needed.
https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/79
In case we need to add weights via co-occurrence matrix, we can reopen the issue.
