### ISSUE TITLE
Enable Unit testing for components of analytics platform. 

### ISSUE THREAD

**Issue by sara-02** [openshiftio/openshift.io#974]
### Description
Currently, the unit test are present under the folder of each component, but and not included in the CI testing.

#### Acceptance Criteria: 
Have unit tests enabled in the CI.

#### Todo:
- [x] Add a repository wide test folder.
- [x] Add the unit tests to the CI for the repository.
- [x] Rename the tests to reflect the component it is testing.

**Comment by miteshvp** [comment]
@sara02 please re-format the contents as per https://github.com/openshiftio/openshift.io/issues/973

**Comment by sara-02** [comment]
@miteshvp done.

**Comment by joshuawilson** [comment]
You don't have to close it but you can't stay here. Please close or move to backlog or next sprint.

**Comment by miteshvp** [comment]
@sara-02 - any updates on this one? Can we close this?

**Comment by sara-02** [comment]
Finally fixed by @rootAvish  via https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/137 and https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/pull/138
