### ISSUE TITLE
[5] Display Reasoning for recommendations

### ISSUE THREAD

**Issue by SaketJNU** [openshiftio/openshift.io#984]
# Description:
Provide the reason for each recommendation
## Acceptance criteria
Show simple reasoning behind any recommendations (English Sentence)
## Task
- [ ] Phrase a sentence for recommended companion packages.
- [ ] Phrase a sentence for recommended alternate packages.

### UI Changes
- [ ] UI Changes in the stack report
    - [ ] Implement a tooltip to highlight the recommendation reason
    - [ ] Integrate on mouse over of recommendations

**Comment by SaketJNU** [comment]
A PR https://github.com/fabric8-analytics/fabric8-analytics-server/pull/171 is opened for both mentioned tasks.

**Comment by arunkumars08** [comment]
@miteshvp @SaketJNU Is this API change available in production? I don't see it when I ran a new stack analysis. 
This is what I 've just triggered (https://recommender.api.openshift.io/api/v1/stack-analyses/76830a2a374f43a6bfd61e942c85649b).

Correct me if I am missing something?

**Comment by SaketJNU** [comment]
HI @arunkumars08 ; The changes are not available at desired place as the PR https://github.com/fabric8-analytics/fabric8-analytics-server/pull/171 is still open with no further comment. Once, this PR will get approved, merged and deployed on prod, you may  say the changes in response if an input-stack has that. 
Thank

**Comment by samuzzal-choudhury** [comment]
Closing this as the first cut has been deployed on production.
