### ISSUE TITLE
[8] PGM to handle unknown packages at the time of training

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#985]
## Description

Currently the PGM training works on the assumption that the training data to it and will be passed a package to topic map where all packages have some tags associated with them. The PGM training will fail if this assumption was to fall through in some case. The idea here is to do a short spike and either figure out how to deal with such packages in a better way or have the PGM training discard them so that training still happens.

## Acceptance criteria

In case where packages have no tags, make sure PGM is still able to train.

## Tasks

- [x]  Explore other possible options to not have to discard the PGM input packages that have no tags
- [x]  Option 2: Label these packages using the group name and the package name (max 4 labels on each)
- [x]  Retrain the PGM using this logic and make sure it doesn't fail
- [x]  Code the agreed upon logic
- [x]  Write unit tests
- [x] Address review comments
- [x]  Push to production
- [x] ~~Option 1: Label these packages with the package name only~~
- [x]  ~~Option 3: Failover if both 1 & 2 fail: discard these packages during pre-processing~~

## Dependencies

None.

**Comment by rootAvish** [comment]
Picking up #987 while I'm waiting on a review for PR.

**Comment by rootAvish** [comment]
Closing this as changes pushed to production.

**Comment by rootAvish** [comment]
Pushed to production, marking done.
