### ISSUE TITLE
[8] Task Iteration 1 - Tagging related Statistics (Observations, suggest improvements, statistics)

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#987]
## Description

With the tagging accuracy report first cut released(see https://github.com/fabric8-analytics/devnull/pull/1) we need to add more metrics to the same to have a more clear picture and take up any possible enhancements to the same so by the end of the sprint we have a more clear picture of where we are with respect to automated tagging.

## Acceptance criteria

Have more metrics surrounding the automated tagging and possibly have increased accuracy by the end of this sprint.

## Task list
- [x] Add the name of all programming languages to the stop words list
- [x] Collect a list of all packages for which changes in thresholding would give accurate tags
- [x] Read and understand the tagger code to look for enhancements to the existing flow
- [x] Check if multi document topic modelling on stackoverflow's Q&A using LDA is a good idea
- [x] Metric around how many packages have how many tags in common
- [x] For the packages for which manual tags were collected, evaluate the tagging according to the rank at which these packages occur.

# 

Suggestions for possible enhancements (to be picked in later sprints)

* Tag each package with tags that have already been use to tag packages (unless the number of said packages has reached four, the maximum number of topics that can be associated with the PGM for now). [As per discussion, implementation of suggestions will be taken up in the next sprint]

## Dependencies
- Tagger needs to be re-run by @fridex if any enhancements to it are taken up in #976 for the script or any future versions of it to produce a different result than before.

**Comment by rootAvish** [comment]
All review comments in the final PR have been addressed, this script will not be pushed to production and the results will be published in a spreadsheet for public viewing instead.

**Comment by miteshvp** [comment]
@rootAvish - can we also reference the spreadsheet where you are maintaining this observations?

**Comment by rootAvish** [comment]
https://docs.google.com/spreadsheets/d/1X6ClIqc3sJZXR7mrl0RvJ9FxM9q2tJfJkdjRatybyFo/edit#gid=0
