### ISSUE TITLE
[User-story] - Curate data for machine generated stacks

### ISSUE THREAD

**Issue by miteshvp** [openshiftio/openshift.io#996]
To be filled

Subtasks:
- [x] [Generate component-categories mapping for springboot components from start.spring.io](https://github.com/openshiftio/openshift.io/issues/1009)
- [x] [Generate component-categories mapping for vertx components from vertx.io](https://github.com/openshiftio/openshift.io/issues/1010)
- [x] [Generate a list of common categories](https://github.com/openshiftio/openshift.io/issues/1011)
- [x] [Map the respective components of vertx and springboot to the generated list of common categories](https://github.com/openshiftio/openshift.io/issues/1012)

**Comment by sunilk747** [comment]
This is the final JSON file generated for machine generated stacks. https://pastebin.com/hgLSBNSR

**Comment by sunilk747** [comment]
This is the final JSON file generated for machine generated stacks. https://pastebin.com/hgLSBNSR
